// AUTO-GENERATED by apps/web/scripts/build-tool-catalog.ts from packages/ui — do not edit.
// Run it after changing a component kit 2 re-exports, or the curated notes beside them.
import type { CatalogEntry } from './catalog'

/** The app's own components (@visvine/ui) as kit 2 re-exports them. */
export const UI_CATALOG: readonly CatalogEntry[] = [
  {
    "name": "Alert",
    "kind": "component",
    "what": "A notice: a 2px rule in its colour down the left, then the words.",
    "when": "Only when something is actually wrong or needs saying once — a normal state is silent. In the app: admin, agents, connectors and 8 more.",
    "props": "variant?: 'error' | 'info' | 'warning' | 'success' · onDismiss?: () => void · inline?: boolean",
    "snippet": "<Alert variant=\"warning\">Two deals have no owner.</Alert>"
  },
  {
    "name": "Avatar",
    "kind": "component",
    "what": "A person's (or a space's) picture, falling back to a silhouette or initials.",
    "when": "Beside a name in a list or a record — the Directory and messages draw people this way. In the app: admin, agents, connectors and 6 more.",
    "props": "name: string · imageUrl?: string | null · size?: 'xs' | 'sm' | 'md' | 'chip' | 'lg' | 'xl' · accentColor?: string · fallback?: 'silhouette' | 'initials' | 'space' · sizeClassName?: string · pixelSize?: number",
    "snippet": "<Avatar name=\"Ada Lovelace\" size=\"sm\" />"
  },
  {
    "name": "Checkbox",
    "kind": "component",
    "what": "The platform's own checkbox, painted in the accent (`accent-color`).",
    "when": "A choice that joins a set. A setting that switches something on is a Toggle. In the app: events, resources, shared.",
    "props": "checked: boolean · onChange: (checked: boolean) => void · label?: ReactNode · indeterminate?: boolean · disabled?: boolean · invalid?: boolean · size?: 'sm' | 'md' · 'aria-label'?: string",
    "snippet": "<Checkbox checked={false} onChange={() => {}} label=\"Include archived\" />"
  },
  {
    "name": "ConfirmDialog",
    "kind": "component",
    "what": "A modal that asks before a destructive or irreversible act, and can make the person type a name first.",
    "when": "Before anything destructive or irreversible. Pass confirmText for the most dangerous. In the app: admin, connectors, directory and 9 more.",
    "props": "open: boolean · title: string · body?: React.ReactNode · confirmLabel?: string · destructive?: boolean · confirmText?: string · error?: React.ReactNode · closeOnBackdrop?: boolean · closeOnEscape?: boolean · onConfirm: () => void | Promise<void> · onClose: () => void",
    "snippet": "<ConfirmDialog open={false} title=\"Delete this deal?\" confirmLabel=\"Delete\" destructive onConfirm={() => {}} onClose={() => {}} />"
  },
  {
    "name": "IconButton",
    "kind": "component",
    "what": "A square, quiet button that is only an icon: the label is its name for a screen reader and its title under the pointer.",
    "when": "A toolbar action that is only an icon; its label is its name for a screen reader. In the app: resources, tools.",
    "props": "label: string · icon: ReactNode · size?: 'sm' | 'md' · active?: boolean",
    "snippet": "<IconButton label=\"More\" onClick={() => {}} icon={<span aria-hidden>⋯</span>} />"
  },
  {
    "name": "LoadingText",
    "kind": "component",
    "what": "A centred, muted \"Loading…\" line for a view that has nothing to show yet.",
    "when": "Instead of a spinner when a whole view is waiting. In the app: admin, pages.",
    "props": "text?: string",
    "snippet": "<LoadingText />"
  },
  {
    "name": "Menu",
    "kind": "component",
    "what": "A small popover of actions under a trigger — the overflow (…) of a toolbar.",
    "when": "The overflow (⋯) of a row or a toolbar — actions that do not earn a button of their own. In the app: messages, resources, tools.",
    "props": "trigger: (props: { open: boolean; toggle: () => void; … · items: MenuItem[] · align?: 'start' | 'end' · placement?: 'below' | 'above' · label: string",
    "snippet": "<Menu label=\"Deal actions\" items={[{ id: 'archive', label: 'Archive', onSelect: () => {} }]} trigger={({ toggle }) => <button type=\"button\" onClick={toggle}>⋯</button>} />"
  },
  {
    "name": "Row",
    "kind": "component",
    "what": "Children side by side, a fixed step apart, centred on one line.",
    "when": "A row of buttons, a label beside its control, a chip beside a name.",
    "props": "gap?: 0 | 0.5 | 1 | 1.5 | 2 | 2.5 | 3 | 4 | 5 | 6 |… · align?: 'start' | 'center' | 'end' | 'stretch' | 'bas… · justify?: 'start' | 'center' | 'end' | 'between' · wrap?: boolean · as?: ElementType",
    "snippet": "<Row gap={2}>\n  <span>Left</span>\n  <span>Right</span>\n</Row>"
  },
  {
    "name": "SearchInput",
    "kind": "component",
    "what": "A text input with a search glyph and a clear button.",
    "when": "Above a list that filters as you type — the Directory and the pickers. In the app: admin, connectors, directory and 4 more.",
    "props": "value: string · onChange: (value: string) => void · placeholder?: string · autoFocus?: boolean · icon?: React.ReactNode · size?: 'sm' | 'md' | 'lg'",
    "snippet": "<SearchInput value=\"\" onChange={() => {}} placeholder=\"Search deals\" />"
  },
  {
    "name": "SettingsSection",
    "kind": "component",
    "what": "A flat settings section: a small bold heading, a muted line, and a hairline between siblings.",
    "when": "A Tool's own settings view: small heading, one muted line, hairlines between sections, no card. In the app: admin, pages, settings.",
    "props": "title: React.ReactNode · description?: React.ReactNode · action?: React.ReactNode · flush?: boolean · large?: boolean",
    "snippet": "<SettingsSection title=\"Pipeline\">\n  <p>Stages</p>\n</SettingsSection>"
  },
  {
    "name": "Skeleton",
    "kind": "component",
    "what": "A single shimmering placeholder block.",
    "when": "The shape of rows while they load, so the page does not jump when they arrive. In the app: connectors, directory, discover and 5 more.",
    "props": "className — its size and shape",
    "snippet": "<Skeleton className=\"h-4 w-1/3 rounded\" />"
  },
  {
    "name": "Toggle",
    "kind": "component",
    "what": "Standard toggle switch — one size everywhere (40×24px track, 16px thumb).",
    "when": "A setting that switches something on — beside the title it controls, never a second row saying the same. In the app: admin, agents, connectors and 5 more.",
    "props": "checked: boolean · onChange: (checked: boolean) => void · label?: React.ReactNode · disabled?: boolean · 'aria-label'?: string",
    "snippet": "<Toggle checked={false} onChange={() => {}} aria-label=\"Show closed\" />"
  }
]
