/**
 * Deterministic local-dev seed.
 *
 * Produces a realistic CRM/social graph: anchor users (deterministic, always
 * present), faker-generated background users, Barabási–Albert preferential-
 * attachment connection graph, time-spread DM/group conversations, and a
 * handful of named edge cases.
 *
 * To add a named scenario (saved bug repro), create
 * apps/web/prisma/seed/scenarios/<name>.ts exporting a default async function
 * that takes (prisma, ctx) and import + invoke it from `main()` below.
 */

import { PrismaClient } from "@prisma/client";
import { faker } from "@faker-js/faker";
import seedrandom from "seedrandom";

const SEED = 42;
faker.seed(SEED);
const rng = seedrandom(String(SEED));

const USER_COUNT = Number(process.env.SEED_USER_COUNT ?? 1000);
const BA_M = 2; // edges per new node — controls hub concentration

const COMMUNITY_ID = "community:local-dev";
const COMMUNITY_NAME = "Local Dev Community";

const prisma = new PrismaClient();

interface SeededUser {
  id: string;
  name: string;
  email: string;
  isAnchor: boolean;
  anchorRole?: "admin" | "moderator" | "member";
  isHub?: boolean;
  isIsolated?: boolean;
  isInactive?: boolean;
  // PersonNode id (matches Person.id, which is the graph node id)
  personNodeId: string;
}

const ANCHORS: Array<Omit<SeededUser, "personNodeId">> = [
  { id: "user_dev_admin",     name: "Dev Admin",  email: "admin@local.dev",     isAnchor: true, anchorRole: "admin" },
  { id: "user_dev_moderator", name: "Dev Mod",    email: "moderator@local.dev", isAnchor: true, anchorRole: "moderator" },
  { id: "user_dev_alice",     name: "Alice Dev",  email: "alice@local.dev",     isAnchor: true, anchorRole: "member" },
  { id: "user_dev_bob",       name: "Bob Dev",    email: "bob@local.dev",       isAnchor: true, anchorRole: "member" },
  { id: "user_dev_hub",       name: "Hub Dev",    email: "hub@local.dev",       isAnchor: true, anchorRole: "member", isHub: true },
  { id: "user_dev_isolated",  name: "Isolated",   email: "isolated@local.dev",  isAnchor: true, anchorRole: "member", isIsolated: true },
  { id: "user_dev_blocked",   name: "Blocked",    email: "blocked@local.dev",   isAnchor: true, anchorRole: "member" },
  { id: "user_dev_pending",   name: "Pending",    email: "pending@local.dev",   isAnchor: true, anchorRole: "member" },
  { id: "user_dev_unicode",   name: "李明 🌸 Тест", email: "unicode@local.dev",  isAnchor: true, anchorRole: "member" },
];

async function wipeData() {
  // Delete in dependency order. Anything not covered here will cascade via
  // onDelete: Cascade once we drop UserCommunity / User / Community / Node.
  console.log("Wiping existing data…");
  await prisma.$transaction([
    prisma.userBlock.deleteMany({}),
    prisma.messageReaction.deleteMany({}),
    prisma.messageDelivery.deleteMany({}),
    prisma.messageImage.deleteMany({}),
    prisma.messageMention.deleteMany({}),
    prisma.messageStar.deleteMany({}),
    prisma.messageAttachment.deleteMany({}),
    prisma.messageLinkPreview.deleteMany({}),
    prisma.message.deleteMany({}),
    prisma.conversationMember.deleteMany({}),
    prisma.conversation.deleteMany({}),
    prisma.link.deleteMany({}),
    prisma.attendee.deleteMany({}),
    prisma.privateColumnValue.deleteMany({}),
    prisma.privateColumn.deleteMany({}),
    prisma.communityColumnValue.deleteMany({}),
    prisma.communityColumn.deleteMany({}),
    prisma.communityColumnRequest.deleteMany({}),
    prisma.userCommunity.deleteMany({}),
    prisma.person.deleteMany({}),
    prisma.node.deleteMany({}),
    prisma.user.deleteMany({}),
    prisma.community.deleteMany({}),
  ]);
}

async function createCommunity() {
  console.log("Creating community…");
  return prisma.community.create({
    data: {
      id: COMMUNITY_ID,
      name: COMMUNITY_NAME,
      description: "Local development community — generated by seed.ts.",
      location: "localhost",
      tags: ["dev", "local", "seeded"],
      country: "AU",
    },
  });
}

async function createAnchorUsers(): Promise<SeededUser[]> {
  console.log("Creating anchor users…");
  const out: SeededUser[] = [];
  for (const a of ANCHORS) {
    const personNodeId = `person:${a.id.replace(/^user_/, "")}`;
    await prisma.user.create({
      data: {
        id: a.id,
        email: a.email,
        name: a.name,
        emailVerified: true,
        isActive: true,
      },
    });
    await prisma.userCommunity.create({
      data: {
        userId: a.id,
        communityId: COMMUNITY_ID,
        role: a.anchorRole ?? "member",
      },
    });
    // Person record — also serves as the graph Node (Person.id == Node.id)
    await prisma.node.create({
      data: {
        id: personNodeId,
        type: "Person",
        name: a.name,
        communityId: COMMUNITY_ID,
        metadata: { seeded: true, anchor: true },
      },
    });
    await prisma.person.create({
      data: {
        id: personNodeId,
        userId: a.id,
        name: a.name,
        bio: faker.person.bio(),
        location: faker.location.city(),
        hasOnboarded: true,
      },
    });
    out.push({ ...a, personNodeId });
  }
  return out;
}

async function createBackgroundUsers(count: number): Promise<SeededUser[]> {
  console.log(`Creating ${count} background users…`);
  const out: SeededUser[] = [];
  // Batch user creation for speed. createMany doesn't return rows we need
  // for downstream foreign keys, but Person/Node ids are derived from User id.
  const userRows: Array<{
    id: string;
    email: string;
    name: string;
    emailVerified: boolean;
    isActive: boolean;
  }> = [];
  const personRows: Array<{
    id: string;
    userId: string;
    name: string;
    bio: string;
    location: string;
    hasOnboarded: boolean;
  }> = [];
  const nodeRows: Array<{
    id: string;
    type: string;
    name: string;
    communityId: string;
    metadata: object;
  }> = [];
  const userCommRows: Array<{
    userId: string;
    communityId: string;
    role: string;
  }> = [];

  for (let i = 0; i < count; i++) {
    const id = `user_dev_bg_${String(i).padStart(5, "0")}`;
    const personNodeId = `person:bg_${String(i).padStart(5, "0")}`;
    const fullName = faker.person.fullName();
    const email = `bg-${i}@local.example`; // not @local.dev — won't show in dev login picker
    userRows.push({ id, email, name: fullName, emailVerified: true, isActive: true });
    nodeRows.push({
      id: personNodeId,
      type: "Person",
      name: fullName,
      communityId: COMMUNITY_ID,
      metadata: { seeded: true },
    });
    personRows.push({
      id: personNodeId,
      userId: id,
      name: fullName,
      bio: faker.person.bio(),
      location: faker.location.city(),
      hasOnboarded: true,
    });
    userCommRows.push({ userId: id, communityId: COMMUNITY_ID, role: "member" });
    out.push({
      id,
      name: fullName,
      email,
      isAnchor: false,
      personNodeId,
    });
  }

  // createMany in chunks to avoid hitting parameter limits.
  const chunk = 500;
  for (let i = 0; i < userRows.length; i += chunk) {
    await prisma.user.createMany({ data: userRows.slice(i, i + chunk) });
  }
  for (let i = 0; i < nodeRows.length; i += chunk) {
    await prisma.node.createMany({ data: nodeRows.slice(i, i + chunk) });
  }
  for (let i = 0; i < personRows.length; i += chunk) {
    await prisma.person.createMany({ data: personRows.slice(i, i + chunk) });
  }
  for (let i = 0; i < userCommRows.length; i += chunk) {
    await prisma.userCommunity.createMany({ data: userCommRows.slice(i, i + chunk) });
  }

  return out;
}

/**
 * Barabási–Albert preferential attachment.
 * Anchor "hub" user is placed early in the order so it accumulates many edges.
 * Anchor "isolated" user is excluded entirely.
 */
async function createSocialGraph(users: SeededUser[]) {
  console.log("Building Barabási–Albert connection graph…");
  const participating = users.filter((u) => !u.isIsolated);

  // Reorder: hub first, then other anchors, then background — so hub gets
  // many incoming preferential-attachment edges.
  const ordered = [
    ...participating.filter((u) => u.isHub),
    ...participating.filter((u) => u.isAnchor && !u.isHub),
    ...participating.filter((u) => !u.isAnchor),
  ];

  // Initial fully-connected core
  const m0 = BA_M + 1;
  const degree = new Map<string, number>();
  const core = ordered.slice(0, m0);
  const linkRows: Array<{
    sourceId: string;
    targetId: string;
    relationship: string;
    communityId: string;
  }> = [];

  for (let i = 0; i < core.length; i++) {
    for (let j = i + 1; j < core.length; j++) {
      linkRows.push({
        sourceId: core[i].personNodeId,
        targetId: core[j].personNodeId,
        relationship: "connected",
        communityId: COMMUNITY_ID,
      });
      degree.set(core[i].personNodeId, (degree.get(core[i].personNodeId) ?? 0) + 1);
      degree.set(core[j].personNodeId, (degree.get(core[j].personNodeId) ?? 0) + 1);
    }
  }

  // Preferential-attachment phase
  for (let i = m0; i < ordered.length; i++) {
    const newcomer = ordered[i];
    const candidates = ordered.slice(0, i);
    const chosen = pickWeighted(candidates, BA_M, degree);
    for (const c of chosen) {
      linkRows.push({
        sourceId: newcomer.personNodeId,
        targetId: c.personNodeId,
        relationship: "connected",
        communityId: COMMUNITY_ID,
      });
      degree.set(newcomer.personNodeId, (degree.get(newcomer.personNodeId) ?? 0) + 1);
      degree.set(c.personNodeId, (degree.get(c.personNodeId) ?? 0) + 1);
    }
  }

  console.log(`  generated ${linkRows.length} links`);
  const chunk = 1000;
  for (let i = 0; i < linkRows.length; i += chunk) {
    await prisma.link.createMany({ data: linkRows.slice(i, i + chunk) });
  }
}

function pickWeighted(
  candidates: SeededUser[],
  m: number,
  degree: Map<string, number>,
): SeededUser[] {
  // Use degree+1 to give zero-degree candidates a non-zero chance. Sample
  // without replacement.
  const pool = candidates.map((c) => ({ user: c, weight: (degree.get(c.personNodeId) ?? 0) + 1 }));
  let total = pool.reduce((a, b) => a + b.weight, 0);
  const out: SeededUser[] = [];
  for (let k = 0; k < m && pool.length > 0; k++) {
    let pick = rng() * total;
    let idx = 0;
    for (; idx < pool.length; idx++) {
      pick -= pool[idx].weight;
      if (pick <= 0) break;
    }
    if (idx >= pool.length) idx = pool.length - 1;
    const removed = pool.splice(idx, 1)[0];
    total -= removed.weight;
    out.push(removed.user);
  }
  return out;
}

async function createMessages(users: SeededUser[]) {
  console.log("Creating conversations and messages…");
  const eligible = users.filter((u) => !u.isIsolated && !u.isInactive);
  const dmCount = Math.floor(eligible.length * 0.3);
  const groupCount = Math.floor(eligible.length * 0.05);

  const startDate = new Date("2025-01-01T00:00:00Z");
  const endDate = new Date("2026-05-01T00:00:00Z");
  const recentStart = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const now = new Date();

  let totalMessages = 0;

  // DMs
  for (let i = 0; i < dmCount; i++) {
    const a = eligible[Math.floor(rng() * eligible.length)];
    let b = eligible[Math.floor(rng() * eligible.length)];
    while (b.id === a.id) b = eligible[Math.floor(rng() * eligible.length)];
    const dmKey = [a.id, b.id].sort().join(":");
    const existing = await prisma.conversation.findUnique({ where: { dmKey } });
    if (existing) continue;
    const conv = await prisma.conversation.create({
      data: {
        type: "DM",
        dmKey,
        createdById: a.id,
        members: {
          create: [
            { userId: a.id, role: "MEMBER" },
            { userId: b.id, role: "MEMBER" },
          ],
        },
      },
    });
    const msgCount = Math.floor(rng() * 30) + 1;
    const msgRows = [];
    for (let m = 0; m < msgCount; m++) {
      const sender = rng() < 0.5 ? a : b;
      msgRows.push({
        conversationId: conv.id,
        senderId: sender.id,
        text: faker.lorem.sentence({ min: 3, max: 18 }),
        createdAt: faker.date.between({ from: startDate, to: endDate }),
      });
    }
    await prisma.message.createMany({ data: msgRows });
    totalMessages += msgRows.length;
  }

  // Groups
  for (let i = 0; i < groupCount; i++) {
    const creator = eligible[Math.floor(rng() * eligible.length)];
    const memberCount = 5 + Math.floor(rng() * 11); // 5-15
    const memberPool = new Set<string>([creator.id]);
    while (memberPool.size < memberCount) {
      memberPool.add(eligible[Math.floor(rng() * eligible.length)].id);
    }
    const conv = await prisma.conversation.create({
      data: {
        type: "GROUP",
        name: faker.company.catchPhrase(),
        createdById: creator.id,
        members: {
          create: Array.from(memberPool).map((uid) => ({
            userId: uid,
            role: uid === creator.id ? ("ADMIN" as const) : ("MEMBER" as const),
          })),
        },
      },
    });
    const memberArr = Array.from(memberPool);
    const msgCount = Math.floor(rng() * 50) + 5;
    const msgRows = [];
    for (let m = 0; m < msgCount; m++) {
      const senderId = memberArr[Math.floor(rng() * memberArr.length)];
      msgRows.push({
        conversationId: conv.id,
        senderId,
        text: faker.lorem.sentence({ min: 3, max: 25 }),
        createdAt: faker.date.between({ from: startDate, to: endDate }),
      });
    }
    await prisma.message.createMany({ data: msgRows });
    totalMessages += msgRows.length;
  }

  // Recent activity pass — tag the last few messages from each anchor's
  // conversations with timestamps in the past 7 days so unread UI has data.
  const anchorIds = users.filter((u) => u.isAnchor && !u.isIsolated).map((u) => u.id);
  for (const uid of anchorIds.slice(0, 5)) {
    const memberships = await prisma.conversationMember.findMany({
      where: { userId: uid },
      take: 3,
    });
    for (const m of memberships) {
      const recentMsg = await prisma.message.findFirst({
        where: { conversationId: m.conversationId },
        orderBy: { createdAt: "desc" },
      });
      if (recentMsg) {
        await prisma.message.update({
          where: { id: recentMsg.id },
          data: {
            createdAt: faker.date.between({ from: recentStart, to: now }),
          },
        });
      }
    }
  }

  console.log(`  created ${totalMessages} messages`);
}

async function createEdgeCases(users: SeededUser[]) {
  console.log("Creating edge cases…");

  const alice = users.find((u) => u.id === "user_dev_alice")!;
  const blocked = users.find((u) => u.id === "user_dev_blocked")!;
  const pending = users.find((u) => u.id === "user_dev_pending")!;

  // Mutual block: blocked@ <-> alice@
  await prisma.userBlock.createMany({
    data: [
      { blockerId: blocked.id, blockedId: alice.id },
      { blockerId: alice.id, blockedId: blocked.id },
    ],
  });

  // Pending invite: a Conversation with `pending` as a member but lastReadAt
  // never set and no messages from them.
  const inviter = users.find((u) => u.id === "user_dev_admin")!;
  await prisma.conversation.create({
    data: {
      type: "DM",
      dmKey: [inviter.id, pending.id].sort().join(":"),
      createdById: inviter.id,
      members: {
        create: [
          { userId: inviter.id, role: "MEMBER" },
          { userId: pending.id, role: "MEMBER" },
        ],
      },
      messages: {
        create: [
          {
            senderId: inviter.id,
            text: "Hey, welcome — this is a pending-invite scenario for testing.",
          },
        ],
      },
    },
  });

  // Soft-deleted user
  const inactiveId = "user_dev_inactive";
  const inactiveNodeId = "person:inactive";
  await prisma.user.create({
    data: {
      id: inactiveId,
      email: "inactive@local.dev",
      name: "Inactive User",
      isActive: false,
    },
  });
  await prisma.node.create({
    data: {
      id: inactiveNodeId,
      type: "Person",
      name: "Inactive User",
      communityId: COMMUNITY_ID,
      metadata: { seeded: true, inactive: true },
    },
  });
  await prisma.person.create({
    data: {
      id: inactiveNodeId,
      userId: inactiveId,
      name: "Inactive User",
      hasOnboarded: false,
    },
  });

  // Very-long-name user
  const longId = "user_dev_long_name";
  const longNodeId = "person:long_name";
  const longName = "A".repeat(200);
  await prisma.user.create({
    data: {
      id: longId,
      email: "long-name@local.dev",
      name: longName,
      isActive: true,
    },
  });
  await prisma.node.create({
    data: {
      id: longNodeId,
      type: "Person",
      name: longName,
      communityId: COMMUNITY_ID,
      metadata: { seeded: true, edge: "long-name" },
    },
  });
  await prisma.person.create({
    data: { id: longNodeId, userId: longId, name: longName, hasOnboarded: true },
  });
  await prisma.userCommunity.create({
    data: { userId: longId, communityId: COMMUNITY_ID, role: "member" },
  });

  // Self-link (filter-bug bait)
  await prisma.link.create({
    data: {
      sourceId: alice.personNodeId,
      targetId: alice.personNodeId,
      relationship: "self",
      communityId: COMMUNITY_ID,
    },
  });

  // Orphan Person (claimable account scenario — Person with no User)
  const orphanNodeId = "person:orphan";
  await prisma.node.create({
    data: {
      id: orphanNodeId,
      type: "Person",
      name: "Orphan Person",
      communityId: COMMUNITY_ID,
      metadata: { seeded: true, edge: "orphan" },
    },
  });
  await prisma.person.create({
    data: {
      id: orphanNodeId,
      userId: null,
      name: "Orphan Person",
      hasOnboarded: false,
    },
  });
}

async function main() {
  console.log(`Seeding with SEED=${SEED}, USER_COUNT=${USER_COUNT}`);
  const t0 = Date.now();
  await wipeData();
  await createCommunity();
  const anchors = await createAnchorUsers();
  const background = await createBackgroundUsers(Math.max(0, USER_COUNT - anchors.length));
  const allUsers = [...anchors, ...background];
  await createSocialGraph(allUsers);
  await createMessages(allUsers);
  await createEdgeCases(allUsers);
  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
  console.log(`Seed complete in ${elapsed}s. ${allUsers.length} users.`);
  console.log("Anchor users (sign in via /dev/login):");
  for (const a of anchors) console.log(`  ${a.email}  →  ${a.name} (${a.anchorRole ?? "member"})`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
