/**
 * The starting Tools (lib/tools/templates/sources/*.tsx) as strings, for the
 * server to copy into a new Tool: Next's standalone output only carries files
 * something imports, and these are read as text, never imported as code.
 *
 * Output lands in lib/tools/templates/sources.generated.ts and IS COMMITTED;
 * `--check` fails when it has drifted (tests/tools-templates.test.ts runs the
 * same check).
 *
 *   pnpm --filter @visvine/web exec tsx scripts/build-tool-templates.ts
 *   pnpm --filter @visvine/web exec tsx scripts/build-tool-templates.ts --check
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const APP = join(__dirname, '..')
const SOURCES = join(APP, 'lib', 'tools', 'templates', 'sources')
const OUT = join(APP, 'lib', 'tools', 'templates', 'sources.generated.ts')

export function generateTemplateSources(): string {
  const files = readdirSync(SOURCES).filter((f) => f.endsWith('.tsx')).sort()
  const entries = files.map((file) => `  ${JSON.stringify(file.replace(/\.tsx$/, ''))}: ${JSON.stringify(readFileSync(join(SOURCES, file), 'utf8'))},`)
  return [
    '// Generated by scripts/build-tool-templates.ts from lib/tools/templates/sources — do not edit.',
    '',
    'export const TEMPLATE_SOURCES: Record<string, string> = {',
    ...entries,
    '}',
    '',
  ].join('\n')
}

if (require.main === module) {
  const next = generateTemplateSources()
  if (process.argv.includes('--check')) {
    const current = readFileSync(OUT, 'utf8')
    if (current !== next) {
      console.error('lib/tools/templates/sources.generated.ts is stale — run scripts/build-tool-templates.ts')
      process.exit(1)
    }
  } else {
    writeFileSync(OUT, next)
    console.log(`wrote ${OUT}`)
  }
}
