/**
 * Icon codegen — turns `assets/icons/*.svg` into React components.
 *
 * The SVGs at the repo root are the source of truth (see docs/icons.md and
 * assets/icons/ATTRIBUTION.md). They live outside apps/web because the native
 * apps consume the same directory, and apps/mobile is not in the pnpm workspace.
 *
 * Output lands in apps/web/features/shared/icons/generated/ and IS COMMITTED, so
 * `dev` and `typecheck` need no prebuild step. `pnpm icons:check` re-runs the
 * generator in memory and fails if the committed output has drifted from the
 * SVGs — that check rides `lint`, so a hand-edited generated file cannot land.
 *
 *   pnpm --filter @visvine/web icons:build     regenerate
 *   pnpm --filter @visvine/web icons:check     verify committed output matches
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SVG_DIR = path.resolve(HERE, '../../../assets/icons');
const OUT_DIR = path.resolve(HERE, '../features/shared/icons/generated');
// The name list also lands in lib/, which must stay React-free: server routes
// and zod schemas need to validate an icon name without pulling in 135
// components. Same split as lib/featureAccess.ts vs features/shared/lib/features.tsx.
const NAMES_FILE = path.resolve(HERE, '../lib/icons/names.ts');
// The few glyphs the shared UI package draws itself (a dialog's close, a
// select's chevron, a space's fallback mark). packages/ui cannot import the
// app, so it gets its own generated module from the same SVGs.
const UI_GLYPHS_FILE = path.resolve(HERE, '../../../packages/ui/src/icons/glyphs.generated.tsx');
const UI_GLYPHS = [
  'check', 'chevron-down', 'minus', 'space', 'x',
  // The resources viewer and its file tiles (packages/ui/src/resources).
  'chevron-left', 'chevron-right', 'download', 'external-link', 'ellipsis', 'maximize-2', 'minimize-2',
  'zoom-in', 'zoom-out', 'link-2', 'file', 'file-text', 'file-pdf', 'file-image', 'file-spreadsheet',
  'presentation', 'file-music', 'file-play', 'file-code-2', 'file-archive', 'copy', 'share', 'folder',
];

const BANNER = [
  '// AUTO-GENERATED by apps/web/scripts/build-icons.ts — do not edit.',
  '// Source of truth: assets/icons/*.svg. Run `pnpm icons:build` after changing one.',
  '',
].join('\n');

/** `circle-check` -> `CircleCheckIcon`. */
function componentName(iconName: string): string {
  const pascal = iconName
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  return `${pascal}Icon`;
}

/** SVG attribute names a child element may carry, and their JSX spellings. */
const CHILD_ATTRS: Record<string, string> = {
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-dasharray': 'strokeDasharray',
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
};

interface Glyph {
  /** Kebab file stem, and the key `<Icon name>` is looked up by. */
  name: string;
  /** The glyph's own stroke weight — lucide-derived art is 2, house art is 1.8. */
  strokeWidth: number;
  /** The child elements, as JSX, indented ready to inline. */
  body: string;
}

/**
 * Read one SVG and split it into (stroke weight, children).
 *
 * Deliberately strict rather than a general SVG parser: every file in
 * assets/icons/ is written by us to one shape, so anything that does not match
 * is a mistake worth failing on, not something to paper over. Attribute names
 * are converted to their JSX spellings on the way out.
 */
async function readGlyph(file: string): Promise<Glyph> {
  const name = path.basename(file, '.svg');
  const raw = await fs.readFile(file, 'utf8');

  const open = raw.match(/<svg\b([\s\S]*?)>/);
  if (!open) throw new Error(`${name}.svg: no <svg> element`);
  const attrs = open[1];

  if (!/viewBox="0 0 24 24"/.test(attrs)) {
    throw new Error(`${name}.svg: must declare viewBox="0 0 24 24"`);
  }
  const width = attrs.match(/stroke-width="([\d.]+)"/);
  if (!width) throw new Error(`${name}.svg: must declare a root stroke-width`);

  const inner = raw.slice(open.index! + open[0].length, raw.lastIndexOf('</svg>')).trim();
  if (!inner) throw new Error(`${name}.svg: empty`);

  // The root already carries fill/stroke/linecap/linejoin, so child elements
  // only ever contribute geometry. The few kebab attribute names that can show
  // up there are rewritten to their JSX spellings by name — never by a blanket
  // kebab->camel regex, which would also chew through path data (`a-2 2` and
  // friends) and silently corrupt the geometry.
  const body = inner
    .split('\n')
    .map((line) => {
      let out = line.trim();
      for (const [kebab, jsx] of Object.entries(CHILD_ATTRS)) {
        out = out.replaceAll(`${kebab}=`, `${jsx}=`);
      }
      return `      ${out}`;
    })
    .join('\n');

  return { name, strokeWidth: Number(width[1]), body };
}

function renderIconsModule(glyphs: Glyph[], iconBaseFrom = '@visvine/ui'): string {
  const components = glyphs.map((g) => {
    const comp = componentName(g.name);
    return [
      `export function ${comp}(props: IconProps) {`,
      `  return (`,
      `    <IconBase strokeWidth={${g.strokeWidth}} {...props}>`,
      g.body,
      `    </IconBase>`,
      `  );`,
      `}`,
    ].join('\n');
  });

  return [
    BANNER,
    `import { IconBase, type IconProps } from '${iconBaseFrom}';`,
    ``,
    components.join('\n\n'),
    ``,
  ].join('\n');
}

/**
 * The names list, with no React in it.
 *
 * Route handlers and zod schemas need to validate an icon name; `lib/` is
 * forbidden from importing React (eslint enforces it), and pulling 135
 * components into a request handler to check a string would be absurd anyway.
 * Same split the app already uses for `lib/featureAccess.ts` (pure) vs
 * `features/shared/lib/features.tsx` (the glyphs).
 */
function renderNamesModule(glyphs: Glyph[]): string {
  const names = glyphs.map((g) => `  '${g.name}',`).join('\n');
  return [
    BANNER,
    `/** Every icon we own, as a name. The union below is derived from this list. */`,
    `export const ICON_NAMES = [`,
    names,
    `] as const;`,
    ``,
    `export type IconName = (typeof ICON_NAMES)[number];`,
    ``,
    `const NAME_SET: ReadonlySet<string> = new Set(ICON_NAMES);`,
    ``,
    `/** Whether \`value\` names an icon we own — the guard for data coming in. */`,
    `export function isIconName(value: unknown): value is IconName {`,
    `  return typeof value === 'string' && NAME_SET.has(value);`,
    `}`,
    ``,
  ].join('\n');
}

function renderRegistryModule(glyphs: Glyph[]): string {
  const imports = glyphs.map((g) => `  ${componentName(g.name)},`).join('\n');
  const entries = glyphs.map((g) => `  '${g.name}': ${componentName(g.name)},`).join('\n');

  return [
    BANNER,
    `import type { ComponentType } from 'react';`,
    `import type { IconName } from '@/lib/icons/names';`,
    `import type { IconProps } from '@visvine/ui';`,
    `import {`,
    imports,
    `} from './icons';`,
    ``,
    `/**`,
    ` * Name -> component, for the surfaces that pick an icon by string: a Tool's`,
    ` * rail icon, a channel's icon, a space's feature config. Importing this pulls`,
    ` * every glyph, which is why it lives in its own module — code that names its`,
    ` * icons statically should import them from '@/features/shared/icons' instead`,
    ` * and get only what it uses.`,
    ` */`,
    `export const ICONS: Record<IconName, ComponentType<IconProps>> = {`,
    entries,
    `};`,
    ``,
  ].join('\n');
}

async function main() {
  const check = process.argv.includes('--check');

  const files = (await fs.readdir(SVG_DIR))
    .filter((f) => f.endsWith('.svg'))
    .sort()
    .map((f) => path.join(SVG_DIR, f));
  if (files.length === 0) throw new Error(`no SVGs found in ${SVG_DIR}`);

  const glyphs = await Promise.all(files.map(readGlyph));

  const outputs: Record<string, string> = {
    [path.join(OUT_DIR, 'icons.tsx')]: renderIconsModule(glyphs),
    [path.join(OUT_DIR, 'registry.ts')]: renderRegistryModule(glyphs),
    [NAMES_FILE]: renderNamesModule(glyphs),
    [UI_GLYPHS_FILE]: renderIconsModule(
      UI_GLYPHS.map((name) => {
        const glyph = glyphs.find((g) => g.name === name);
        if (!glyph) throw new Error(`packages/ui draws ${name}.svg, which assets/icons no longer has`);
        return glyph;
      }),
      './IconBase',
    ),
  };

  if (check) {
    const drifted: string[] = [];
    for (const [file, want] of Object.entries(outputs)) {
      const got = await fs.readFile(file, 'utf8').catch(() => null);
      if (got !== want) drifted.push(path.relative(path.resolve(HERE, '../../..'), file));
    }
    if (drifted.length) {
      console.error(
        `icons: generated output is stale (${drifted.join(', ')}). Run \`pnpm icons:build\`.`,
      );
      process.exit(1);
    }
    console.log(`icons: ${glyphs.length} glyphs, generated output up to date.`);
    return;
  }

  for (const [file, contents] of Object.entries(outputs)) {
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, contents);
  }
  console.log(`icons: wrote ${glyphs.length} glyphs to ${path.relative(process.cwd(), OUT_DIR)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
