// Major world cities for location autocomplete — "City, Country" format
// Sorted roughly by prominence so top matches feel LinkedIn-like

export const LOCATIONS: string[] = [
  // United States
  'New York, United States',
  'Los Angeles, United States',
  'San Francisco, United States',
  'Chicago, United States',
  'Houston, United States',
  'Boston, United States',
  'Seattle, United States',
  'Austin, United States',
  'Miami, United States',
  'Washington DC, United States',
  'Atlanta, United States',
  'Denver, United States',
  'San Diego, United States',
  'Dallas, United States',
  'Phoenix, United States',
  'Portland, United States',
  'Nashville, United States',
  'Minneapolis, United States',
  'Detroit, United States',
  'Las Vegas, United States',
  'Philadelphia, United States',
  'Salt Lake City, United States',
  'Raleigh, United States',
  'Charlotte, United States',
  'Pittsburgh, United States',
  'New Orleans, United States',
  'Kansas City, United States',
  'Columbus, United States',
  'Indianapolis, United States',
  'San Jose, United States',
  'Oakland, United States',
  'Sacramento, United States',
  'Palo Alto, United States',
  'Boulder, United States',
  // United Kingdom
  'London, United Kingdom',
  'Manchester, United Kingdom',
  'Birmingham, United Kingdom',
  'Edinburgh, United Kingdom',
  'Glasgow, United Kingdom',
  'Bristol, United Kingdom',
  'Leeds, United Kingdom',
  'Liverpool, United Kingdom',
  'Oxford, United Kingdom',
  'Cambridge, United Kingdom',
  'Brighton, United Kingdom',
  'Cardiff, United Kingdom',
  'Belfast, United Kingdom',
  // Canada
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Calgary, Canada',
  'Ottawa, Canada',
  'Edmonton, Canada',
  'Winnipeg, Canada',
  'Halifax, Canada',
  // Australia
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Perth, Australia',
  'Adelaide, Australia',
  'Canberra, Australia',
  // Europe
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Frankfurt, Germany',
  'Cologne, Germany',
  'Stuttgart, Germany',
  'Paris, France',
  'Lyon, France',
  'Marseille, France',
  'Bordeaux, France',
  'Toulouse, France',
  'Amsterdam, Netherlands',
  'Rotterdam, Netherlands',
  'The Hague, Netherlands',
  'Eindhoven, Netherlands',
  'Stockholm, Sweden',
  'Gothenburg, Sweden',
  'Malmö, Sweden',
  'Oslo, Norway',
  'Bergen, Norway',
  'Copenhagen, Denmark',
  'Aarhus, Denmark',
  'Helsinki, Finland',
  'Espoo, Finland',
  'Zürich, Switzerland',
  'Geneva, Switzerland',
  'Basel, Switzerland',
  'Vienna, Austria',
  'Graz, Austria',
  'Brussels, Belgium',
  'Antwerp, Belgium',
  'Ghent, Belgium',
  'Dublin, Ireland',
  'Cork, Ireland',
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Valencia, Spain',
  'Seville, Spain',
  'Bilbao, Spain',
  'Rome, Italy',
  'Milan, Italy',
  'Turin, Italy',
  'Florence, Italy',
  'Bologna, Italy',
  'Naples, Italy',
  'Warsaw, Poland',
  'Krakow, Poland',
  'Prague, Czech Republic',
  'Budapest, Hungary',
  'Bucharest, Romania',
  'Kyiv, Ukraine',
  'Athens, Greece',
  'Thessaloniki, Greece',
  'Tallinn, Estonia',
  'Riga, Latvia',
  'Vilnius, Lithuania',
  'Ljubljana, Slovenia',
  'Zagreb, Croatia',
  'Belgrade, Serbia',
  // Asia
  'Tokyo, Japan',
  'Osaka, Japan',
  'Kyoto, Japan',
  'Fukuoka, Japan',
  'Yokohama, Japan',
  'Nagoya, Japan',
  'Seoul, South Korea',
  'Busan, South Korea',
  'Beijing, China',
  'Shanghai, China',
  'Shenzhen, China',
  'Guangzhou, China',
  'Hangzhou, China',
  'Chengdu, China',
  'Chongqing, China',
  'Hong Kong',
  'Taipei, Taiwan',
  'Singapore',
  'Kuala Lumpur, Malaysia',
  'Bangkok, Thailand',
  'Ho Chi Minh City, Vietnam',
  'Hanoi, Vietnam',
  'Jakarta, Indonesia',
  'Bali, Indonesia',
  'Manila, Philippines',
  'Cebu, Philippines',
  'Mumbai, India',
  'Delhi, India',
  'Bangalore, India',
  'Hyderabad, India',
  'Chennai, India',
  'Pune, India',
  'Kolkata, India',
  'Ahmedabad, India',
  'Islamabad, Pakistan',
  'Karachi, Pakistan',
  'Lahore, Pakistan',
  'Dhaka, Bangladesh',
  'Colombo, Sri Lanka',
  'Kathmandu, Nepal',
  'Dubai, UAE',
  'Abu Dhabi, UAE',
  'Riyadh, Saudi Arabia',
  'Jeddah, Saudi Arabia',
  'Doha, Qatar',
  'Kuwait City, Kuwait',
  'Muscat, Oman',
  'Manama, Bahrain',
  'Amman, Jordan',
  'Beirut, Lebanon',
  'Tel Aviv, Israel',
  'Jerusalem, Israel',
  'Istanbul, Turkey',
  'Ankara, Turkey',
  'Izmir, Turkey',
  // Africa
  'Lagos, Nigeria',
  'Abuja, Nigeria',
  'Cairo, Egypt',
  'Alexandria, Egypt',
  'Nairobi, Kenya',
  'Johannesburg, South Africa',
  'Cape Town, South Africa',
  'Durban, South Africa',
  'Accra, Ghana',
  'Addis Ababa, Ethiopia',
  'Dar es Salaam, Tanzania',
  'Casablanca, Morocco',
  'Tunis, Tunisia',
  'Dakar, Senegal',
  'Kigali, Rwanda',
  // Latin America
  'São Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Brasília, Brazil',
  'Belo Horizonte, Brazil',
  'Curitiba, Brazil',
  'Porto Alegre, Brazil',
  'Mexico City, Mexico',
  'Guadalajara, Mexico',
  'Monterrey, Mexico',
  'Buenos Aires, Argentina',
  'Córdoba, Argentina',
  'Bogotá, Colombia',
  'Medellín, Colombia',
  'Santiago, Chile',
  'Lima, Peru',
  'Caracas, Venezuela',
  'Quito, Ecuador',
  'La Paz, Bolivia',
  'Montevideo, Uruguay',
  'Asunción, Paraguay',
  'Panama City, Panama',
  'San José, Costa Rica',
  'Havana, Cuba',
  // Remote / Global
  'Remote',
  'Global',
  'Worldwide',
];

export function searchLocations(query: string): string[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  const exact: string[] = [];
  const startsWith: string[] = [];
  const contains: string[] = [];

  for (const loc of LOCATIONS) {
    const l = loc.toLowerCase();
    if (l === q) { exact.push(loc); continue; }
    if (l.startsWith(q) || l.split(', ')[0].startsWith(q)) { startsWith.push(loc); continue; }
    if (l.includes(q)) contains.push(loc);
  }

  return [...exact, ...startsWith, ...contains].slice(0, 8);
}
