// AUTO-GENERATED by apps/web/scripts/build-icons.ts — do not edit.
// Source of truth: assets/icons/*.svg. Run `pnpm icons:build` after changing one.

import { IconBase, type IconProps } from './IconBase';

export function CheckIcon(props: IconProps) {
  return (
    <IconBase strokeWidth={2} {...props}>
      <path d="M20 6 9 17l-5-5" />
    </IconBase>
  );
}

export function ChevronDownIcon(props: IconProps) {
  return (
    <IconBase strokeWidth={2} {...props}>
      <path d="m6 9 6 6 6-6" />
    </IconBase>
  );
}

export function MinusIcon(props: IconProps) {
  return (
    <IconBase strokeWidth={2} {...props}>
      <path d="M5 12h14" />
    </IconBase>
  );
}

export function SpaceIcon(props: IconProps) {
  return (
    <IconBase strokeWidth={2} {...props}>
      <path d="M7.5 5h9M7.5 19h9M5 7.5v9M19 7.5v9M2.5 5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0-5 0M16.5 5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0-5 0M2.5 19a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0-5 0M16.5 19a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0-5 0" />
    </IconBase>
  );
}

export function XIcon(props: IconProps) {
  return (
    <IconBase strokeWidth={2} {...props}>
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </IconBase>
  );
}
