// Context domain: nodes, links, node/link type configs, aliases, and their
// canonical defaults + resolution helpers.

// Node type is now dynamic per community
export type NodeType = string;

// Shape options for node rendering
type NodeShape = 'rectangle' | 'hexagon' | 'circle' | 'square';

// Configuration for a node type
export interface NodeTypeConfig {
  name: string; // e.g., "Person", "Organization"
  color: string; // Hex color e.g., "#2563eb"
  shape: NodeShape; // Shape to render
  icon?: string; // Optional emoji or icon
  /**
   * `note` marks a type a member invented from the draft surface. Things made
   * under it are plain context notes — Context and Raw, a coloured type chip,
   * no profile page — because nothing syncs a graph node for a note. Surfaces
   * that list types in order to FILTER NODES skip these; surfaces that label or
   * colour a type show them like any other. Absent on the built-ins, which a
   * tool claims and turns into real directory entities.
   */
  scope?: 'note';
}

export interface NBNode {
  id: string;
  type: NodeType;
  name: string;
  subtitle?: string | null;
  location?: string | null;
  url?: string | null;
  tags?: string[];
  image_url?: string | null;
  metadata?: Record<string, unknown>;
  alias?: string | null;
  community_id?: string | null;
  createdAt?: string;
  // Force context will add these during simulation
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
  fx?: number | null;
  fy?: number | null;
  // Anti-bouncing system
  lastFix?: Record<string, number>;
}

type RelationshipType =
  | 'works_at'
  | 'founded'
  | 'invested_in'
  | 'attended'
  | 'hosting'
  | 'member_of'
  | 'sponsors'
  | 'partner_with'
  | 'related'
  | 'knows'
  | 'mentors'
  | 'introduced';

// Where a Link came from. `manual` = created in the UI by an admin; the rest are
// system-generated by an action (and carry `originRef` for symmetric auto-undo);
// `context` = derived from an entity mention in a context note (originRef = the
// note path); `structure` = the containment edge from a community to its sections,
// channels, notes and files (originRef = the child node id, so moving or deleting
// the child undoes exactly its own edge); `import` = bulk-loaded curated data.
export type LinkOrigin =
  | 'manual'
  | 'event_attendance'
  | 'event_hosting'
  | 'intro'
  | 'context'
  | 'structure'
  | 'import';

export interface NBLink {
  source: string | NBNode; // node id or node object
  target: string | NBNode; // node id or node object
  relationship: RelationshipType | (string & {});
  since?: string; // ISO date
  metadata?: Record<string, unknown>;
  community_id?: string;
  origin?: LinkOrigin;     // provenance; surfaced read-only by the context serializer
  id?: number;             // DB id, exposed read-only so the client can reconcile optimistic edits
}

export interface ContextData {
  nodes: NBNode[];
  links: NBLink[];
}

// A named alias with a display color, scoped to a specific node type within a
// community. Created on the Types page — and for the Person type they are also
// the community's PERMISSION model: a member holds any number of their Person
// aliases (UserAlias rows), `owner` says holders manage the community, and a
// BrainGrant with subjectType 'alias' targets one by name. So "Engineering" is
// one thing: a chip in the directory and a set of permissions.
export interface CommunityAlias {
  name: string;    // e.g. "Founder"
  color: string;   // Hex color e.g. "#16a34a"
  nodeType: string; // e.g. "Person", "Space"
  // Person aliases only
  /** Holders manage the community (lib/auth.ts#isAdmin). */
  owner?: boolean;
  /** The built-in Owner alias — like the system link types, it can't be removed
   *  or recoloured, and it always owns the community. */
  system?: boolean;
}

/** The built-in Person alias every community has. Gold, fixed, always owns. */
export const OWNER_ALIAS_NAME = 'Owner';
export const OWNER_ALIAS: CommunityAlias = {
  name: OWNER_ALIAS_NAME,
  color: '#b4881b',
  nodeType: 'Person',
  owner: true,
  system: true,
};

/**
 * A community's Person aliases — its permission vocabulary. The built-in Owner
 * alias is grafted in first whether or not it is stored, so a community can
 * never present itself as having nothing that owns it.
 */
export function personAliases(aliases: CommunityAlias[] | undefined): CommunityAlias[] {
  const stored = aliasesForType(aliases, 'Person').filter((a) => a.name !== OWNER_ALIAS_NAME);
  const owner = aliasesForType(aliases, 'Person').find((a) => a.name === OWNER_ALIAS_NAME);
  return [{ ...OWNER_ALIAS, ...owner, owner: true, system: true }, ...stored];
}

// A community-configurable relationship (edge) type — mirrors NodeTypeConfig.
// Managed in the console alongside node types; the stored Link.relationship is the
// slug of `name` (see lib/notes/context/relationships.ts normalizeRelationship).
export interface LinkTypeConfig {
  name: string;       // human label, e.g. "Works at"
  color: string;      // hex, tints the edge stroke
  directed: boolean;  // arrowhead vs plain line
  system?: boolean;   // attended | hosting | introduced — auto-flows depend on these (recolor-only, can't delete)
}

// Canonical node types and their default colours/shapes. A community can override
// these via `nodeTypes`, but every type listed here resolves to a non-grey colour
// even before a community config has loaded. This is what prevents the
// "everything is grey on first paint" race condition.
export const DEFAULT_NODE_TYPES: NodeTypeConfig[] = [
  { name: 'Person',    color: '#2563eb', shape: 'rectangle' },
  // A group, organisation or community recorded in the directory — the type
  // was called Community until the 2026-08 vocabulary rename (and Group /
  // Organization before that). There is one type because there is one thing:
  // every such card points at a real Community tenant row via
  // `metadata.communityRef`, unclaimed until somebody runs it (lib/communities/
  // stub.ts). isOwnCommunityNode below tells the space you're IN apart from
  // the organisations recorded inside it.
  { name: 'Space',     color: '#78d870', shape: 'square'    },
  { name: 'Event',     color: '#ef4444', shape: 'rectangle' },
  { name: 'Resource',  color: '#f59e0b', shape: 'rectangle' },
  // Structural types — the container kinds. Colours match the Create panel's
  // tiles so a thing looks the same wherever you meet it. Notes and uploaded
  // files are deliberately absent: they are content in a brain, not nodes in
  // the graph, so nothing syncs a `note:`/`file:` node for them. Section was
  // called Space before the rename freed that name for the org type; stored
  // rows are migrated by scripts/rename-community-to-space.ts.
  { name: 'Section',   color: '#0ea5e9', shape: 'square'    },
  { name: 'Channel',   color: '#e0685f', shape: 'rectangle' },
  // A connector is a community's gateway to an external API or database, kept
  // as a note under connectors/. Rectangle like the other document types — the
  // indigo tint and the plug glyph are what set it apart.
  { name: 'Connector', color: '#6366f1', shape: 'rectangle' },
  // An index note IS a folder (lib/notes/shared/indexNote.ts). Listed here so
  // the Type chip on one resolves to a real configured type in every community,
  // not just the seeded ones — nothing writes an `index:` node. Fuchsia, not the
  // Resource amber it used to share: two different things painting the same
  // colour defeats the point of colouring anything by type, and fuchsia is the
  // one hue the seeded vocabulary (prisma/seed.ts NODE_TYPES) leaves free.
  { name: 'Index',     color: '#c026d3', shape: 'square'    },
];

// Aliases are entirely community-configured — there is no built-in list for any
// type, Connector included. A connector's `alias: http` frontmatter picks its
// executor on its own (lib/connectors/config.ts never reads this registry), so
// the alias rows here are pure display vocabulary and an admin owns all of them:
// add, recolour, remove.

/**
 * Node types that describe where things live rather than who/what they are.
 * These are hidden by default in the context view and excluded from the
 * directory grid; the type filter turns them back on. Lowercase — compare
 * against a node's stored `type`, which is canonicalised lowercase on write.
 *
 * `space` (the org type, formerly Community) is deliberately NOT here. It
 * carries the organisations that used to be the Group type, which are
 * directory records people expect to see; the cost is that a space's own root
 * node shows up in its grid too, which reads as a "this space" card and links
 * to /communities/<id>.
 *
 * `note`, `file` and `index` are still listed so any row left over from when
 * those types existed stays filtered out of the grid and the graph rather than
 * surfacing as a grey unknown. Nothing writes them any more.
 */
export const STRUCTURAL_NODE_TYPES: readonly string[] = [
  'section',
  'channel',
  'note',
  'file',
  'index',
  'connector',
];

/**
 * The graph node standing for a community itself.
 *
 * Community ids are usually already `community:`-prefixed (`community:blackbird`
 * from the slugified name), so prefixing blindly would produce
 * `community:community:blackbird` — and, worse, a note path with a colon in it,
 * because entityNotePath slugs everything after the FIRST colon. Normalising
 * here keeps the id and the note path (`communities/blackbird.md`) clean whether
 * or not the caller's id carries the prefix.
 *
 * Lives here rather than in lib/notes/context/entityNodes.ts (which re-exports it)
 * because client components need it and that module imports prisma.
 */
export function communityNodeId(communityId: string): string {
  return `community:${communityId.replace(/^community:/, '')}`;
}

/**
 * Does this `space`-typed node stand for the space it lives in, or for a
 * group/organisation recorded inside it?
 *
 * Both wear `type: 'space'` and (for legacy rows) a `community:<slug>` id —
 * ids are opaque and keep whatever prefix they were minted with across the
 * type's renames (Group → Community → Space). The space's own root node is
 * the one whose id derives from its own `communityId`; anything else is a
 * card pointing at some other space (see `metadata.communityRef`).
 *
 * This is the discriminator every consumer needs: the root node redirects to
 * /communities/<id>, a record renders its profile in place, and only records
 * resolve to a cross-community organisation Identity.
 */
export function isOwnCommunityNode(node: { id: string; communityId?: string | null }): boolean {
  if (!node.communityId) return false;
  return communityNodeId(node.communityId) === node.id;
}

/** Whether a node type is structural (see {@link STRUCTURAL_NODE_TYPES}). */
export function isStructuralNodeType(type: string | null | undefined): boolean {
  if (!type) return false;
  const normalized = type.toLowerCase();
  return STRUCTURAL_NODE_TYPES.includes(TYPE_SYNONYMS[normalized] ?? normalized);
}

// (NODE_COLORS removed — all type→colour resolution goes through the
// case-insensitive getNodeTypeConfig/getTypeColor canonical helpers.)

/**
 * Get node type configuration for a specific type within a community
 */
// Legacy/synonym type names that map onto a canonical base type. Keeps nodes
// still stored (or cached) under a retired spelling rendering identically to
// the current one, so un-migrated or stale-cache data never falls through to
// the grey "unknown type" placeholder. Organisations have been through three
// renames now — Organization → Group → Community → Space — so every retired
// spelling lands on `space`.
//
// There is deliberately NO synonym for the old structural 'space' rows
// (sections): 'space' now IS the canonical org type, so those rows can only be
// handled by data migration (scripts/rename-community-to-space.ts) — which is
// why that migration is mandatory, not optional.
const TYPE_SYNONYMS: Record<string, string> = {
  organization: 'space',
  organisation: 'space',
  org: 'space',
  group: 'space',
  groups: 'space',
  company: 'space',
  companies: 'space',
  community: 'space',
  communities: 'space',
};

/**
 * The canonical spelling of a type string: lowercased, with retired names
 * (`org`, `group`, `company`, …) folded onto the type they became. Filtering by
 * raw string instead of this is how a caller ends up matching nothing against
 * legacy rows that still carry the old spelling.
 */
export function canonicalNodeType(type: string | null | undefined): string {
  const normalized = (type ?? '').trim().toLowerCase();
  return TYPE_SYNONYMS[normalized] ?? normalized;
}

/**
 * Every spelling that means the same type as `type` — the canonical one plus
 * any retired synonym for it. For querying stored `node.type` values, which are
 * whatever spelling was current when the row was written.
 */
export function nodeTypeSpellings(type: string | null | undefined): string[] {
  const canonical = canonicalNodeType(type);
  if (!canonical) return [];
  const synonyms = Object.entries(TYPE_SYNONYMS)
    .filter(([, to]) => to === canonical)
    .map(([from]) => from);
  return [...new Set([canonical, ...synonyms])];
}

/**
 * Resolve a type string to a REAL type — one the community configured in its
 * console, or one of the built-in defaults — or null when it is neither.
 *
 * The null arm is the point. `getNodeTypeConfig` below always answers with
 * something so a node is never grey-on-unknown, which is right for nodes: they
 * cannot exist without a type. Free text is a different story. A note's
 * frontmatter can say `type: Note`, `type: Dashboard`, anything at all, and a
 * surface that renders that as a chip is inventing a type the community never
 * created — it looks configured, it isn't, and it can never match a filter,
 * an alias or a colour. Callers showing a type to a user resolve it here first
 * and show nothing when it comes back null.
 */
export function findNodeTypeConfig(
  type: string | null | undefined,
  communityNodeTypes?: NodeTypeConfig[]
): NodeTypeConfig | null {
  if (!type) return null;
  const normalized = type.trim().toLowerCase();
  if (!normalized) return null;
  const canonical = TYPE_SYNONYMS[normalized] ?? normalized;
  const matches = (t: NodeTypeConfig) => {
    const n = t.name.toLowerCase();
    return n === normalized || n === canonical;
  };
  // The community's own types win: the console is where a type is created, and
  // its name and colour are the ones the rest of the app filters and paints by.
  return communityNodeTypes?.find(matches) ?? DEFAULT_NODE_TYPES.find(matches) ?? null;
}

export function getNodeTypeConfig(
  type: string,
  communityNodeTypes?: NodeTypeConfig[]
): NodeTypeConfig {
  const config = findNodeTypeConfig(type, communityNodeTypes);
  if (config) return config;

  // Truly unknown type — capitalize for display
  return { name: type.charAt(0).toUpperCase() + type.slice(1), color: '#6b7280', shape: 'rectangle' };
}

/**
 * The avatar-fallback glyph a node type should draw when it has no image. People
 * get the person silhouette; communities and the other containers the cluster;
 * events a calendar; resources a document. Any other type returns null and the
 * caller falls back to name initials. A clean SVG-glyph system, not emoji.
 */
export function getNodeGlyph(
  type: string | null | undefined
): 'person' | 'group' | 'event' | 'resource' | 'connector' | null {
  if (!type) return null;
  const normalized = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[normalized] ?? normalized;
  if (canonical === 'person' || canonical === 'people') return 'person';
  if (canonical === 'event' || canonical === 'events') return 'event';
  if (canonical === 'resource' || canonical === 'resources') return 'resource';
  // Containers reuse the existing glyphs rather than inventing new ones: a
  // space/section/channel reads as a cluster. The glyph key is still called
  // 'group' — it is the shape's name, not a node type.
  if (canonical === 'space' || canonical === 'section' || canonical === 'channel') return 'group';
  if (canonical === 'connector') return 'connector';
  return null;
}

/**
 * Community aliases scoped to a base node type. Matching is case-insensitive
 * because stored node `type` values aren't consistently cased — the canonical
 * way to relate an alias to a node type across the app.
 */
export function aliasesForType(
  aliases: CommunityAlias[] | undefined,
  type: string | null | undefined,
): CommunityAlias[] {
  if (!type) return [];
  const t = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[t] ?? t;
  return (aliases ?? []).filter((a) => {
    const n = a.nodeType.toLowerCase();
    return n === t || n === canonical;
  });
}

/**
 * Find the alias with a given name for a node type (case-insensitive on type).
 * Returns undefined when name is empty or no alias matches.
 */
export function findAlias(
  aliases: CommunityAlias[] | undefined,
  name: string | null | undefined,
  type: string,
): CommunityAlias | undefined {
  if (!name) return undefined;
  return aliasesForType(aliases, type).find((a) => a.name === name);
}

/**
 * The label for a node's type chip. `Node.alias` only counts as a community
 * alias when the community actually configures one by that name for the node's
 * type — events reuse the same column for their public /e/<slug> slug, which
 * must never surface as a type label. Anything unrecognised falls back to the
 * canonical type name ("Event", "Space", …).
 */
export function nodeTypeLabel(
  type: string | null | undefined,
  alias: string | null | undefined,
  aliases: CommunityAlias[] | undefined,
  nodeTypes?: NodeTypeConfig[],
): string {
  const t = type ?? '';
  if (!t) return alias ?? '';
  return findAlias(aliases, alias, t)?.name ?? getNodeTypeConfig(t, nodeTypes).name;
}

// Canonical relationship (edge) types and their default colours. A community
// overrides these via `linkTypes`; this is the seeded fallback. The `system`
// types back the auto-link flows (RSVP/event/intro/context-note mentions) and
// must always resolve, even before a community config loads. Keep in sync with
// the `Community.linkTypes` default in schema.prisma.
export const DEFAULT_LINK_TYPES: LinkTypeConfig[] = [
  { name: 'Related',     color: '#94a3b8', directed: false },
  { name: 'Knows',       color: '#2563eb', directed: false },
  { name: 'Works at',    color: '#9333ea', directed: true  },
  { name: 'Founded',     color: '#16a34a', directed: true  },
  { name: 'Invested in', color: '#f59e0b', directed: true  },
  { name: 'Member of',   color: '#0ea5e9', directed: true  },
  { name: 'Partner',     color: '#ec4899', directed: false },
  { name: 'Mentors',     color: '#14b8a6', directed: true  },
  { name: 'Attended',    color: '#ef4444', directed: true,  system: true },
  { name: 'Hosting',     color: '#ef4444', directed: true,  system: true },
  { name: 'Introduced',  color: '#06b6d4', directed: false, system: true },
  { name: 'Mentioned',   color: '#8b5cf6', directed: false, system: true },
  { name: 'Contains',    color: '#64748b', directed: true,  system: true },
];

/**
 * All link types available for a community (its config, or the default set).
 */
export function getLinkTypes(communityLinkTypes?: LinkTypeConfig[]): LinkTypeConfig[] {
  return communityLinkTypes && communityLinkTypes.length > 0 ? communityLinkTypes : DEFAULT_LINK_TYPES;
}
