// Context domain: nodes, links, node/link type configs, aliases, and their
// canonical defaults + resolution helpers.

// Node type is now dynamic per community
export type NodeType = string;

// Shape options for node rendering
type NodeShape = 'rectangle' | 'hexagon' | 'circle' | 'square';

// Configuration for a node type
export interface NodeTypeConfig {
  name: string; // e.g., "Person", "Organization"
  color: string; // Hex color e.g., "#2563eb"
  shape: NodeShape; // Shape to render
  icon?: string; // Optional emoji or icon
}

export interface NBNode {
  id: string;
  type: NodeType;
  name: string;
  subtitle?: string | null;
  location?: string | null;
  url?: string | null;
  tags?: string[];
  image_url?: string | null;
  metadata?: Record<string, unknown>;
  alias?: string | null;
  community_id?: string | null;
  createdAt?: string;
  // Force context will add these during simulation
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
  fx?: number | null;
  fy?: number | null;
  // Anti-bouncing system
  lastFix?: Record<string, number>;
}

type RelationshipType =
  | 'works_at'
  | 'founded'
  | 'invested_in'
  | 'attended'
  | 'hosting'
  | 'member_of'
  | 'sponsors'
  | 'partner_with'
  | 'related'
  | 'knows'
  | 'mentors'
  | 'introduced';

// Where a Link came from. `manual` = created in the UI by an admin; the rest are
// system-generated by an action (and carry `originRef` for symmetric auto-undo);
// `context` = derived from an entity mention in a context note (originRef = the
// note path); `structure` = the containment edge from a community to its spaces,
// channels, notes and files (originRef = the child node id, so moving or deleting
// the child undoes exactly its own edge); `import` = bulk-loaded curated data.
export type LinkOrigin =
  | 'manual'
  | 'event_attendance'
  | 'event_hosting'
  | 'intro'
  | 'context'
  | 'structure'
  | 'import';

export interface NBLink {
  source: string | NBNode; // node id or node object
  target: string | NBNode; // node id or node object
  relationship: RelationshipType | (string & {});
  since?: string; // ISO date
  metadata?: Record<string, unknown>;
  community_id?: string;
  origin?: LinkOrigin;     // provenance; surfaced read-only by the context serializer
  id?: number;             // DB id, exposed read-only so the client can reconcile optimistic edits
}

export interface ContextData {
  nodes: NBNode[];
  links: NBLink[];
}

// A named alias with a display color, scoped to a specific node type within a community
export interface CommunityAlias {
  name: string;    // e.g. "Founder"
  color: string;   // Hex color e.g. "#16a34a"
  nodeType: string; // e.g. "Person", "Organization"
}

// A community-configurable relationship (edge) type — mirrors NodeTypeConfig.
// Managed in the console alongside node types; the stored Link.relationship is the
// slug of `name` (see lib/context/relationships.ts normalizeRelationship).
export interface LinkTypeConfig {
  name: string;       // human label, e.g. "Works at"
  color: string;      // hex, tints the edge stroke
  directed: boolean;  // arrowhead vs plain line
  system?: boolean;   // attended | hosting | introduced — auto-flows depend on these (recolor-only, can't delete)
}

// Canonical node types and their default colours/shapes. A community can override
// these via `nodeTypes`, but every type listed here resolves to a non-grey colour
// even before a community config has loaded. This is what prevents the
// "everything is grey on first paint" race condition.
export const DEFAULT_NODE_TYPES: NodeTypeConfig[] = [
  { name: 'Person',    color: '#2563eb', shape: 'rectangle' },
  // An organisation IS a community: the company, group or org you record in the
  // directory is the same kind of thing as the workspace you could run for it,
  // so there is one type for both. A record living in someone else's graph is
  // just a community nobody has provisioned yet — see isOwnCommunityNode in
  // lib/context/entityNodes.ts for how the two are told apart.
  { name: 'Community', color: '#78d870', shape: 'square'    },
  { name: 'Event',     color: '#ef4444', shape: 'rectangle' },
  { name: 'Resource',  color: '#f59e0b', shape: 'rectangle' },
  // Structural types — the container and document kinds. Colours match the
  // Create panel's tiles so a thing looks the same wherever you meet it.
  { name: 'Space',     color: '#0ea5e9', shape: 'square'    },
  { name: 'Channel',   color: '#e0685f', shape: 'rectangle' },
  { name: 'Note',      color: '#ec4899', shape: 'rectangle' },
  { name: 'File',      color: '#14b8a6', shape: 'rectangle' },
  // A connector is a community's gateway to an external API or database, kept
  // as a note under connectors/. Rectangle like the other document types — the
  // indigo tint and the plug glyph are what set it apart.
  { name: 'Connector', color: '#6366f1', shape: 'rectangle' },
];

// Aliases are entirely community-configured — there is no built-in list for any
// type, Connector included. A connector's `alias: http` frontmatter picks its
// executor on its own (lib/connectors/config.ts never reads this registry), so
// the alias rows here are pure display vocabulary and an admin owns all of them:
// add, recolour, remove.

/**
 * Node types that describe where things live rather than who/what they are.
 * Everything creatable now has a node, which is what makes the context graph
 * complete — but a community with 400 notes would drown its 40 people. So these
 * are hidden by default in the context view and excluded from the directory
 * grid; the type filter turns them back on. Lowercase — compare against a
 * node's stored `type`, which is canonicalised lowercase on write.
 *
 * `community` is deliberately NOT here. It carries the organisations that used
 * to be the Group type, which are directory records people expect to see; the
 * cost is that a community's own root node shows up in its grid too, which
 * reads as a "this community" card and links to /communities/<id>.
 */
export const STRUCTURAL_NODE_TYPES: readonly string[] = [
  'space',
  'channel',
  'note',
  'file',
  'connector',
];

/**
 * The graph node standing for a community itself.
 *
 * Community ids are usually already `community:`-prefixed (`community:blackbird`
 * from the slugified name), so prefixing blindly would produce
 * `community:community:blackbird` — and, worse, a note path with a colon in it,
 * because entityNotePath slugs everything after the FIRST colon. Normalising
 * here keeps the id and the note path (`communities/blackbird.md`) clean whether
 * or not the caller's id carries the prefix.
 *
 * Lives here rather than in lib/context/entityNodes.ts (which re-exports it)
 * because client components need it and that module imports prisma.
 */
export function communityNodeId(communityId: string): string {
  return `community:${communityId.replace(/^community:/, '')}`;
}

/**
 * Does this `community`-typed node stand for the community it lives in, or for
 * an organisation recorded inside it?
 *
 * Both wear `type: 'community'` and a `community:<slug>` id since organisations
 * stopped being their own "Group" type — an org IS a community, just one nobody
 * has provisioned a workspace for. The community's own root node is the one
 * whose id derives from its own `communityId`; anything else is a record.
 *
 * This is the discriminator every consumer needs: the root node redirects to
 * /communities/<id>, a record renders its profile in place, and only records
 * resolve to a cross-community organisation Identity.
 */
export function isOwnCommunityNode(node: { id: string; communityId?: string | null }): boolean {
  if (!node.communityId) return false;
  return communityNodeId(node.communityId) === node.id;
}

/** Whether a node type is structural (see {@link STRUCTURAL_NODE_TYPES}). */
export function isStructuralNodeType(type: string | null | undefined): boolean {
  if (!type) return false;
  const normalized = type.toLowerCase();
  return STRUCTURAL_NODE_TYPES.includes(TYPE_SYNONYMS[normalized] ?? normalized);
}

// (NODE_COLORS removed — all type→colour resolution goes through the
// case-insensitive getNodeTypeConfig/getTypeColor canonical helpers.)

/**
 * Get node type configuration for a specific type within a community
 */
// Legacy/synonym type names that map onto a canonical base type. Keeps nodes
// still stored (or cached) under a retired spelling rendering identically to
// the current one, so un-migrated or stale-cache data never falls through to
// the grey "unknown type" placeholder. Organisations have been through two
// renames now — Organization → Group → Community — so all five spellings land
// on `community`.
const TYPE_SYNONYMS: Record<string, string> = {
  organization: 'community',
  organisation: 'community',
  org: 'community',
  group: 'community',
  groups: 'community',
  company: 'community',
  companies: 'community',
  communities: 'community',
  // An uploaded file is stored as a ContextSource; "File" is what the Create
  // panel and the graph call it, so both names resolve to the same config.
  source: 'file',
};

export function getNodeTypeConfig(
  type: string,
  communityNodeTypes?: NodeTypeConfig[]
): NodeTypeConfig {
  const normalized = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[normalized] ?? normalized;

  // Check community-specific overrides first (case-insensitive), matching either
  // the raw type or its canonical synonym.
  if (communityNodeTypes) {
    const config = communityNodeTypes.find(t => {
      const n = t.name.toLowerCase();
      return n === normalized || n === canonical;
    });
    if (config) return config;
  }

  // Always fall back to DEFAULT_NODE_TYPES before giving up
  const defaultConfig = DEFAULT_NODE_TYPES.find(t => {
    const n = t.name.toLowerCase();
    return n === normalized || n === canonical;
  });
  if (defaultConfig) return defaultConfig;

  // Truly unknown type — capitalize for display
  return { name: type.charAt(0).toUpperCase() + type.slice(1), color: '#6b7280', shape: 'rectangle' };
}

/**
 * The avatar-fallback glyph a node type should draw when it has no image. People
 * get the person silhouette; communities and the other containers the cluster;
 * events a calendar; resources a document. Any other type returns null and the
 * caller falls back to name initials. A clean SVG-glyph system, not emoji.
 */
export function getNodeGlyph(
  type: string | null | undefined
): 'person' | 'group' | 'event' | 'resource' | 'connector' | null {
  if (!type) return null;
  const normalized = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[normalized] ?? normalized;
  if (canonical === 'person' || canonical === 'people') return 'person';
  if (canonical === 'event' || canonical === 'events') return 'event';
  if (canonical === 'resource' || canonical === 'resources') return 'resource';
  // Containers reuse the existing glyphs rather than inventing new ones: a
  // community/space/channel reads as a cluster, a document as a page. The glyph
  // key is still called 'group' — it is the shape's name, not a node type.
  if (canonical === 'community' || canonical === 'space' || canonical === 'channel') return 'group';
  if (canonical === 'note' || canonical === 'file') return 'resource';
  if (canonical === 'connector') return 'connector';
  return null;
}

/**
 * Community aliases scoped to a base node type. Matching is case-insensitive
 * because stored node `type` values aren't consistently cased — the canonical
 * way to relate an alias to a node type across the app.
 */
export function aliasesForType(
  aliases: CommunityAlias[] | undefined,
  type: string | null | undefined,
): CommunityAlias[] {
  if (!type) return [];
  const t = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[t] ?? t;
  return (aliases ?? []).filter((a) => {
    const n = a.nodeType.toLowerCase();
    return n === t || n === canonical;
  });
}

/**
 * Find the alias with a given name for a node type (case-insensitive on type).
 * Returns undefined when name is empty or no alias matches.
 */
export function findAlias(
  aliases: CommunityAlias[] | undefined,
  name: string | null | undefined,
  type: string,
): CommunityAlias | undefined {
  if (!name) return undefined;
  return aliasesForType(aliases, type).find((a) => a.name === name);
}

/**
 * The label for a node's type chip. `Node.alias` only counts as a community
 * alias when the community actually configures one by that name for the node's
 * type — events reuse the same column for their public /e/<slug> slug, which
 * must never surface as a type label. Anything unrecognised falls back to the
 * canonical type name ("Event", "Community", …).
 */
export function nodeTypeLabel(
  type: string | null | undefined,
  alias: string | null | undefined,
  aliases: CommunityAlias[] | undefined,
  nodeTypes?: NodeTypeConfig[],
): string {
  const t = type ?? '';
  if (!t) return alias ?? '';
  return findAlias(aliases, alias, t)?.name ?? getNodeTypeConfig(t, nodeTypes).name;
}

// Canonical relationship (edge) types and their default colours. A community
// overrides these via `linkTypes`; this is the seeded fallback. The `system`
// types back the auto-link flows (RSVP/event/intro/context-note mentions) and
// must always resolve, even before a community config loads. Keep in sync with
// the `Community.linkTypes` default in schema.prisma.
export const DEFAULT_LINK_TYPES: LinkTypeConfig[] = [
  { name: 'Related',     color: '#94a3b8', directed: false },
  { name: 'Knows',       color: '#2563eb', directed: false },
  { name: 'Works at',    color: '#9333ea', directed: true  },
  { name: 'Founded',     color: '#16a34a', directed: true  },
  { name: 'Invested in', color: '#f59e0b', directed: true  },
  { name: 'Member of',   color: '#0ea5e9', directed: true  },
  { name: 'Partner',     color: '#ec4899', directed: false },
  { name: 'Mentors',     color: '#14b8a6', directed: true  },
  { name: 'Attended',    color: '#ef4444', directed: true,  system: true },
  { name: 'Hosting',     color: '#ef4444', directed: true,  system: true },
  { name: 'Introduced',  color: '#06b6d4', directed: false, system: true },
  { name: 'Mentioned',   color: '#8b5cf6', directed: false, system: true },
  { name: 'Contains',    color: '#64748b', directed: true,  system: true },
];

/**
 * All link types available for a community (its config, or the default set).
 */
export function getLinkTypes(communityLinkTypes?: LinkTypeConfig[]): LinkTypeConfig[] {
  return communityLinkTypes && communityLinkTypes.length > 0 ? communityLinkTypes : DEFAULT_LINK_TYPES;
}
