// Graph domain: nodes, links, node/link type configs, aliases, and their
// canonical defaults + resolution helpers.

// Node type is now dynamic per community
export type NodeType = string;

// Shape options for node rendering
type NodeShape = 'rectangle' | 'hexagon' | 'circle' | 'square';

// Configuration for a node type
export interface NodeTypeConfig {
  name: string; // e.g., "Person", "Organization"
  color: string; // Hex color e.g., "#2563eb"
  shape: NodeShape; // Shape to render
  icon?: string; // Optional emoji or icon
}

export interface NBNode {
  id: string;
  type: NodeType;
  name: string;
  subtitle?: string | null;
  location?: string | null;
  url?: string | null;
  tags?: string[];
  image_url?: string | null;
  metadata?: Record<string, unknown>;
  alias?: string | null;
  community_id?: string | null;
  createdAt?: string;
  // Force graph will add these during simulation
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
  fx?: number | null;
  fy?: number | null;
  // Anti-bouncing system
  lastFix?: Record<string, number>;
}

type RelationshipType =
  | 'works_at'
  | 'founded'
  | 'invested_in'
  | 'attended'
  | 'hosting'
  | 'member_of'
  | 'sponsors'
  | 'partner_with'
  | 'related'
  | 'knows'
  | 'mentors'
  | 'introduced';

// Where a Link came from. `manual` = created in the UI by an admin; the rest are
// system-generated by an action (and carry `originRef` for symmetric auto-undo);
// `context` = derived from an entity mention in a context note (originRef = the
// note path); `import` = bulk-loaded curated data. See docs/link-management-design.md.
export type LinkOrigin = 'manual' | 'event_attendance' | 'event_hosting' | 'intro' | 'context' | 'import';

export interface NBLink {
  source: string | NBNode; // node id or node object
  target: string | NBNode; // node id or node object
  relationship: RelationshipType | (string & {});
  since?: string; // ISO date
  metadata?: Record<string, unknown>;
  community_id?: string;
  origin?: LinkOrigin;     // provenance; surfaced read-only by the graph serializer
  id?: number;             // DB id, exposed read-only so the client can reconcile optimistic edits
}

export interface GraphData {
  nodes: NBNode[];
  links: NBLink[];
}

// A named alias with a display color, scoped to a specific node type within a community
export interface CommunityAlias {
  name: string;    // e.g. "Founder"
  color: string;   // Hex color e.g. "#16a34a"
  nodeType: string; // e.g. "Person", "Organization"
}

// A community-configurable relationship (edge) type — mirrors NodeTypeConfig.
// Managed in the console alongside node types; the stored Link.relationship is the
// slug of `name` (see lib/graph/relationships.ts normalizeRelationship).
export interface LinkTypeConfig {
  name: string;       // human label, e.g. "Works at"
  color: string;      // hex, tints the edge stroke
  directed: boolean;  // arrowhead vs plain line
  system?: boolean;   // attended | hosting | introduced — auto-flows depend on these (recolor-only, can't delete)
}

// Canonical node types and their default colours/shapes. A community can override
// these via `nodeTypes`, but every type listed here resolves to a non-grey colour
// even before a community config has loaded. This is what prevents the
// "everything is grey on first paint" race condition.
export const DEFAULT_NODE_TYPES: NodeTypeConfig[] = [
  { name: 'Person',   color: '#2563eb', shape: 'rectangle' },
  { name: 'Group',    color: '#9333ea', shape: 'square'    },
  { name: 'Event',    color: '#ef4444', shape: 'rectangle' },
  { name: 'Resource', color: '#f59e0b', shape: 'rectangle' },
];

// (NODE_COLORS removed — all type→colour resolution goes through the
// case-insensitive getNodeTypeConfig/getTypeColor canonical helpers.)

/**
 * Get node type configuration for a specific type within a community
 */
// Legacy/synonym type names that map onto a canonical base type. Keeps nodes
// still stored (or cached) as "organization" rendering identically to "Group"
// after the Organization→Group rename, so un-migrated or stale-cache data never
// falls through to the grey "unknown type" placeholder.
const TYPE_SYNONYMS: Record<string, string> = {
  organization: 'group',
  organisation: 'group',
  org: 'group',
};

export function getNodeTypeConfig(
  type: string,
  communityNodeTypes?: NodeTypeConfig[]
): NodeTypeConfig {
  const normalized = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[normalized] ?? normalized;

  // Check community-specific overrides first (case-insensitive), matching either
  // the raw type or its canonical synonym.
  if (communityNodeTypes) {
    const config = communityNodeTypes.find(t => {
      const n = t.name.toLowerCase();
      return n === normalized || n === canonical;
    });
    if (config) return config;
  }

  // Always fall back to DEFAULT_NODE_TYPES before giving up
  const defaultConfig = DEFAULT_NODE_TYPES.find(t => {
    const n = t.name.toLowerCase();
    return n === normalized || n === canonical;
  });
  if (defaultConfig) return defaultConfig;

  // Truly unknown type — capitalize for display
  return { name: type.charAt(0).toUpperCase() + type.slice(1), color: '#6b7280', shape: 'rectangle' };
}

/**
 * The avatar-fallback glyph a node type should draw when it has no image. People
 * get the person silhouette; groups/organisations the cluster; events a calendar;
 * resources a document. Any other type returns null and the caller falls back to
 * name initials. This is a clean SVG-glyph system — deliberately not emoji.
 */
export function getNodeGlyph(
  type: string | null | undefined
): 'person' | 'group' | 'event' | 'resource' | null {
  if (!type) return null;
  const normalized = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[normalized] ?? normalized;
  if (canonical === 'person' || canonical === 'people') return 'person';
  if (canonical === 'group') return 'group';
  if (canonical === 'event' || canonical === 'events') return 'event';
  if (canonical === 'resource' || canonical === 'resources') return 'resource';
  return null;
}

/**
 * Community aliases scoped to a base node type. Matching is case-insensitive
 * because stored node `type` values aren't consistently cased — the canonical
 * way to relate an alias to a node type across the app.
 */
export function aliasesForType(
  aliases: CommunityAlias[] | undefined,
  type: string | null | undefined,
): CommunityAlias[] {
  if (!type) return [];
  const t = type.toLowerCase();
  const canonical = TYPE_SYNONYMS[t] ?? t;
  return (aliases ?? []).filter((a) => {
    const n = a.nodeType.toLowerCase();
    return n === t || n === canonical;
  });
}

/**
 * Find the alias with a given name for a node type (case-insensitive on type).
 * Returns undefined when name is empty or no alias matches.
 */
export function findAlias(
  aliases: CommunityAlias[] | undefined,
  name: string | null | undefined,
  type: string,
): CommunityAlias | undefined {
  if (!name) return undefined;
  return aliasesForType(aliases, type).find((a) => a.name === name);
}

// Canonical relationship (edge) types and their default colours. A community
// overrides these via `linkTypes`; this is the seeded fallback. The `system`
// types back the auto-link flows (RSVP/event/intro/context-note mentions) and
// must always resolve, even before a community config loads. Keep in sync with
// the `Community.linkTypes` default in schema.prisma.
export const DEFAULT_LINK_TYPES: LinkTypeConfig[] = [
  { name: 'Related',     color: '#94a3b8', directed: false },
  { name: 'Knows',       color: '#2563eb', directed: false },
  { name: 'Works at',    color: '#9333ea', directed: true  },
  { name: 'Founded',     color: '#16a34a', directed: true  },
  { name: 'Invested in', color: '#f59e0b', directed: true  },
  { name: 'Member of',   color: '#0ea5e9', directed: true  },
  { name: 'Partner',     color: '#ec4899', directed: false },
  { name: 'Mentors',     color: '#14b8a6', directed: true  },
  { name: 'Attended',    color: '#ef4444', directed: true,  system: true },
  { name: 'Hosting',     color: '#ef4444', directed: true,  system: true },
  { name: 'Introduced',  color: '#06b6d4', directed: false, system: true },
  { name: 'Mentioned',   color: '#8b5cf6', directed: false, system: true },
];

/**
 * All link types available for a community (its config, or the default set).
 */
export function getLinkTypes(communityLinkTypes?: LinkTypeConfig[]): LinkTypeConfig[] {
  return communityLinkTypes && communityLinkTypes.length > 0 ? communityLinkTypes : DEFAULT_LINK_TYPES;
}
