'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import { UserPlus, Link2, Users } from 'lucide-react';
import { Alert, Avatar, Button, ConfirmDialog, Field, Input, SearchInput, SettingsCard } from '@/components/ui';
import Select from '@/components/ui/Select';
import Dropdown from '@/components/ui/Dropdown';
import { useConsoleAction } from '@/components/console/ConsoleSaveContext';

interface Member {
  id: string;
  userId: string;
  role: string;
  status: string;
  joinedAt: string;
  user: {
    id: string;
    name: string;
    email: string;
    image: string | null;
    createdAt: string;
  };
}

interface Props {
  communityId: string;
  /** Lets the console nav badge track the pending join-request count. */
  onPendingCountChange?: (count: number) => void;
}

/**
 * Reusable invite link for the community. Admins copy it to share; regenerating
 * revokes the old link. Lazily generated by GET /invite the first time.
 */
function InviteLinkRow({ communityId }: { communityId: string }) {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const runAction = useConsoleAction();

  useEffect(() => {
    let active = true;
    fetch(`/api/communities/${communityId}/invite`)
      .then(r => r.json())
      .then(d => { if (active) setUrl(d.url ?? ''); })
      .catch(() => {})
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [communityId]);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };

  const regenerate = async () => {
    setConfirmRegenerate(false);
    try {
      await runAction(async () => {
        const res = await fetch(`/api/communities/${communityId}/invite`, { method: 'POST' });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error ?? 'Failed to regenerate link');
        setUrl(data.url ?? '');
      });
    } catch { /* status pill shows the failure */ }
  };

  return (
    <div>
      <div className="flex items-center gap-2">
        <input
          readOnly
          value={loading ? 'Loading…' : url}
          className="min-w-0 flex-1 truncate rounded-xl border border-transparent bg-surface-2 px-3.5 py-2.5 text-xs text-text-secondary"
        />
        <Button variant="pill-secondary" onClick={copy} disabled={loading || !url}>
          {copied ? 'Copied' : 'Copy'}
        </Button>
      </div>
      <div className="mt-2 flex items-center justify-between">
        <p className="text-xs text-text-muted">
          New joiners appear below as pending requests for you to approve.
        </p>
        <button
          type="button"
          onClick={() => setConfirmRegenerate(true)}
          disabled={loading}
          className="text-xs font-medium text-text-muted transition-colors hover:text-text-primary disabled:opacity-50"
        >
          Regenerate
        </button>
      </div>

      <ConfirmDialog
        open={confirmRegenerate}
        title="Regenerate invite link"
        body="The current link will stop working immediately. Anyone holding the old link won't be able to join with it."
        confirmLabel="Regenerate"
        onConfirm={regenerate}
        onClose={() => setConfirmRegenerate(false)}
      />
    </div>
  );
}

function InviteModal({ communityId, onAdded, onClose }: {
  communityId: string;
  onAdded: (member: Member) => void;
  onClose: () => void;
}) {
  const [email, setEmail] = useState('');
  const [role, setRole] = useState<'member' | 'admin'>('member');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const res = await fetch(`/api/communities/${communityId}/members`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: email.trim(), role }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error ?? 'Failed to add member'); return; }
      onAdded(data.member);
      onClose();
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative w-full max-w-sm space-y-4 rounded-2xl border border-border-subtle bg-surface-1 p-6 shadow-float">
        <div className="flex items-center justify-between">
          <h2 className="font-ginto text-base font-medium text-text-primary">Invite member</h2>
          <button onClick={onClose} className="text-text-muted transition-colors hover:text-text-primary" aria-label="Close">
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <Field label="Email address">
            <Input
              type="email"
              required
              autoFocus
              placeholder="user@example.com"
              value={email}
              onChange={e => setEmail(e.target.value)}
            />
          </Field>
          <Field label="Role">
            <Select value={role} onChange={e => setRole(e.target.value as 'member' | 'admin')}>
              <option value="member">Member</option>
              <option value="admin">Admin</option>
            </Select>
          </Field>
          {error && <Alert variant="error" inline>{error}</Alert>}
          <div className="flex gap-2 pt-1">
            <Button type="button" variant="pill-secondary" onClick={onClose} className="flex-1">
              Cancel
            </Button>
            <Button type="submit" variant="pill-primary" loading={loading} loadingText="Inviting…" className="flex-1">
              Invite
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function MembersPanel({ communityId, onPendingCountChange }: Props) {
  const [members, setMembers] = useState<Member[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [actionError, setActionError] = useState('');
  const [showInvite, setShowInvite] = useState(false);
  const [query, setQuery] = useState('');
  const [confirm, setConfirm] = useState<{ kind: 'remove' | 'deny'; userId: string; name: string } | null>(null);
  const runAction = useConsoleAction();

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/communities/${communityId}/members`);
      if (!res.ok) throw new Error('Failed to load members');
      const data = await res.json();
      setMembers(data.members);
    } catch {
      setError('Failed to load members');
    } finally {
      setLoading(false);
    }
  }, [communityId]);

  useEffect(() => { load(); }, [load]);

  const pendingMembers = useMemo(() => members.filter(m => m.status === 'pending'), [members]);
  const activeMembers = useMemo(() => members.filter(m => m.status !== 'pending'), [members]);

  useEffect(() => {
    onPendingCountChange?.(pendingMembers.length);
  }, [pendingMembers.length, onPendingCountChange]);

  const filteredMembers = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return activeMembers;
    return activeMembers.filter(m =>
      m.user.name.toLowerCase().includes(q) || m.user.email.toLowerCase().includes(q)
    );
  }, [activeMembers, query]);

  const memberAction = async (userId: string, action: () => Promise<void>) => {
    setActionError('');
    setActionLoading(userId);
    try {
      await runAction(action);
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Action failed');
    } finally {
      setActionLoading(null);
    }
  };

  const updateRole = (userId: string, role: string) =>
    memberAction(userId, async () => {
      const res = await fetch(`/api/communities/${communityId}/members/${userId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ role }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? 'Failed to update role');
      setMembers(prev => prev.map(m => m.userId === userId ? { ...m, role: data.member.role } : m));
    });

  const approveMember = (userId: string) =>
    memberAction(userId, async () => {
      const res = await fetch(`/api/communities/${communityId}/members/${userId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: 'active' }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? 'Failed to approve');
      setMembers(prev => prev.map(m => m.userId === userId ? { ...m, status: 'active' } : m));
    });

  const removeMember = (userId: string) =>
    memberAction(userId, async () => {
      const res = await fetch(`/api/communities/${communityId}/members/${userId}`, { method: 'DELETE' });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? 'Failed to remove');
      setMembers(prev => prev.filter(m => m.userId !== userId));
    });

  if (loading) return <div className="p-6 text-sm text-text-muted">Loading members…</div>;
  if (error) return <Alert variant="error">{error}</Alert>;

  return (
    <div className="grid grid-cols-1 items-start gap-6 xl:grid-cols-2">
      {actionError && (
        <Alert variant="error" onDismiss={() => setActionError('')} className="xl:col-span-2">{actionError}</Alert>
      )}

      <SettingsCard
        icon={<Link2 className="h-5 w-5" />}
        title="Invite people"
        description="Share the invite link, or add someone directly by email."
        className={pendingMembers.length === 0 ? 'xl:col-span-2' : undefined}
        action={
          <Button variant="pill-primary" onClick={() => setShowInvite(true)}>
            <span className="inline-flex items-center gap-1.5">
              <UserPlus size={14} />
              Invite member
            </span>
          </Button>
        }
      >
        <InviteLinkRow communityId={communityId} />
      </SettingsCard>

      {/* Pending join requests (from invite links) */}
      {pendingMembers.length > 0 && (
        <SettingsCard
          title={`Pending requests (${pendingMembers.length})`}
          description="People who joined via the invite link, waiting for approval."
          className="border-amber-400/40"
        >
          <div className="space-y-3">
            {pendingMembers.map(member => (
              <div key={member.id} className="flex items-center justify-between gap-3">
                <div className="flex min-w-0 items-center gap-3">
                  <Avatar name={member.user.name} imageUrl={member.user.image} size="sm" />
                  <div className="min-w-0">
                    <div className="truncate text-sm font-medium text-text-primary">{member.user.name}</div>
                    <div className="truncate text-xs text-text-muted">{member.user.email}</div>
                  </div>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <Button
                    variant="pill-primary"
                    onClick={() => approveMember(member.userId)}
                    disabled={actionLoading === member.userId}
                    className="!px-3 !py-1.5 !text-xs"
                  >
                    Approve
                  </Button>
                  <Button
                    variant="pill-secondary"
                    onClick={() => setConfirm({ kind: 'deny', userId: member.userId, name: member.user.name })}
                    disabled={actionLoading === member.userId}
                    className="!px-3 !py-1.5 !text-xs"
                  >
                    Deny
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </SettingsCard>
      )}

      {/* Members table */}
      <SettingsCard
        icon={<Users className="h-5 w-5" />}
        title={`Members (${activeMembers.length})`}
        description="Everyone in this community, and their role."
        bodyClassName="space-y-4"
        className="xl:col-span-2"
      >
        {activeMembers.length > 3 && (
          <SearchInput
            value={query}
            onChange={setQuery}
            placeholder="Search members…"
          />
        )}

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border-subtle text-left">
                <th className="pb-3 pr-4 text-xs font-semibold uppercase tracking-wider text-text-muted">Member</th>
                <th className="pb-3 pr-4 text-xs font-semibold uppercase tracking-wider text-text-muted">Role</th>
                <th className="pb-3 pr-4 text-xs font-semibold uppercase tracking-wider text-text-muted">Joined</th>
                <th className="pb-3 text-xs font-semibold uppercase tracking-wider text-text-muted"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border-subtle">
              {filteredMembers.map(member => (
                <tr key={member.id} className="transition hover:bg-surface-2">
                  <td className="py-3 pr-4">
                    <div className="flex items-center gap-3">
                      <Avatar name={member.user.name} imageUrl={member.user.image} size="sm" />
                      <div>
                        <div className="font-medium text-text-primary">{member.user.name}</div>
                        <div className="text-xs text-text-muted">{member.user.email}</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-3 pr-4">
                    <Dropdown
                      value={member.role}
                      options={[
                        { value: 'member', label: 'Member' },
                        { value: 'admin', label: 'Admin' },
                      ]}
                      onChange={role => { if (role !== member.role) updateRole(member.userId, role); }}
                      active={member.role === 'admin'}
                      menuWidthClass="min-w-[130px]"
                    />
                  </td>
                  <td className="py-3 pr-4 text-xs text-text-muted">
                    {new Date(member.joinedAt).toLocaleDateString()}
                  </td>
                  <td className="py-3 text-right">
                    <Button
                      variant="danger-text"
                      onClick={() => setConfirm({ kind: 'remove', userId: member.userId, name: member.user.name })}
                      disabled={actionLoading === member.userId}
                    >
                      Remove
                    </Button>
                  </td>
                </tr>
              ))}
              {filteredMembers.length === 0 && (
                <tr>
                  <td colSpan={4} className="py-8 text-center text-sm text-text-muted">
                    {query ? 'No members match your search' : 'No members yet'}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </SettingsCard>

      <ConfirmDialog
        open={confirm !== null}
        title={confirm?.kind === 'deny' ? 'Deny join request' : 'Remove member'}
        body={
          confirm?.kind === 'deny' ? (
            <>Deny <span className="font-semibold">{confirm?.name}</span>&apos;s request to join?</>
          ) : (
            <>Remove <span className="font-semibold">{confirm?.name}</span> from this community?</>
          )
        }
        confirmLabel={confirm?.kind === 'deny' ? 'Deny' : 'Remove'}
        destructive
        onConfirm={async () => {
          if (!confirm) return;
          const { userId } = confirm;
          setConfirm(null);
          await removeMember(userId);
        }}
        onClose={() => setConfirm(null)}
      />

      {showInvite && (
        <InviteModal
          communityId={communityId}
          onAdded={member => setMembers(prev => [...prev, member])}
          onClose={() => setShowInvite(false)}
        />
      )}
    </div>
  );
}
