/**
 * Blackbird's team — everyone on blackbird.vc/team, September 2026, in the
 * words of their own team pages.
 *
 * GENERATED, then kept by hand: `does` is their answer to "What do you do at
 * Blackbird?" (or the first line of About Me when they left it blank), `before`
 * their answer to "What did you do before Blackbird?", `quote` the line under
 * their name on the team page. Two pages give an office as "Auckland,
 * Australia"; both are recorded as Auckland, New Zealand.
 */

export type TeamGroup = 'Investments' | 'Operations' | 'Building Blackbird'

export interface SeedTeamMember {
  name: string
  role: string
  group: TeamGroup
  location: string
  /** Their page: https://www.blackbird.vc/team/<bbSlug>. */
  bbSlug: string
  does?: string
  before?: string
  quote?: string
}

export const TEAM: SeedTeamMember[] = [
  {
    name: "Alex Apoifis",
    role: "Partner, Chief Operating Officer",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "alex-apoifis",
    does: "I oversee an incredible team covering finance, legal, compliance, operations, investor relations and fundraising.",
    before: "I worked as a lawyer, investment banker and institutional stockbroker.",
  },
  {
    name: "Alex Gifford",
    role: "Head of Investment Programs",
    group: "Investments",
    location: "Melbourne, Australia",
    bbSlug: "alex-gifford",
    does: "As the Investments Chief of Staff, I support our amazing investments team to maximise their impact and spend their time doing what they do best - investing! I help improve communication, processes & productivity and connect the investments team with all other parts of the business.",
    before: "I worked as an environmental and human rights lawyer, as a study skills presenter with an education company, co-founded and co-hosted a gender podcast and most recently, in PwC’s education consulting team equipping Australians with the skills they need for the future of work.",
    quote: "Watch more comedy.",
  },
  {
    name: "Alissa Lucas",
    role: "Impact Associate",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "alissa-lucas",
    does: "I work to support our incredible founders, their companies, and Blackbird on impact and ESG initiatives.",
    before: "Before Blackbird, I worked as a banking and finance lawyer at Allen & Overy. I have also worked in the startup and fintech teams at KPMG in both Hong Kong and Sydney.",
    quote: "Everything happens for no reason",
  },
  {
    name: "Anthoney Duong",
    role: "Head of Investment Legal",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "anthoney-duong",
    does: "I oversee investment legal at Blackbird and run the legal aspects of our VC investments, exits and ongoing portfolio company management.",
    before: "I started my career as a private equity lawyer at King & Wood Mallesons in Sydney. I then worked as in-house legal at an investment firm and investment bank in Sydney and London.",
  },
  {
    name: "Baoying Tong",
    role: "Investment Associate",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "baoying-tong",
  },
  {
    name: "Becca Kennedy",
    role: "People & Culture Partner",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "becca-kennedy",
    does: "I work with Carlene Kemp, our CPO, to enable all Blackbirds to be their best self.",
    before: "I was a critical care veterinary nurse at a specialty and referral hospital.",
    quote: "It's nice to be nice",
  },
  {
    name: "Carlene Kemp",
    role: "Chief People Officer",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "carlene-kemp",
  },
  {
    name: "Catt Vongpraseuth",
    role: "Senior Operations Associate",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "catt-vongpraseuth",
    does: "I support the team with all the operational aspects of Blackbird. This includes everything from investor and portfolio reporting to compliance and fund operations.",
    before: "I worked in the finance team at Pacific Equity Partners for 5 years. Prior to that, I worked at EY in the assurance practice.",
  },
  {
    name: "Cindy Lam",
    role: "Legal Counsel",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "cindy-lam",
    does: "I’m a lawyer at Blackbird. I advise on various facets of Blackbird's fundraisings, fund structuring, fund governance/maintenance and other special projects.",
    before: "I was a financial regulatory lawyer at a commercial law firm in Sydney.",
    quote: "You miss 100% of the shots you don’t take.-Wayne Gretzky” -Michael Scott",
  },
  {
    name: "Connor Wiltshire",
    role: "Data Analyst",
    group: "Building Blackbird",
    location: "Auckland, New Zealand",
    bbSlug: "connor-wiltshire",
    does: "I help the investment team make the most well-informed decisions possible, whether that’s digging into portfolio data, spotting trends, or building tools that surface the right insights at the right time. I love making sense of messy data and turning it into something clear, useful, and actionable.",
    before: "I started out at Halter, working on supply chain and quality assurance. That sparked an interest in software, so I took a leap and completed a 16-week coding bootcamp with Dev Academy.",
    quote: "You grow through what you go through",
  },
  {
    name: "Davies Ayomide",
    role: "IT Operations Analyst",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "davies-ayomide",
    quote: "We are products of our experiences.",
  },
  {
    name: "Ed Little",
    role: "Head of Technology",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "ed-little",
    does: "I look after the Technology team at Blackbird, which provides IT, Security and Data capability to the Blackbird team. We makes sure every Blackbird has access to the systems and data they need to do their best work.",
    before: "I've worked in technology and risk roles for over 10 years, from software development to data analytics and visualisation. Most recently I worked as a technology risk consultant, specialising in security and data.",
    quote: "What could possibly go wrong?",
  },
  {
    name: "Georgia Robertson",
    role: "Associate",
    group: "Investments",
    location: "Auckland, New Zealand",
    bbSlug: "georgia-robertson",
    does: "I find and invest in ambitious Aussie and Kiwi Founders building generational companies - wherever they are in the world, and work with them from the very beginning.",
    before: "I’ve lived a few lives professionally, working across law, technology, social impact and data consulting. I was a corporate lawyer, then built the New Zealand arm of the fastest growing tech-charity in Australasia, before serving as CE of a data consultancy.",
    quote: "You never regret a swim.",
  },
  {
    name: "James Palmer",
    role: "Principal",
    group: "Investments",
    location: "Auckland, New Zealand",
    bbSlug: "james-palmer",
    does: "I find and back Aotearoa's most ambitious founders who solve truly painful problems.",
    before: "I've taken a random walk through finance. Corporate Banking > Corporate Development & Strategy > Venture Capital.",
    quote: "Naivety is powerful when applied to the right problem.",
  },
  {
    name: "Jane Shaw",
    role: "Business Operations Analyst",
    group: "Operations",
    location: "Melbourne, Australia",
    bbSlug: "jane-shaw",
    does: "I work across operational areas at Blackbird such as investor onboarding, fund reporting, capital calls, and compliance.",
    before: "Before Blackbird, I was a Customer Success Lead in the Digital Innovation team at Justice Connect, a community legal centre servicing Victoria and NSW.",
  },
  {
    name: "Jasmin Jenkins",
    role: "Head of Investor Relations",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "jasmin-jenkins",
    does: "My mission is to connect LPs with all things Blackbird, and to surface and solve their pain points. But we are not only stewards capital - we also want to bring some magic to their lives.",
    before: "My happiest days were in hospitality, in the golden era of Cosmopolitans and foam on every plate. I've most recently been in sustainable finance and prior to that, all things funds management.",
    quote: "We get to think the world is progressing when it is only repeating itself - Rudyard Kipling",
  },
  {
    name: "Jessica Tulp",
    role: "Associate",
    group: "Investments",
    location: "Auckland, New Zealand",
    bbSlug: "jessica-tulp",
    does: "As an Associate on the NZ investments team, my mission is to find and invest in the best Kiwi founders, right from the very beginning.",
    before: "I come from a strategic operator background, having worked directly alongside the Founders of some of NZ's most epic companies, Rocket Lab and Soul Machines. Most recently I've spent a few years living in Amsterdam, again in a Chief of Staff-style role, exploring my Dutch roots.",
    quote: "Logic will get you from A to B. Imagination will take you everywhere.",
  },
  {
    name: "Joel Connolly",
    role: "Creative Director & Head of Blackbird Foundation",
    group: "Building Blackbird",
    location: "Orange, Australia",
    bbSlug: "joel-connolly",
    does: "I'm Creative Director and I run our Brand and Comms team with Melia. I work on making Blackbird into a beautiful place full of creativity and rich in meaning.",
    before: "Before Blackbird I founded a talent management business. We managed bands including the Rubens, Cloud Control, Fishing and Urthboy.",
    quote: "Still trying to make fetch happen.",
  },
  {
    name: "Josephine Tay",
    role: "Giants Program Manager",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "josephine-tay",
    does: "I run the Giants program at Blackbird. Giants is a free eight week program designed to support ambitious, early stage founders forge new pathways into the ANZ ecosystem.",
    before: "My career has been non-linear by design. Before I joined Blackbird, I was a Venture Growth and Community Lead at an agtech accelerator.",
  },
  {
    name: "Jun Hu",
    role: "Business Operations Analyst",
    group: "Operations",
    location: "Melbourne, Australia",
    bbSlug: "jun-hu",
    does: "I support the team with all the operational aspects of Blackbird. This includes everything from investor and portfolio reporting to compliance and fund operations.",
    quote: "Keep finding discomfort, or the discomfort will find you.",
  },
  {
    name: "Justine Nangle",
    role: "General Counsel",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "justine-nangle",
    does: "I oversee all of the legal, compliance and risk aspects relating to the Blackbird group, including our funds and the investments we make into startups.",
    before: "Previously, I was Head of Legal & Compliance at CHAMP Private Equity (CPE Capital) in Sydney and Head of Legal (Europe) at Pantheon Ventures in London. Before that, I worked as a solicitor in corporate/financial services law at law firms based in both Sydney and London.",
    quote: "If I didn't become a lawyer I would have loved to work in musical theatre",
  },
  {
    name: "Kate Glazebrook",
    role: "Head of Impact & Operating Principal",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "kate-glazebrook",
    does: "I work to grow and amplify our portfolio companies' positive impact on the world. That means I have the privilege of working with founders and their teams on everything from sustainability, to social impact, to how they design the tech we're all proud to use.",
    before: "I was the cofounder and CEO of Applied, a Blackbird portfolio company, which uses behavioural science de-bias hiring and help the best person get the job, regardless of their background.",
    quote: "It’s the simple (even boring-sounding) characteristics that matter most in a person",
  },
  {
    name: "Katie Tholo",
    role: "Partnerships & Program Producer",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "katie-tholo",
    does: "I’m the Partnerships & Program Producer for Sunrise, Blackbird’s love letter to our founders and the startup community.",
  },
  {
    name: "Maddy Guest",
    role: "Investment Associate",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "maddy-guest",
    does: "I invest in Aussie and Kiwi founders with outsized ambition",
    quote: "Life shrinks or expands in proportion to one’s courage",
  },
  {
    name: "Mahalia Lum",
    role: "Executive Assistant (Alex Apoifis & Tom Humphrey) and Sydney Office Manager",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "mahalia-lum",
    does: "I support Alex Apoifis and Tom Humphrey to organise their time in order to set them up for success - for Alex, to manage all operational aspects of the funds, and Tom to find and invest in amazing Aussie and NZ start-ups.",
    before: "I worked at Office Hub which is a marketplace for serviced offices, coworking and shared offices. I was the EA to the CEO and Operations Specialist there and was lucky enough to be a part of the journey as we grew from a handful of employees to a global business with teams across 7 different countries!",
    quote: "Get excited for the little things",
  },
  {
    name: "Max Meyer",
    role: "Principal",
    group: "Investments",
    location: "Melbourne, Australia",
    bbSlug: "max-meyer",
    does: "My mission is to find and work alongside the most ambitious founders that endeavour to revolutionise the way people live their life.",
    quote: "Perpetual optimism is a force multiplier",
  },
  {
    name: "Michael Tolo",
    role: "Partner",
    group: "Investments",
    location: "Melbourne, Australia",
    bbSlug: "michael-tolo",
    does: "I work with unreasonably ambitious founders who are looking to solve the most complex and consequential problems. No idea is too early, no risk is too great and no plan is too improbable!",
    before: "Investor at Playground Global in Palo Alto and Future Fund in Melbourne.",
  },
  {
    name: "Morven Brown",
    role: "Executive Assistant (Nick Crocker & Michael Tolo), Melbourne Office Manager",
    group: "Building Blackbird",
    location: "Melbourne, Australia",
    bbSlug: "morven-brown",
    does: "I work closely with partners, Nick Crocker and Michael Tolo, to optimise their time and maximise their output as leaders and investors.",
    before: "I was employee #3 at a medical device prototyping start up, where I was EA to the CEO.",
    quote: "How you do anything is how you do everything",
  },
  {
    name: "Nick Crocker",
    role: "Partner",
    group: "Investments",
    location: "Melbourne, Australia",
    bbSlug: "nick-crocker",
    does: "I invest in Australia's most ambitious founders.",
    before: "Music journalism, law, started a digital agency, started a music website, started a healthcare company (called Sessions, that Blackbird funded) and worked at Boxee, MyFitnessPal and Under Armour.",
    quote: "I wish there was a way to know you're in the good old days before you've actually left them.",
  },
  {
    name: "Nick Erzetic",
    role: "Data & Product Manager",
    group: "Building Blackbird",
    location: "Remote (Brisbane), Australia",
    bbSlug: "nick-erzetic",
    does: "I work with all teams at Blackbird to build internal tools and automations that support every stage of the investment lifecycle.",
    before: "Prior to Blackbird I worked within product and data at an Australian ad-tech startup and studied Business Analytics and Finance at the University of Queensland.",
    quote: "The grass is greener where you water it",
  },
  {
    name: "Niki Scevak",
    role: "Partner",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "niki-scevak",
    does: "I believe in the hungry not the proven. That the people who bring about change are outsiders not insiders.",
    before: "Before Blackbird, I founded Startmate upon moving back to Sydney in 2010. Before investing, I also started two software companies and lived in New York.",
    quote: "The more ambitious you are, the more likely you are to succeed",
  },
  {
    name: "Phoebe Harrop",
    role: "Partner",
    group: "Investments",
    location: "Auckland, New Zealand",
    bbSlug: "phoebe-harrop",
    does: "Based in New Zealand, I invest in unreasonably ambitious Kiwi founders who want to build world-changing companies. I'm interested in make-stuff-better ideas across everything from fintech to healthcare, future food to cleantech.",
    before: "I was an investor at Generation, working across London and San Francisco, investing in the likes of Gusto, Guideline, Nature's Fynd and Remitly.",
    quote: "Companies are just people. The best companies grow from the best people.",
  },
  {
    name: "Rick Baker",
    role: "Partner",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "rick-baker",
    does: "My primary role is to find and invest in great tech startups and then help them as much as I can.",
    before: "Prior to Blackbird I ran the venture portfolio at MLC and invested over half a billion dollars into venture capital. Before this I co-founded two software companies, Right Party Connect (sold to Adeptra) and IDC Global.",
    quote: "Passionate about Aussie and Kiwi startups.",
  },
  {
    name: "Riley Fallon",
    role: "Legal & Compliance Associate",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "riley-fallon",
    does: "At Blackbird, I am involved in matters relating to our range of funds. My role also encompasses general legal work, reviewing contracts, overseeing regulatory filings, and rolling out compliance-related activities.",
    before: "Graduate lawyer at a commercial law firm in Sydney",
    quote: "There's some good in this world, Mr. Frodo and it's worth fighting for",
  },
  {
    name: "Robyn Denholm",
    role: "Board Member",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "robyn-denholm",
    does: "I work with a handful of our most ambitious late stage company founders to reach their beautiful potential, as well as advising Blackbird as part of its board.",
    before: "I've been fortunate enough to work in finance and operational roles with some phenomenal global technology companies, including Toyota, Sun Microsystems, Juniper Networks and Telstra. I've served on the boards of Echelon Corporation and ABB previously, and I'm presently the Chair of the Board of Directors at Tesla.",
    quote: "I believe bold ambitions enable a better world",
  },
  {
    name: "Samantha Wong",
    role: "Partner",
    group: "Investments",
    location: "Auckland, New Zealand",
    bbSlug: "samantha-wong",
    does: "I find hugely ambitious Aussie and Kiwi founders solving deeply painful problems as early as possible, and try to back them with money, time and most importantly, our belief.",
    before: "I was a lawyer, then a product manager then a Startmate company founder. I joined Blackbird as Head of Operations in 2015 before moving to investments in 2017.",
  },
  {
    name: "Saron Berhane",
    role: "Foundry Lead",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "saron-berhane",
    does: "I'm the Foundry Lead at Blackbird. I support ambitious researchers who are curious about startups and want to take their world-changing ideas to the next level.",
    quote: "If you do the work, the score will take care of itself.",
  },
  {
    name: "Sean Weston",
    role: "Head of Fund Operations",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "sean-weston",
    does: "I support the team with all operational aspects of the Blackbird funds, from investor onboarding to fund reporting, tax and compliance.",
    before: "I spent six years working within Big 4 providing tax structuring and due diligence assistance on a range of domestic and international private equity, venture capital, corporate M&A and property transactions.",
    quote: "You make your own luck",
  },
  {
    name: "Silk Kadala",
    role: "Principal",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "silk-kadala",
    does: "I'm a Principal at Blackbird based in our Sydney office. The best part of what I do is find founders with unique ideas, then help them make a huge difference in the world.",
    before: "Management consulting in Australia and the US, product commercialisation at a MedTech company, built a education startup.",
    quote: "Relationships rule the world.",
  },
  {
    name: "Sofia Echesortu",
    role: "Portfolio Program Lead",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "sofia-echesortu",
    does: "I am the Portfolio Program Lead at Blackbird. Working with the Blackbird team to creatively create unique experiences and moments to build and support a community of people doing great things for this planet.",
    before: "I was a Design Strategist at an urban design firm and teaching Creativity and Entrepreneurship at UNSW Art, Design & Architecture for Master of Design students.",
    quote: "Always leave a little room for the unexpected\" - James Clear",
  },
  {
    name: "Sophie Steverson",
    role: "EA to Rick Baker, Niki Scevak and Samantha Wong",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "sophie-steverson",
    does: "I work with Rick, Niki and Sam to organise and maximise their time so they can focus on what they do best, finding and investing in great Australian and New Zealand start-ups.",
    before: "I worked with Stu Gregor, co-founder of Four Pillars Gin and before this with restaurateur and food writer Bill Granger. Basically, I love eating food and drinking great Australian gin!",
    quote: "Hospitality is at the heart of every great business that you know and love.",
  },
  {
    name: "Sophie Taylor",
    role: "Head of Strategy and Projects",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "sophie-taylor",
  },
  {
    name: "Theia Gabatan",
    role: "Grant Programs and Impact Lead @ Blackbird Foundation",
    group: "Building Blackbird",
    location: "Brisbane (Meanjin), Australia",
    bbSlug: "theia-gabatan",
    does: "In a nutshell, I focus on scaling Blackbird Foundation's social mission to unleash creativity in young people. I primarily focus on leading our grant programs, community, and impact initiatives.",
    before: "Pre-Blackbird I worked in various marketing roles at organisations in the education, construction, social entrepreneurship and social impact spaces. At uni I studied law and business, with a brief stint in politics and comms.",
    quote: "Being cringe is the price you pay for excellence 🥲",
  },
  {
    name: "Tom Harvey",
    role: "Investor Relations Associate",
    group: "Operations",
    location: "Sydney, Australia",
    bbSlug: "tom-harvey",
    does: "As an Investor Relations Associate at Blackbird, I help build and nurture relationships with our Limited Partners, ensuring they stay informed, engaged, and excited about our journey.",
    before: "Before Blackbird, I worked in Sales and Strategy for a large tech firm.",
    quote: "It’s not about ideas. It’s about making ideas happen.",
  },
  {
    name: "Tom Humphrey",
    role: "Partner",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "tom-humphrey",
    does: "I sit in the investments team in our Sydney office. I seek to partner with the most ambitious of Australia's founders to build world class businesses.",
    before: "Spent 8 years building two companies - first as COO of Kanopy, a B2B video streaming company based in San Francisco and OurDeal, a D2C ecommerce website based in Sydney. Immediately before joining Blackbird in 2021, I spent 2 years with a US-based VC fund called Access Ventures.",
    quote: "A desk is a dangerous place from which to watch the world",
  },
  {
    name: "Tristan Edwards",
    role: "Investment Associate",
    group: "Investments",
    location: "Sydney, Australia",
    bbSlug: "tristan-edwards",
    does: "I love meeting brilliant technical founders who've lived the problem long enough to solve it differently.",
    before: "I was an investor at Medicxi, a biotech venture fund in London, working on formation and late stage investments across companies like New Amsterdam Pharma, T-Cypher Bio and Altesa Biosciences. Prior to that, I was part of the founding team at BIOS building towards a USB port for the body.",
    quote: "Measure Once, Cut Twice",
  },
  {
    name: "Zac Hardman",
    role: "Senior IT & Project Analyst",
    group: "Building Blackbird",
    location: "Sydney, Australia",
    bbSlug: "zac-hardman",
    does: "I work in our IT department helping support our service desk and maintaining our automations and website.",
    before: "I spent 7 years at a tractor and agricultural machinery dealership in Tasmania working across inventory control and sales admin.",
    quote: "My side projects have side projects",
  },
]
