// Generated by packages/tokens from its DTCG source. Do not edit.
// Change a token in packages/tokens/tokens/, then run `pnpm tokens:build`.

package com.visvine.mobile.ui.theme

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Semantic colours, light — the theme the app shows. Paint with these, never a literal. The accent is the person's choice, a VVAccent held by the theme controller. */
object VVColor {
    /** The one opaque surface: the page, floats, inputs. */
    val surface = Color(0xFFFFFFFF)
    /** A quiet fill: a neutral button, a selected row. Tints what it sits on. */
    val surfaceSubtle = Color(0xFF111827).copy(alpha = 0.025f)
    /** Hover, and the fill one step louder than subtle. */
    val surfaceMuted = Color(0xFF111827).copy(alpha = 0.05f)
    /** What the whole app sits on. */
    val surfaceBackdrop = Color(0xFFFFFFFF)
    /** Chrome over moving content, under a blur. */
    val surfaceGlass = Color(0xFFFFFFFF).copy(alpha = 0.82f)
    /** Body text, titles, icons that matter. */
    val fg = Color(0xFF111827)
    val fgSecondary = Color(0xFF374151)
    /** Metadata, labels, the `·` state line. */
    val fgMuted = Color(0xFF4B5563)
    /** Placeholders and disabled text only: below AA for reading. */
    val fgSubtle = Color(0xFF9CA3AF)
    /** Text on a filled accent or danger control. */
    val fgInverse = Color(0xFFFFFFFF)
    /** Links in content are the web's blue, never the accent. */
    val fgLink = Color(0xFF2563EB)
    /** Input and control borders. */
    val line = Color(0xFFD1D5DB)
    /** The hairline between sections. */
    val lineSubtle = Color(0xFFE5E7EB)
    /** The logo green. Fixed: it never follows the chosen accent. Use `accent` for anything a person's accent should repaint. */
    val brand = Color(0xFF78D870)
    /** The built-in Admin alias, the one alias a space cannot change. */
    val admin = Color(0xFFB4881B)
    /** Error text, a destructive button. */
    val danger = Color(0xFFDC2626)
    /** Hover on a destructive button; emphasised error text. */
    val dangerStrong = Color(0xFFB91C1C)
    /** An invalid field's border, a status dot. */
    val dangerBright = Color(0xFFEF4444)
    val dangerWash = Color(0xFFFEF2F2)
    val dangerLine = Color(0xFFFECACA)
    val warning = Color(0xFFB45309)
    val warningStrong = Color(0xFF92400E)
    val warningBright = Color(0xFFF59E0B)
    val warningWash = Color(0xFFFFFBEB)
    val warningLine = Color(0xFFFDE68A)
    val success = Color(0xFF15803D)
    val successStrong = Color(0xFF166534)
    val successBright = Color(0xFF22C55E)
    val successWash = Color(0xFFF0FDF4)
    val successLine = Color(0xFFBBF7D0)
    val info = Color(0xFF1D4ED8)
    val infoStrong = Color(0xFF1E40AF)
    val infoBright = Color(0xFF3B82F6)
    val infoWash = Color(0xFFEFF6FF)
    val infoLine = Color(0xFFBFDBFE)
    val hueRed = Color(0xFFEF4444)
    val hueRedFg = Color(0xFFB91C1C)
    val hueRedWash = Color(0xFFFEF2F2)
    val hueRedLine = Color(0xFFFECACA)
    val hueOrange = Color(0xFFF97316)
    val hueOrangeFg = Color(0xFFC2410C)
    val hueOrangeWash = Color(0xFFFFF7ED)
    val hueOrangeLine = Color(0xFFFED7AA)
    val hueAmber = Color(0xFFF59E0B)
    val hueAmberFg = Color(0xFFB45309)
    val hueAmberWash = Color(0xFFFFFBEB)
    val hueAmberLine = Color(0xFFFDE68A)
    val hueYellow = Color(0xFFEAB308)
    val hueYellowFg = Color(0xFFA16207)
    val hueYellowWash = Color(0xFFFEFCE8)
    val hueYellowLine = Color(0xFFFEF08A)
    val hueGreen = Color(0xFF22C55E)
    val hueGreenFg = Color(0xFF15803D)
    val hueGreenWash = Color(0xFFF0FDF4)
    val hueGreenLine = Color(0xFFBBF7D0)
    val hueTeal = Color(0xFF14B8A6)
    val hueTealFg = Color(0xFF0F766E)
    val hueTealWash = Color(0xFFF0FDFA)
    val hueTealLine = Color(0xFF99F6E4)
    val hueCyan = Color(0xFF06B6D4)
    val hueCyanFg = Color(0xFF0E7490)
    val hueCyanWash = Color(0xFFECFEFF)
    val hueCyanLine = Color(0xFFA5F3FC)
    val hueSky = Color(0xFF0EA5E9)
    val hueSkyFg = Color(0xFF0369A1)
    val hueSkyWash = Color(0xFFF0F9FF)
    val hueSkyLine = Color(0xFFBAE6FD)
    val hueBlue = Color(0xFF3B82F6)
    val hueBlueFg = Color(0xFF1D4ED8)
    val hueBlueWash = Color(0xFFEFF6FF)
    val hueBlueLine = Color(0xFFBFDBFE)
    val hueIndigo = Color(0xFF6366F1)
    val hueIndigoFg = Color(0xFF4338CA)
    val hueIndigoWash = Color(0xFFEEF2FF)
    val hueIndigoLine = Color(0xFFC7D2FE)
    val hueViolet = Color(0xFF8B5CF6)
    val hueVioletFg = Color(0xFF6D28D9)
    val hueVioletWash = Color(0xFFF5F3FF)
    val hueVioletLine = Color(0xFFDDD6FE)
    val huePink = Color(0xFFEC4899)
    val huePinkFg = Color(0xFFBE185D)
    val huePinkWash = Color(0xFFFDF2F8)
    val huePinkLine = Color(0xFFFBCFE8)
    val hueGray = Color(0xFF6B7280)
    val hueGrayFg = Color(0xFF374151)
    val hueGrayWash = Color(0xFFF9FAFB)
    val hueGrayLine = Color(0xFFE5E7EB)
}

/** PROVISIONAL dark theme, same names as VVColor. Switched on nowhere yet. */
object VVColorDark {
    val surface = Color(0xFF111827)
    val surfaceSubtle = Color(0xFFFFFFFF).copy(alpha = 0.03f)
    val surfaceMuted = Color(0xFFFFFFFF).copy(alpha = 0.06f)
    val surfaceBackdrop = Color(0xFF030712)
    val surfaceGlass = Color(0xFF111827).copy(alpha = 0.82f)
    val fg = Color(0xFFF9FAFB)
    val fgSecondary = Color(0xFFD1D5DB)
    val fgMuted = Color(0xFF9CA3AF)
    val fgSubtle = Color(0xFF6B7280)
    val fgInverse = Color(0xFF111827)
    val fgLink = Color(0xFF60A5FA)
    val line = Color(0xFF374151)
    val lineSubtle = Color(0xFF1F2937)
    val brand = Color(0xFF78D870)
    val admin = Color(0xFFB4881B)
    val danger = Color(0xFFF87171)
    val dangerStrong = Color(0xFFFCA5A5)
    val dangerBright = Color(0xFFEF4444)
    val dangerWash = Color(0xFF450A0A)
    val dangerLine = Color(0xFF7F1D1D)
    val warning = Color(0xFFFBBF24)
    val warningStrong = Color(0xFFFCD34D)
    val warningBright = Color(0xFFF59E0B)
    val warningWash = Color(0xFF451A03)
    val warningLine = Color(0xFF78350F)
    val success = Color(0xFF4ADE80)
    val successStrong = Color(0xFF86EFAC)
    val successBright = Color(0xFF22C55E)
    val successWash = Color(0xFF052E16)
    val successLine = Color(0xFF14532D)
    val info = Color(0xFF60A5FA)
    val infoStrong = Color(0xFF93C5FD)
    val infoBright = Color(0xFF3B82F6)
    val infoWash = Color(0xFF172554)
    val infoLine = Color(0xFF1E3A8A)
    val hueRed = Color(0xFFF87171)
    val hueRedFg = Color(0xFFFCA5A5)
    val hueRedWash = Color(0xFF450A0A)
    val hueRedLine = Color(0xFF991B1B)
    val hueOrange = Color(0xFFFB923C)
    val hueOrangeFg = Color(0xFFFDBA74)
    val hueOrangeWash = Color(0xFF431407)
    val hueOrangeLine = Color(0xFF9A3412)
    val hueAmber = Color(0xFFFBBF24)
    val hueAmberFg = Color(0xFFFCD34D)
    val hueAmberWash = Color(0xFF451A03)
    val hueAmberLine = Color(0xFF92400E)
    val hueYellow = Color(0xFFFACC15)
    val hueYellowFg = Color(0xFFFDE047)
    val hueYellowWash = Color(0xFF422006)
    val hueYellowLine = Color(0xFF854D0E)
    val hueGreen = Color(0xFF4ADE80)
    val hueGreenFg = Color(0xFF86EFAC)
    val hueGreenWash = Color(0xFF052E16)
    val hueGreenLine = Color(0xFF166534)
    val hueTeal = Color(0xFF2DD4BF)
    val hueTealFg = Color(0xFF5EEAD4)
    val hueTealWash = Color(0xFF042F2E)
    val hueTealLine = Color(0xFF115E59)
    val hueCyan = Color(0xFF22D3EE)
    val hueCyanFg = Color(0xFF67E8F9)
    val hueCyanWash = Color(0xFF083344)
    val hueCyanLine = Color(0xFF155E75)
    val hueSky = Color(0xFF38BDF8)
    val hueSkyFg = Color(0xFF7DD3FC)
    val hueSkyWash = Color(0xFF082F49)
    val hueSkyLine = Color(0xFF075985)
    val hueBlue = Color(0xFF60A5FA)
    val hueBlueFg = Color(0xFF93C5FD)
    val hueBlueWash = Color(0xFF172554)
    val hueBlueLine = Color(0xFF1E40AF)
    val hueIndigo = Color(0xFF818CF8)
    val hueIndigoFg = Color(0xFFA5B4FC)
    val hueIndigoWash = Color(0xFF1E1B4B)
    val hueIndigoLine = Color(0xFF3730A3)
    val hueViolet = Color(0xFFA78BFA)
    val hueVioletFg = Color(0xFFC4B5FD)
    val hueVioletWash = Color(0xFF2E1065)
    val hueVioletLine = Color(0xFF5B21B6)
    val huePink = Color(0xFFF472B6)
    val huePinkFg = Color(0xFFF9A8D4)
    val huePinkWash = Color(0xFF500724)
    val huePinkLine = Color(0xFF9D174D)
    val hueGray = Color(0xFF9CA3AF)
    val hueGrayFg = Color(0xFFD1D5DB)
    val hueGrayWash = Color(0xFF030712)
    val hueGrayLine = Color(0xFF1F2937)
}

/** A built-in type's colours: `base` for its chip and glyph, `fg` for text in its hue, `wash` behind it. */
data class VVSwatch(val base: Color, val fg: Color, val wash: Color)

/** The default colour of each built-in type. A space may override one. */
object VVTypeColor {
    val space = VVSwatch(Color(0xFF78D870), Color(0xFF2F7A3E), Color(0xFFEAF9EC))
    val subspace = VVSwatch(Color(0xFFA8E6A2), Color(0xFF2F7A3E), Color(0xFFEAF9EC))
    val person = VVSwatch(Color(0xFF60A5FA), Color(0xFF1D4ED8), Color(0xFFEFF6FF))
    val event = VVSwatch(Color(0xFFFB7185), Color(0xFFBE123C), Color(0xFFFFF1F2))
    val resource = VVSwatch(Color(0xFFFB923C), Color(0xFFC2410C), Color(0xFFFFF7ED))
    val index = VVSwatch(Color(0xFFFACC15), Color(0xFFA16207), Color(0xFFFEFCE8))
    val section = VVSwatch(Color(0xFF38BDF8), Color(0xFF0369A1), Color(0xFFF0F9FF))
    val channel = VVSwatch(Color(0xFFF472B6), Color(0xFFBE185D), Color(0xFFFDF2F8))
    val connector = VVSwatch(Color(0xFF818CF8), Color(0xFF4338CA), Color(0xFFEEF2FF))
    val agent = VVSwatch(Color(0xFF2DD4BF), Color(0xFF0F766E), Color(0xFFF0FDFA))
    val tool = VVSwatch(Color(0xFFE879F9), Color(0xFFA21CAF), Color(0xFFFDF4FF))
    val model = VVSwatch(Color(0xFFA78BFA), Color(0xFF6D28D9), Color(0xFFF5F3FF))
    val other = VVSwatch(Color(0xFF9CA3AF), Color(0xFF4B5563), Color(0xFFF9FAFB))

    /** A type by the name a node carries (`Person`, `space`…); `other` when it is not built in. */
    fun named(name: String): VVSwatch = when (name.lowercase()) {
        "space" -> space
        "subspace" -> subspace
        "person" -> person
        "event" -> event
        "resource" -> resource
        "index" -> index
        "section" -> section
        "channel" -> channel
        "connector" -> connector
        "agent" -> agent
        "tool" -> tool
        "model" -> model
        else -> other
    }
}

/** PROVISIONAL dark type colours. */
object VVTypeColorDark {
    val space = VVSwatch(Color(0xFF78D870), Color(0xFFA8E6A2), Color(0xFF0F2915))
    val subspace = VVSwatch(Color(0xFFA8E6A2), Color(0xFFA8E6A2), Color(0xFF0F2915))
    val person = VVSwatch(Color(0xFF60A5FA), Color(0xFF93C5FD), Color(0xFF172554))
    val event = VVSwatch(Color(0xFFFB7185), Color(0xFFFDA4AF), Color(0xFF4C0519))
    val resource = VVSwatch(Color(0xFFFB923C), Color(0xFFFDBA74), Color(0xFF431407))
    val index = VVSwatch(Color(0xFFFACC15), Color(0xFFFDE047), Color(0xFF422006))
    val section = VVSwatch(Color(0xFF38BDF8), Color(0xFF7DD3FC), Color(0xFF082F49))
    val channel = VVSwatch(Color(0xFFF472B6), Color(0xFFF9A8D4), Color(0xFF500724))
    val connector = VVSwatch(Color(0xFF818CF8), Color(0xFFA5B4FC), Color(0xFF1E1B4B))
    val agent = VVSwatch(Color(0xFF2DD4BF), Color(0xFF5EEAD4), Color(0xFF042F2E))
    val tool = VVSwatch(Color(0xFFE879F9), Color(0xFFF0ABFC), Color(0xFF4A044E))
    val model = VVSwatch(Color(0xFFA78BFA), Color(0xFFC4B5FD), Color(0xFF2E1065))
    val other = VVSwatch(Color(0xFF9CA3AF), Color(0xFFD1D5DB), Color(0xFF1F2937))

    /** A type by the name a node carries (`Person`, `space`…); `other` when it is not built in. */
    fun named(name: String): VVSwatch = when (name.lowercase()) {
        "space" -> space
        "subspace" -> subspace
        "person" -> person
        "event" -> event
        "resource" -> resource
        "index" -> index
        "section" -> section
        "channel" -> channel
        "connector" -> connector
        "agent" -> agent
        "tool" -> tool
        "model" -> model
        else -> other
    }
}

/** One accent in one theme: `base` for fills and the selected state, `strong` for text and icons, `soft` behind a selected row. */
data class VVAccentSet(val base: Color, val strong: Color, val soft: Color)

/** A hue a person picks from in Settings. The id is what is stored. */
data class VVAccent(val id: String, val name: String, val light: VVAccentSet, val dark: VVAccentSet)

object VVAccents {
    val all: List<VVAccent> = listOf(
        VVAccent("green", "Green", VVAccentSet(Color(0xFF78D870), Color(0xFF2F7A3E), Color(0xFFEAF9EC)), VVAccentSet(Color(0xFF78D870), Color(0xFFA8E6A2), Color(0xFF0F2915))),
        VVAccent("blue", "Blue", VVAccentSet(Color(0xFF60A5FA), Color(0xFF1D4ED8), Color(0xFFEFF6FF)), VVAccentSet(Color(0xFF60A5FA), Color(0xFF93C5FD), Color(0xFF172554))),
        VVAccent("purple", "Purple", VVAccentSet(Color(0xFFA78BFA), Color(0xFF6D28D9), Color(0xFFF5F3FF)), VVAccentSet(Color(0xFFA78BFA), Color(0xFFC4B5FD), Color(0xFF2E1065))),
        VVAccent("rose", "Rose", VVAccentSet(Color(0xFFF87171), Color(0xFFB91C1C), Color(0xFFFFF1F2)), VVAccentSet(Color(0xFFF87171), Color(0xFFFCA5A5), Color(0xFF4C0519))),
        VVAccent("orange", "Orange", VVAccentSet(Color(0xFFFB923C), Color(0xFF9A3412), Color(0xFFFFF7ED)), VVAccentSet(Color(0xFFFB923C), Color(0xFFFDBA74), Color(0xFF431407))),
        VVAccent("yellow", "Yellow", VVAccentSet(Color(0xFFFACC15), Color(0xFF854D0E), Color(0xFFFEFCE8)), VVAccentSet(Color(0xFFFACC15), Color(0xFFFDE047), Color(0xFF422006))),
        VVAccent("teal", "Teal", VVAccentSet(Color(0xFF2DD4BF), Color(0xFF0F766E), Color(0xFFF0FDFA)), VVAccentSet(Color(0xFF2DD4BF), Color(0xFF5EEAD4), Color(0xFF042F2E))),
        VVAccent("pink", "Pink", VVAccentSet(Color(0xFFF472B6), Color(0xFFBE185D), Color(0xFFFDF2F8)), VVAccentSet(Color(0xFFF472B6), Color(0xFFF9A8D4), Color(0xFF500724))),
        VVAccent("indigo", "Indigo", VVAccentSet(Color(0xFF818CF8), Color(0xFF3730A3), Color(0xFFEEF2FF)), VVAccentSet(Color(0xFF818CF8), Color(0xFFA5B4FC), Color(0xFF1E1B4B))),
    )

    val default: VVAccent get() = all.first()

    fun named(id: String?): VVAccent = all.firstOrNull { it.id == id } ?: default
}

/** Spacing, named like Tailwind: `x4` is `p-4` is 16.dp. */
object VVSpace {
    val x0 = 0.dp
    val px = 1.dp
    val x0_5 = 2.dp
    val x1 = 4.dp
    val x1_5 = 6.dp
    val x2 = 8.dp
    val x2_5 = 10.dp
    val x3 = 12.dp
    val x3_5 = 14.dp
    val x4 = 16.dp
    val x5 = 20.dp
    val x6 = 24.dp
    val x8 = 32.dp
    val x10 = 40.dp
    val x12 = 48.dp
    val x16 = 64.dp
}

/** Corner radius. */
object VVRadius {
    val none = 0.dp
    val xs = 2.dp
    val sm = 4.dp
    val md = 6.dp
    val lg = 8.dp
    val xl = 12.dp
    val xl2 = 16.dp
    val xl3 = 24.dp
    val full = 9999.dp
}

/** Font size, named by size. */
object VVFontSize {
    val s10 = 10.sp
    val s11 = 11.sp
    val s12 = 12.sp
    val s13 = 13.sp
    val s14 = 14.sp
    val s15 = 15.sp
    val s16 = 16.sp
    val s18 = 18.sp
    val s20 = 20.sp
    val s24 = 24.sp
    val s30 = 30.sp
    val s36 = 36.sp
    val s48 = 48.sp
    val s60 = 60.sp
}

object VVFontWeight {
    val light = FontWeight(300)
    val regular = FontWeight(400)
    val medium = FontWeight(500)
    val semibold = FontWeight(600)
    val bold = FontWeight(700)
}

/** Durations in milliseconds, and the curves they run on. */
object VVMotion {
    /** Hover and colour changes. */
    const val fast = 150
    /** Something closing. */
    const val quick = 200
    /** Tabs, the rail, a panel moving. */
    const val base = 300
    /** A view arriving. */
    const val slow = 380
    /** A whole tab set changing. */
    const val slower = 550

    /** Things moving between two places. */
    val standard = CubicBezierEasing(0.4f, 0f, 0.2f, 1f)
    /** Things arriving: fast out, long settle. */
    val enter = CubicBezierEasing(0.22f, 1f, 0.36f, 1f)
    /** The shell and rail resizing (CSS `ease`). */
    val gentle = CubicBezierEasing(0.25f, 0.1f, 0.25f, 1f)
    /** A dragged row landing. */
    val settle = CubicBezierEasing(0.25f, 1f, 0.5f, 1f)
    /** A small spring past the mark. */
    val overshoot = CubicBezierEasing(0.34f, 1.56f, 0.64f, 1f)
}
