'use client';

// People & access → Members: the hub view. Every member row carries their
// community role, team membership, and effective context access in one line;
// expanding a row exposes full per-person control — team assignment, direct
// grants (add / change level / revoke), and what flows in via teams or
// community-wide grants.

import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, Plus, UserPlus, X } from 'lucide-react';
import {
  Alert,
  Avatar,
  Button,
  ConfirmDialog,
  Field,
  Input,
  SearchInput,
  SettingsSection,
} from '@/components/ui';
import Select from '@/components/ui/Select';
import Dropdown from '@/components/ui/Dropdown';
import { useConsoleAction } from '@/components/console/ConsoleSaveContext';
import { fetchJson, fetchJsonBody } from '@/lib/fetchJson';
import { notesApi } from '@/features/notes/lib/notesApi';
import { effectiveLevel } from '@/lib/notes/shared/authz';
import {
  accessOfMember,
  levelLabel,
  pathLabel,
  summarizeAccess,
  GrantEditor,
  type CommunityMember,
  type PeopleData,
} from './shared';

interface Props {
  communityId: string;
  data: PeopleData;
  busy: boolean;
  run: (fn: () => Promise<unknown>) => Promise<void>;
}

/**
 * Reusable invite link for the community. Admins copy it to share; regenerating
 * revokes the old link. Lazily generated by GET /invite the first time.
 */
function InviteLinkRow({ communityId }: { communityId: string }) {
  const [url, setUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const runAction = useConsoleAction();

  useEffect(() => {
    let alive = true;
    fetch(`/api/communities/${communityId}/invite`)
      .then((r) => r.json())
      .then((d) => { if (alive) setUrl(d.url ?? ''); })
      .catch(() => { if (alive) setUrl(''); });
    return () => { alive = false; };
  }, [communityId]);

  const copy = async () => {
    if (!url) return;
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };

  const regenerate = async () => {
    setConfirmRegenerate(false);
    try {
      await runAction(async () => {
        const data = await fetchJson<{ url?: string }>(`/api/communities/${communityId}/invite`, { method: 'POST' });
        setUrl(data.url ?? '');
      });
    } catch { /* status pill shows the failure */ }
  };

  return (
    <div>
      <div className="flex items-center gap-2">
        <input
          readOnly
          value={url === null ? 'Loading…' : url}
          className="min-w-0 flex-1 truncate rounded-xl border border-transparent bg-surface-2 px-3.5 py-2.5 text-xs text-text-secondary"
        />
        <Button variant="pill-secondary" onClick={copy} disabled={!url}>
          {copied ? 'Copied' : 'Copy'}
        </Button>
      </div>
      <div className="mt-2 flex items-center justify-between">
        <p className="text-xs text-text-muted">
          New joiners appear below as pending requests for you to approve.
        </p>
        <button
          type="button"
          onClick={() => setConfirmRegenerate(true)}
          disabled={url === null}
          className="text-xs font-medium text-text-muted transition-colors hover:text-text-primary disabled:opacity-50"
        >
          Regenerate
        </button>
      </div>

      <ConfirmDialog
        open={confirmRegenerate}
        title="Regenerate invite link"
        body="The current link will stop working immediately. Anyone holding the old link won't be able to join with it."
        confirmLabel="Regenerate"
        onConfirm={regenerate}
        onClose={() => setConfirmRegenerate(false)}
      />
    </div>
  );
}

function InviteModal({ communityId, onDone, onClose }: {
  communityId: string;
  onDone: () => Promise<void>;
  onClose: () => void;
}) {
  const [email, setEmail] = useState('');
  const [role, setRole] = useState<'member' | 'admin'>('member');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await fetchJsonBody(`/api/communities/${communityId}/members`, 'POST', {
        email: email.trim(),
        role,
      });
      await onDone();
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to add member');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative w-full max-w-sm space-y-4 rounded-2xl border border-border-subtle bg-surface-1 p-6 shadow-float">
        <div className="flex items-center justify-between">
          <h2 className="font-ginto text-base font-medium text-text-primary">Invite member</h2>
          <button onClick={onClose} className="text-text-muted transition-colors hover:text-text-primary" aria-label="Close">
            <X className="h-5 w-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <Field label="Email address">
            <Input
              type="email"
              required
              autoFocus
              placeholder="user@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </Field>
          <Field label="Role">
            <Select value={role} onChange={(e) => setRole(e.target.value as 'member' | 'admin')}>
              <option value="member">Member</option>
              <option value="admin">Admin</option>
            </Select>
          </Field>
          {error && <Alert variant="error" inline>{error}</Alert>}
          <div className="flex gap-2 pt-1">
            <Button type="button" variant="pill-secondary" onClick={onClose} className="flex-1">
              Cancel
            </Button>
            <Button type="submit" variant="pill-primary" loading={loading} loadingText="Inviting…" className="flex-1">
              Invite
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}

/** The expanded per-member access editor under a member row. */
function MemberDetail({ communityId, member, data, busy, run }: {
  communityId: string;
  member: CommunityMember;
  data: PeopleData;
  busy: boolean;
  run: Props['run'];
}) {
  const [teamMenuOpen, setTeamMenuOpen] = useState(false);

  const myTeams = data.teams.filter((t) => t.members.some((m) => m.userId === member.userId));
  const joinable = data.teams.filter((t) => !t.members.some((m) => m.userId === member.userId));
  const direct = (data.overview?.grants ?? []).filter(
    (g) => g.subjectType === 'user' && g.subjectId === member.userId,
  );
  const inherited = (data.overview?.grants ?? []).filter(
    (g) =>
      g.subjectType === 'community' ||
      (g.subjectType === 'team' && myTeams.some((t) => t.id === g.subjectId)),
  );
  const access = accessOfMember(member.userId, data.teams, data.overview);

  return (
    <div className="space-y-5 rounded-xl bg-surface-2/60 px-4 py-4">
      {member.role === 'admin' && (
        <p className="text-xs text-text-muted">
          Community admins bypass all grants — {member.user.name} already has full access to the
          entire context.
        </p>
      )}

      {/* Teams */}
      <div>
        <h5 className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-text-muted">Teams</h5>
        <div className="flex flex-wrap items-center gap-1.5">
          {myTeams.map((team) => (
            <span
              key={team.id}
              className="inline-flex items-center gap-1 rounded-full bg-surface-1 py-0.5 pl-2.5 pr-1 text-xs font-medium text-text-secondary ring-1 ring-border-subtle"
            >
              {team.name}
              <button
                type="button"
                title={`Remove from ${team.name}`}
                disabled={busy}
                onClick={() =>
                  void run(() =>
                    notesApi.teamAction(communityId, {
                      action: 'removeMember',
                      teamId: team.id,
                      userId: member.userId,
                    }),
                  )
                }
                className="rounded-full p-0.5 text-text-muted transition hover:text-red-500 disabled:opacity-40"
              >
                <X className="h-3 w-3" />
              </button>
            </span>
          ))}
          {joinable.length > 0 && (
            <div className="relative">
              <button
                type="button"
                disabled={busy}
                onClick={() => setTeamMenuOpen((o) => !o)}
                className="inline-flex items-center gap-1 rounded-full border border-dashed border-border-default px-2.5 py-0.5 text-xs font-medium text-text-muted transition hover:text-text-primary disabled:opacity-40"
              >
                <Plus className="h-3 w-3" /> Add to team
              </button>
              {teamMenuOpen && (
                <div className="absolute left-0 top-full z-50 mt-1 min-w-[180px] overflow-hidden rounded-xl border border-border-subtle bg-surface-1 py-1 shadow-xl">
                  {joinable.map((team) => (
                    <button
                      key={team.id}
                      type="button"
                      onClick={() => {
                        setTeamMenuOpen(false);
                        void run(() =>
                          notesApi.teamAction(communityId, {
                            action: 'setMember',
                            teamId: team.id,
                            userId: member.userId,
                            role: 'member',
                          }),
                        );
                      }}
                      className="block w-full px-3 py-1.5 text-left text-sm text-text-secondary transition-colors hover:bg-surface-2"
                    >
                      {team.name}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}
          {myTeams.length === 0 && joinable.length === 0 && (
            <span className="text-xs text-text-muted">No teams yet — create one in the Teams tab.</span>
          )}
        </div>
      </div>

      {/* Direct grants — fully editable */}
      <div>
        <h5 className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-text-muted">
          Direct access
        </h5>
        <GrantEditor
          communityId={communityId}
          subjectType="user"
          subjectId={member.userId}
          grants={direct}
          paths={data.paths}
          contextName={data.contextName}
          busy={busy}
          run={run}
          emptyText="No direct grants — access comes from teams or community-wide grants."
          placeholder="Give access to…"
          addLabel="Add"
        />
      </div>

      {/* Inherited access — read-only, with source */}
      {inherited.length > 0 && member.role !== 'admin' && (
        <div>
          <h5 className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-text-muted">
            Via teams &amp; everyone
          </h5>
          <div className="space-y-0.5">
            {inherited.map((grant) => (
              <div key={grant.id} className="flex items-center gap-2.5 px-1 py-1 text-sm">
                <span className="min-w-0 flex-1 truncate text-text-primary">{pathLabel(grant.resourcePath, data.contextName)}</span>
                <span className="shrink-0 text-xs text-text-muted">
                  via {grant.subjectType === 'community' ? 'everyone' : grant.subjectName}
                </span>
                <span className="w-20 shrink-0 text-right text-xs font-medium text-text-secondary">
                  {levelLabel(grant.level)}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Effective summary */}
      {member.role !== 'admin' && (
        <p className="text-xs text-text-muted">
          Effective access: <span className="font-medium text-text-secondary">{summarizeAccess(member.role, access)}</span>
          {effectiveLevel(access, '') === 0 && access.grants.length > 0 && (
            <> — no grant reaches the context root, so they only see the areas listed above.</>
          )}
        </p>
      )}
    </div>
  );
}

export default function PeopleTab({ communityId, data, busy, run }: Props) {
  const [showInvite, setShowInvite] = useState(false);
  const [query, setQuery] = useState('');
  const [expanded, setExpanded] = useState<string | null>(null);
  const [confirm, setConfirm] = useState<{ kind: 'remove' | 'deny'; userId: string; name: string } | null>(null);

  const pending = useMemo(() => data.members.filter((m) => m.status === 'pending'), [data.members]);
  const active = useMemo(() => data.members.filter((m) => m.status !== 'pending'), [data.members]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return active;
    return active.filter(
      (m) => m.user.name.toLowerCase().includes(q) || m.user.email.toLowerCase().includes(q),
    );
  }, [active, query]);

  // Teams + effective-access summary per member, computed once per data load
  // instead of per row per render (search keystrokes, expands).
  const memberInfo = useMemo(() => {
    const map = new Map<string, { teams: PeopleData['teams']; summary: string }>();
    for (const m of data.members) {
      map.set(m.userId, {
        teams: data.teams.filter((t) => t.members.some((tm) => tm.userId === m.userId)),
        summary: summarizeAccess(m.role, accessOfMember(m.userId, data.teams, data.overview)),
      });
    }
    return map;
  }, [data.members, data.teams, data.overview]);

  const updateRole = (userId: string, role: string) =>
    run(() => fetchJsonBody(`/api/communities/${communityId}/members/${userId}`, 'PUT', { role }));

  const approve = (userId: string) =>
    run(() => fetchJsonBody(`/api/communities/${communityId}/members/${userId}`, 'PUT', { status: 'active' }));

  const remove = (userId: string) =>
    run(() => fetchJson(`/api/communities/${communityId}/members/${userId}`, { method: 'DELETE' }));

  return (
    <div className="space-y-8">
      <SettingsSection
        title="Invite people"
        description="Share the invite link, or add someone directly by email."
        action={
          <Button variant="pill-primary" onClick={() => setShowInvite(true)}>
            <span className="inline-flex items-center gap-1.5">
              <UserPlus size={14} />
              Invite member
            </span>
          </Button>
        }
      >
        <InviteLinkRow communityId={communityId} />
      </SettingsSection>

      {pending.length > 0 && (
        <SettingsSection
          title={`Pending requests (${pending.length})`}
          description="People who joined via the invite link, waiting for approval."
        >
          <div className="space-y-3">
            {pending.map((member) => (
              <div key={member.id} className="flex items-center justify-between gap-3">
                <div className="flex min-w-0 items-center gap-3">
                  <Avatar name={member.user.name} imageUrl={member.user.image} size="sm" />
                  <div className="min-w-0">
                    <div className="truncate text-sm font-medium text-text-primary">{member.user.name}</div>
                    <div className="truncate text-xs text-text-muted">{member.user.email}</div>
                  </div>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <Button
                    variant="pill-primary"
                    onClick={() => void approve(member.userId)}
                    disabled={busy}
                    className="!px-3 !py-1.5 !text-xs"
                  >
                    Approve
                  </Button>
                  <Button
                    variant="pill-secondary"
                    onClick={() => setConfirm({ kind: 'deny', userId: member.userId, name: member.user.name })}
                    disabled={busy}
                    className="!px-3 !py-1.5 !text-xs"
                  >
                    Deny
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </SettingsSection>
      )}

      <SettingsSection
        title={`Members (${active.length})`}
        description="Role, teams, and context access for everyone — expand a member to manage their individual permissions."
      >
        <div className="space-y-4">
          {active.length > 3 && (
            <SearchInput value={query} onChange={setQuery} placeholder="Search members…" />
          )}

          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border-subtle text-left">
                  <th className="pb-3 pr-4 text-xs font-semibold uppercase tracking-wider text-text-muted">Member</th>
                  <th className="pb-3 pr-4 text-xs font-semibold uppercase tracking-wider text-text-muted">Role</th>
                  <th className="pb-3 pr-4 text-xs font-semibold uppercase tracking-wider text-text-muted">Teams</th>
                  <th className="pb-3 pr-4 text-xs font-semibold uppercase tracking-wider text-text-muted">Context access</th>
                  <th className="pb-3 text-xs font-semibold uppercase tracking-wider text-text-muted"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border-subtle">
                {filtered.map((member) => {
                  const info = memberInfo.get(member.userId);
                  const isOpen = expanded === member.userId;
                  return (
                    <MemberRows
                      key={member.id}
                      member={member}
                      memberTeams={info?.teams ?? []}
                      summary={info?.summary ?? ''}
                      isOpen={isOpen}
                      busy={busy}
                      onToggle={() => setExpanded(isOpen ? null : member.userId)}
                      onRole={(role) => { if (role !== member.role) void updateRole(member.userId, role); }}
                      onRemove={() => setConfirm({ kind: 'remove', userId: member.userId, name: member.user.name })}
                      detail={
                        isOpen ? (
                          <MemberDetail
                            communityId={communityId}
                            member={member}
                            data={data}
                            busy={busy}
                            run={run}
                          />
                        ) : null
                      }
                    />
                  );
                })}
                {filtered.length === 0 && (
                  <tr>
                    <td colSpan={5} className="py-8 text-center text-sm text-text-muted">
                      {query ? 'No members match your search' : 'No members yet'}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </SettingsSection>

      <ConfirmDialog
        open={confirm !== null}
        title={confirm?.kind === 'deny' ? 'Deny join request' : 'Remove member'}
        body={
          confirm?.kind === 'deny' ? (
            <>Deny <span className="font-semibold">{confirm?.name}</span>&apos;s request to join?</>
          ) : (
            <>Remove <span className="font-semibold">{confirm?.name}</span> from this community? Their direct grants and team memberships go with them.</>
          )
        }
        confirmLabel={confirm?.kind === 'deny' ? 'Deny' : 'Remove'}
        destructive
        onConfirm={async () => {
          if (!confirm) return;
          const { userId } = confirm;
          setConfirm(null);
          await remove(userId);
        }}
        onClose={() => setConfirm(null)}
      />

      {showInvite && (
        <InviteModal
          communityId={communityId}
          onDone={async () => run(async () => {})}
          onClose={() => setShowInvite(false)}
        />
      )}
    </div>
  );
}

/** A member's main row + (when expanded) its detail row. */
function MemberRows({ member, memberTeams, summary, isOpen, busy, onToggle, onRole, onRemove, detail }: {
  member: CommunityMember;
  memberTeams: Array<{ id: string; name: string }>;
  summary: string;
  isOpen: boolean;
  busy: boolean;
  onToggle: () => void;
  onRole: (role: string) => void;
  onRemove: () => void;
  detail: React.ReactNode;
}) {
  return (
    <>
      <tr className="transition hover:bg-surface-2">
        <td className="cursor-pointer py-3 pr-4" onClick={onToggle}>
          <div className="flex items-center gap-3">
            <Avatar name={member.user.name} imageUrl={member.user.image} size="sm" />
            <div className="min-w-0">
              <div className="truncate font-medium text-text-primary">{member.user.name}</div>
              <div className="truncate text-xs text-text-muted">{member.user.email}</div>
            </div>
          </div>
        </td>
        <td className="py-3 pr-4">
          <Dropdown
            value={member.role}
            options={[
              { value: 'member', label: 'Member' },
              { value: 'admin', label: 'Admin' },
            ]}
            onChange={onRole}
            active={member.role === 'admin'}
            menuWidthClass="min-w-[130px]"
          />
        </td>
        <td className="cursor-pointer py-3 pr-4" onClick={onToggle}>
          {memberTeams.length === 0 ? (
            <span className="text-xs text-text-muted">—</span>
          ) : (
            <div className="flex flex-wrap gap-1">
              {memberTeams.slice(0, 3).map((t) => (
                <span
                  key={t.id}
                  className="rounded-full bg-surface-2 px-2 py-0.5 text-[11px] font-medium text-text-secondary"
                >
                  {t.name}
                </span>
              ))}
              {memberTeams.length > 3 && (
                <span className="rounded-full bg-surface-2 px-2 py-0.5 text-[11px] font-medium text-text-muted">
                  +{memberTeams.length - 3}
                </span>
              )}
            </div>
          )}
        </td>
        <td className="cursor-pointer py-3 pr-4 text-xs text-text-secondary" onClick={onToggle}>
          {summary}
        </td>
        <td className="py-3 text-right">
          <div className="flex items-center justify-end gap-2">
            <Button variant="pill-danger" onClick={onRemove} disabled={busy} className="!px-3 !py-1.5 !text-xs">
              Remove
            </Button>
            <button
              type="button"
              onClick={onToggle}
              aria-label={isOpen ? 'Collapse member' : 'Expand member'}
              className="rounded p-1 text-text-muted transition hover:text-text-primary"
            >
              <ChevronDown className={`h-4 w-4 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
            </button>
          </div>
        </td>
      </tr>
      {isOpen && (
        <tr>
          <td colSpan={5} className="pb-4 pt-1">
            {detail}
          </td>
        </tr>
      )}
    </>
  );
}
