// Generated by packages/tokens from its DTCG source. Do not edit.
// Change a token in packages/tokens/tokens/, then run `pnpm tokens:build`.

import SwiftUI
import UIKit

private extension UIColor {
    convenience init(vv r: Int, _ g: Int, _ b: Int, _ a: Double) {
        self.init(red: CGFloat(r) / 255, green: CGFloat(g) / 255, blue: CGFloat(b) / 255, alpha: a)
    }
}

/// A colour that follows the appearance between its light and dark value. The
/// app pins itself light, so today every one of these is its light value.
private func vvColor(_ light: UIColor, _ dark: UIColor) -> Color {
    Color(UIColor { $0.userInterfaceStyle == .dark ? dark : light })
}

/// Semantic colours. Paint with these, never a literal. The accent is not here:
/// it is the person's choice, a `VVAccent` held by the theme store.
enum VVColor {
    /// The one opaque surface: the page, floats, inputs.
    static let surface = vvColor(UIColor(vv: 255, 255, 255, 1), UIColor(vv: 17, 24, 39, 1))
    /// A quiet fill: a neutral button, a selected row. Tints what it sits on.
    static let surfaceSubtle = vvColor(UIColor(vv: 17, 24, 39, 0.025), UIColor(vv: 255, 255, 255, 0.03))
    /// Hover, and the fill one step louder than subtle.
    static let surfaceMuted = vvColor(UIColor(vv: 17, 24, 39, 0.05), UIColor(vv: 255, 255, 255, 0.06))
    /// What the whole app sits on.
    static let surfaceBackdrop = vvColor(UIColor(vv: 255, 255, 255, 1), UIColor(vv: 3, 7, 18, 1))
    /// Chrome over moving content, under a blur.
    static let surfaceGlass = vvColor(UIColor(vv: 255, 255, 255, 0.82), UIColor(vv: 17, 24, 39, 0.82))
    /// Body text, titles, icons that matter.
    static let fg = vvColor(UIColor(vv: 17, 24, 39, 1), UIColor(vv: 249, 250, 251, 1))
    static let fgSecondary = vvColor(UIColor(vv: 55, 65, 81, 1), UIColor(vv: 209, 213, 219, 1))
    /// Metadata, labels, the `·` state line.
    static let fgMuted = vvColor(UIColor(vv: 75, 85, 99, 1), UIColor(vv: 156, 163, 175, 1))
    /// Placeholders and disabled text only: below AA for reading.
    static let fgSubtle = vvColor(UIColor(vv: 156, 163, 175, 1), UIColor(vv: 107, 114, 128, 1))
    /// Text on a filled accent or danger control.
    static let fgInverse = vvColor(UIColor(vv: 255, 255, 255, 1), UIColor(vv: 17, 24, 39, 1))
    /// Links in content are the web's blue, never the accent.
    static let fgLink = vvColor(UIColor(vv: 37, 99, 235, 1), UIColor(vv: 96, 165, 250, 1))
    /// Input and control borders.
    static let line = vvColor(UIColor(vv: 209, 213, 219, 1), UIColor(vv: 55, 65, 81, 1))
    /// The hairline between sections.
    static let lineSubtle = vvColor(UIColor(vv: 229, 231, 235, 1), UIColor(vv: 31, 41, 55, 1))
    /// The logo green. Fixed: it never follows the chosen accent. Use `accent` for anything a person's accent should repaint.
    static let brand = vvColor(UIColor(vv: 120, 216, 112, 1), UIColor(vv: 120, 216, 112, 1))
    /// The built-in Admin alias, the one alias a space cannot change.
    static let admin = vvColor(UIColor(vv: 180, 136, 27, 1), UIColor(vv: 180, 136, 27, 1))
    /// Error text, a destructive button.
    static let danger = vvColor(UIColor(vv: 220, 38, 38, 1), UIColor(vv: 248, 113, 113, 1))
    /// Hover on a destructive button; emphasised error text.
    static let dangerStrong = vvColor(UIColor(vv: 185, 28, 28, 1), UIColor(vv: 252, 165, 165, 1))
    /// An invalid field's border, a status dot.
    static let dangerBright = vvColor(UIColor(vv: 239, 68, 68, 1), UIColor(vv: 239, 68, 68, 1))
    static let dangerWash = vvColor(UIColor(vv: 254, 242, 242, 1), UIColor(vv: 69, 10, 10, 1))
    static let dangerLine = vvColor(UIColor(vv: 254, 202, 202, 1), UIColor(vv: 127, 29, 29, 1))
    static let warning = vvColor(UIColor(vv: 180, 83, 9, 1), UIColor(vv: 251, 191, 36, 1))
    static let warningStrong = vvColor(UIColor(vv: 146, 64, 14, 1), UIColor(vv: 252, 211, 77, 1))
    static let warningBright = vvColor(UIColor(vv: 245, 158, 11, 1), UIColor(vv: 245, 158, 11, 1))
    static let warningWash = vvColor(UIColor(vv: 255, 251, 235, 1), UIColor(vv: 69, 26, 3, 1))
    static let warningLine = vvColor(UIColor(vv: 253, 230, 138, 1), UIColor(vv: 120, 53, 15, 1))
    static let success = vvColor(UIColor(vv: 21, 128, 61, 1), UIColor(vv: 74, 222, 128, 1))
    static let successStrong = vvColor(UIColor(vv: 22, 101, 52, 1), UIColor(vv: 134, 239, 172, 1))
    static let successBright = vvColor(UIColor(vv: 34, 197, 94, 1), UIColor(vv: 34, 197, 94, 1))
    static let successWash = vvColor(UIColor(vv: 240, 253, 244, 1), UIColor(vv: 5, 46, 22, 1))
    static let successLine = vvColor(UIColor(vv: 187, 247, 208, 1), UIColor(vv: 20, 83, 45, 1))
    static let info = vvColor(UIColor(vv: 29, 78, 216, 1), UIColor(vv: 96, 165, 250, 1))
    static let infoStrong = vvColor(UIColor(vv: 30, 64, 175, 1), UIColor(vv: 147, 197, 253, 1))
    static let infoBright = vvColor(UIColor(vv: 59, 130, 246, 1), UIColor(vv: 59, 130, 246, 1))
    static let infoWash = vvColor(UIColor(vv: 239, 246, 255, 1), UIColor(vv: 23, 37, 84, 1))
    static let infoLine = vvColor(UIColor(vv: 191, 219, 254, 1), UIColor(vv: 30, 58, 138, 1))
    static let hueRed = vvColor(UIColor(vv: 239, 68, 68, 1), UIColor(vv: 248, 113, 113, 1))
    static let hueRedFg = vvColor(UIColor(vv: 185, 28, 28, 1), UIColor(vv: 252, 165, 165, 1))
    static let hueRedWash = vvColor(UIColor(vv: 254, 242, 242, 1), UIColor(vv: 69, 10, 10, 1))
    static let hueRedLine = vvColor(UIColor(vv: 254, 202, 202, 1), UIColor(vv: 153, 27, 27, 1))
    static let hueOrange = vvColor(UIColor(vv: 249, 115, 22, 1), UIColor(vv: 251, 146, 60, 1))
    static let hueOrangeFg = vvColor(UIColor(vv: 194, 65, 12, 1), UIColor(vv: 253, 186, 116, 1))
    static let hueOrangeWash = vvColor(UIColor(vv: 255, 247, 237, 1), UIColor(vv: 67, 20, 7, 1))
    static let hueOrangeLine = vvColor(UIColor(vv: 254, 215, 170, 1), UIColor(vv: 154, 52, 18, 1))
    static let hueAmber = vvColor(UIColor(vv: 245, 158, 11, 1), UIColor(vv: 251, 191, 36, 1))
    static let hueAmberFg = vvColor(UIColor(vv: 180, 83, 9, 1), UIColor(vv: 252, 211, 77, 1))
    static let hueAmberWash = vvColor(UIColor(vv: 255, 251, 235, 1), UIColor(vv: 69, 26, 3, 1))
    static let hueAmberLine = vvColor(UIColor(vv: 253, 230, 138, 1), UIColor(vv: 146, 64, 14, 1))
    static let hueYellow = vvColor(UIColor(vv: 234, 179, 8, 1), UIColor(vv: 250, 204, 21, 1))
    static let hueYellowFg = vvColor(UIColor(vv: 161, 98, 7, 1), UIColor(vv: 253, 224, 71, 1))
    static let hueYellowWash = vvColor(UIColor(vv: 254, 252, 232, 1), UIColor(vv: 66, 32, 6, 1))
    static let hueYellowLine = vvColor(UIColor(vv: 254, 240, 138, 1), UIColor(vv: 133, 77, 14, 1))
    static let hueGreen = vvColor(UIColor(vv: 34, 197, 94, 1), UIColor(vv: 74, 222, 128, 1))
    static let hueGreenFg = vvColor(UIColor(vv: 21, 128, 61, 1), UIColor(vv: 134, 239, 172, 1))
    static let hueGreenWash = vvColor(UIColor(vv: 240, 253, 244, 1), UIColor(vv: 5, 46, 22, 1))
    static let hueGreenLine = vvColor(UIColor(vv: 187, 247, 208, 1), UIColor(vv: 22, 101, 52, 1))
    static let hueTeal = vvColor(UIColor(vv: 20, 184, 166, 1), UIColor(vv: 45, 212, 191, 1))
    static let hueTealFg = vvColor(UIColor(vv: 15, 118, 110, 1), UIColor(vv: 94, 234, 212, 1))
    static let hueTealWash = vvColor(UIColor(vv: 240, 253, 250, 1), UIColor(vv: 4, 47, 46, 1))
    static let hueTealLine = vvColor(UIColor(vv: 153, 246, 228, 1), UIColor(vv: 17, 94, 89, 1))
    static let hueCyan = vvColor(UIColor(vv: 6, 182, 212, 1), UIColor(vv: 34, 211, 238, 1))
    static let hueCyanFg = vvColor(UIColor(vv: 14, 116, 144, 1), UIColor(vv: 103, 232, 249, 1))
    static let hueCyanWash = vvColor(UIColor(vv: 236, 254, 255, 1), UIColor(vv: 8, 51, 68, 1))
    static let hueCyanLine = vvColor(UIColor(vv: 165, 243, 252, 1), UIColor(vv: 21, 94, 117, 1))
    static let hueSky = vvColor(UIColor(vv: 14, 165, 233, 1), UIColor(vv: 56, 189, 248, 1))
    static let hueSkyFg = vvColor(UIColor(vv: 3, 105, 161, 1), UIColor(vv: 125, 211, 252, 1))
    static let hueSkyWash = vvColor(UIColor(vv: 240, 249, 255, 1), UIColor(vv: 8, 47, 73, 1))
    static let hueSkyLine = vvColor(UIColor(vv: 186, 230, 253, 1), UIColor(vv: 7, 89, 133, 1))
    static let hueBlue = vvColor(UIColor(vv: 59, 130, 246, 1), UIColor(vv: 96, 165, 250, 1))
    static let hueBlueFg = vvColor(UIColor(vv: 29, 78, 216, 1), UIColor(vv: 147, 197, 253, 1))
    static let hueBlueWash = vvColor(UIColor(vv: 239, 246, 255, 1), UIColor(vv: 23, 37, 84, 1))
    static let hueBlueLine = vvColor(UIColor(vv: 191, 219, 254, 1), UIColor(vv: 30, 64, 175, 1))
    static let hueIndigo = vvColor(UIColor(vv: 99, 102, 241, 1), UIColor(vv: 129, 140, 248, 1))
    static let hueIndigoFg = vvColor(UIColor(vv: 67, 56, 202, 1), UIColor(vv: 165, 180, 252, 1))
    static let hueIndigoWash = vvColor(UIColor(vv: 238, 242, 255, 1), UIColor(vv: 30, 27, 75, 1))
    static let hueIndigoLine = vvColor(UIColor(vv: 199, 210, 254, 1), UIColor(vv: 55, 48, 163, 1))
    static let hueViolet = vvColor(UIColor(vv: 139, 92, 246, 1), UIColor(vv: 167, 139, 250, 1))
    static let hueVioletFg = vvColor(UIColor(vv: 109, 40, 217, 1), UIColor(vv: 196, 181, 253, 1))
    static let hueVioletWash = vvColor(UIColor(vv: 245, 243, 255, 1), UIColor(vv: 46, 16, 101, 1))
    static let hueVioletLine = vvColor(UIColor(vv: 221, 214, 254, 1), UIColor(vv: 91, 33, 182, 1))
    static let huePink = vvColor(UIColor(vv: 236, 72, 153, 1), UIColor(vv: 244, 114, 182, 1))
    static let huePinkFg = vvColor(UIColor(vv: 190, 24, 93, 1), UIColor(vv: 249, 168, 212, 1))
    static let huePinkWash = vvColor(UIColor(vv: 253, 242, 248, 1), UIColor(vv: 80, 7, 36, 1))
    static let huePinkLine = vvColor(UIColor(vv: 251, 207, 232, 1), UIColor(vv: 157, 23, 77, 1))
    static let hueGray = vvColor(UIColor(vv: 107, 114, 128, 1), UIColor(vv: 156, 163, 175, 1))
    static let hueGrayFg = vvColor(UIColor(vv: 55, 65, 81, 1), UIColor(vv: 209, 213, 219, 1))
    static let hueGrayWash = vvColor(UIColor(vv: 249, 250, 251, 1), UIColor(vv: 3, 7, 18, 1))
    static let hueGrayLine = vvColor(UIColor(vv: 229, 231, 235, 1), UIColor(vv: 31, 41, 55, 1))
}

/// A built-in type's colours: `base` for its chip and glyph, `fg` for text in its hue, `wash` behind it.
struct VVSwatch {
    let base: Color
    let fg: Color
    let wash: Color
}

/// The default colour of each built-in type. A space may override one.
enum VVTypeColor {
    static let space = VVSwatch(
        base: vvColor(UIColor(vv: 120, 216, 112, 1), UIColor(vv: 120, 216, 112, 1)),
        fg: vvColor(UIColor(vv: 47, 122, 62, 1), UIColor(vv: 168, 230, 162, 1)),
        wash: vvColor(UIColor(vv: 234, 249, 236, 1), UIColor(vv: 15, 41, 21, 1))
    )
    static let subspace = VVSwatch(
        base: vvColor(UIColor(vv: 168, 230, 162, 1), UIColor(vv: 168, 230, 162, 1)),
        fg: vvColor(UIColor(vv: 47, 122, 62, 1), UIColor(vv: 168, 230, 162, 1)),
        wash: vvColor(UIColor(vv: 234, 249, 236, 1), UIColor(vv: 15, 41, 21, 1))
    )
    static let person = VVSwatch(
        base: vvColor(UIColor(vv: 96, 165, 250, 1), UIColor(vv: 96, 165, 250, 1)),
        fg: vvColor(UIColor(vv: 29, 78, 216, 1), UIColor(vv: 147, 197, 253, 1)),
        wash: vvColor(UIColor(vv: 239, 246, 255, 1), UIColor(vv: 23, 37, 84, 1))
    )
    static let event = VVSwatch(
        base: vvColor(UIColor(vv: 251, 113, 133, 1), UIColor(vv: 251, 113, 133, 1)),
        fg: vvColor(UIColor(vv: 190, 18, 60, 1), UIColor(vv: 253, 164, 175, 1)),
        wash: vvColor(UIColor(vv: 255, 241, 242, 1), UIColor(vv: 76, 5, 25, 1))
    )
    static let resource = VVSwatch(
        base: vvColor(UIColor(vv: 251, 146, 60, 1), UIColor(vv: 251, 146, 60, 1)),
        fg: vvColor(UIColor(vv: 194, 65, 12, 1), UIColor(vv: 253, 186, 116, 1)),
        wash: vvColor(UIColor(vv: 255, 247, 237, 1), UIColor(vv: 67, 20, 7, 1))
    )
    static let index = VVSwatch(
        base: vvColor(UIColor(vv: 250, 204, 21, 1), UIColor(vv: 250, 204, 21, 1)),
        fg: vvColor(UIColor(vv: 161, 98, 7, 1), UIColor(vv: 253, 224, 71, 1)),
        wash: vvColor(UIColor(vv: 254, 252, 232, 1), UIColor(vv: 66, 32, 6, 1))
    )
    static let section = VVSwatch(
        base: vvColor(UIColor(vv: 56, 189, 248, 1), UIColor(vv: 56, 189, 248, 1)),
        fg: vvColor(UIColor(vv: 3, 105, 161, 1), UIColor(vv: 125, 211, 252, 1)),
        wash: vvColor(UIColor(vv: 240, 249, 255, 1), UIColor(vv: 8, 47, 73, 1))
    )
    static let channel = VVSwatch(
        base: vvColor(UIColor(vv: 244, 114, 182, 1), UIColor(vv: 244, 114, 182, 1)),
        fg: vvColor(UIColor(vv: 190, 24, 93, 1), UIColor(vv: 249, 168, 212, 1)),
        wash: vvColor(UIColor(vv: 253, 242, 248, 1), UIColor(vv: 80, 7, 36, 1))
    )
    static let connector = VVSwatch(
        base: vvColor(UIColor(vv: 129, 140, 248, 1), UIColor(vv: 129, 140, 248, 1)),
        fg: vvColor(UIColor(vv: 67, 56, 202, 1), UIColor(vv: 165, 180, 252, 1)),
        wash: vvColor(UIColor(vv: 238, 242, 255, 1), UIColor(vv: 30, 27, 75, 1))
    )
    static let agent = VVSwatch(
        base: vvColor(UIColor(vv: 45, 212, 191, 1), UIColor(vv: 45, 212, 191, 1)),
        fg: vvColor(UIColor(vv: 15, 118, 110, 1), UIColor(vv: 94, 234, 212, 1)),
        wash: vvColor(UIColor(vv: 240, 253, 250, 1), UIColor(vv: 4, 47, 46, 1))
    )
    static let tool = VVSwatch(
        base: vvColor(UIColor(vv: 232, 121, 249, 1), UIColor(vv: 232, 121, 249, 1)),
        fg: vvColor(UIColor(vv: 162, 28, 175, 1), UIColor(vv: 240, 171, 252, 1)),
        wash: vvColor(UIColor(vv: 253, 244, 255, 1), UIColor(vv: 74, 4, 78, 1))
    )
    static let model = VVSwatch(
        base: vvColor(UIColor(vv: 167, 139, 250, 1), UIColor(vv: 167, 139, 250, 1)),
        fg: vvColor(UIColor(vv: 109, 40, 217, 1), UIColor(vv: 196, 181, 253, 1)),
        wash: vvColor(UIColor(vv: 245, 243, 255, 1), UIColor(vv: 46, 16, 101, 1))
    )
    static let other = VVSwatch(
        base: vvColor(UIColor(vv: 156, 163, 175, 1), UIColor(vv: 156, 163, 175, 1)),
        fg: vvColor(UIColor(vv: 75, 85, 99, 1), UIColor(vv: 209, 213, 219, 1)),
        wash: vvColor(UIColor(vv: 249, 250, 251, 1), UIColor(vv: 31, 41, 55, 1))
    )

    /// A type by the name a node carries (`Person`, `space`…); `other` when it is not built in.
    static func named(_ name: String) -> VVSwatch {
        switch name.lowercased() {
        case "space": return space
        case "subspace": return subspace
        case "person": return person
        case "event": return event
        case "resource": return resource
        case "index": return index
        case "section": return section
        case "channel": return channel
        case "connector": return connector
        case "agent": return agent
        case "tool": return tool
        case "model": return model
        default: return other
        }
    }
}

/// A hue a person picks from in Settings. The id is what is stored.
struct VVAccent: Identifiable, Hashable {
    let id: String
    let name: String
    /// Fills and the selected state.
    let base: Color
    /// Text and icons in the accent, on white.
    let strong: Color
    /// A wash behind a selected row.
    let soft: Color

    static let all: [VVAccent] = [
        VVAccent(
            id: "green", name: "Green",
            base: vvColor(UIColor(vv: 120, 216, 112, 1), UIColor(vv: 120, 216, 112, 1)),
            strong: vvColor(UIColor(vv: 47, 122, 62, 1), UIColor(vv: 168, 230, 162, 1)),
            soft: vvColor(UIColor(vv: 234, 249, 236, 1), UIColor(vv: 15, 41, 21, 1))
        ),
        VVAccent(
            id: "blue", name: "Blue",
            base: vvColor(UIColor(vv: 96, 165, 250, 1), UIColor(vv: 96, 165, 250, 1)),
            strong: vvColor(UIColor(vv: 29, 78, 216, 1), UIColor(vv: 147, 197, 253, 1)),
            soft: vvColor(UIColor(vv: 239, 246, 255, 1), UIColor(vv: 23, 37, 84, 1))
        ),
        VVAccent(
            id: "purple", name: "Purple",
            base: vvColor(UIColor(vv: 167, 139, 250, 1), UIColor(vv: 167, 139, 250, 1)),
            strong: vvColor(UIColor(vv: 109, 40, 217, 1), UIColor(vv: 196, 181, 253, 1)),
            soft: vvColor(UIColor(vv: 245, 243, 255, 1), UIColor(vv: 46, 16, 101, 1))
        ),
        VVAccent(
            id: "rose", name: "Rose",
            base: vvColor(UIColor(vv: 248, 113, 113, 1), UIColor(vv: 248, 113, 113, 1)),
            strong: vvColor(UIColor(vv: 185, 28, 28, 1), UIColor(vv: 252, 165, 165, 1)),
            soft: vvColor(UIColor(vv: 255, 241, 242, 1), UIColor(vv: 76, 5, 25, 1))
        ),
        VVAccent(
            id: "orange", name: "Orange",
            base: vvColor(UIColor(vv: 251, 146, 60, 1), UIColor(vv: 251, 146, 60, 1)),
            strong: vvColor(UIColor(vv: 154, 52, 18, 1), UIColor(vv: 253, 186, 116, 1)),
            soft: vvColor(UIColor(vv: 255, 247, 237, 1), UIColor(vv: 67, 20, 7, 1))
        ),
        VVAccent(
            id: "yellow", name: "Yellow",
            base: vvColor(UIColor(vv: 250, 204, 21, 1), UIColor(vv: 250, 204, 21, 1)),
            strong: vvColor(UIColor(vv: 133, 77, 14, 1), UIColor(vv: 253, 224, 71, 1)),
            soft: vvColor(UIColor(vv: 254, 252, 232, 1), UIColor(vv: 66, 32, 6, 1))
        ),
        VVAccent(
            id: "teal", name: "Teal",
            base: vvColor(UIColor(vv: 45, 212, 191, 1), UIColor(vv: 45, 212, 191, 1)),
            strong: vvColor(UIColor(vv: 15, 118, 110, 1), UIColor(vv: 94, 234, 212, 1)),
            soft: vvColor(UIColor(vv: 240, 253, 250, 1), UIColor(vv: 4, 47, 46, 1))
        ),
        VVAccent(
            id: "pink", name: "Pink",
            base: vvColor(UIColor(vv: 244, 114, 182, 1), UIColor(vv: 244, 114, 182, 1)),
            strong: vvColor(UIColor(vv: 190, 24, 93, 1), UIColor(vv: 249, 168, 212, 1)),
            soft: vvColor(UIColor(vv: 253, 242, 248, 1), UIColor(vv: 80, 7, 36, 1))
        ),
        VVAccent(
            id: "indigo", name: "Indigo",
            base: vvColor(UIColor(vv: 129, 140, 248, 1), UIColor(vv: 129, 140, 248, 1)),
            strong: vvColor(UIColor(vv: 55, 48, 163, 1), UIColor(vv: 165, 180, 252, 1)),
            soft: vvColor(UIColor(vv: 238, 242, 255, 1), UIColor(vv: 30, 27, 75, 1))
        ),
    ]

    static let `default` = all[0]

    static func named(_ id: String?) -> VVAccent {
        all.first { $0.id == id } ?? .default
    }
}

/// Spacing in points, named like Tailwind: `x4` is `p-4` is 16.
enum VVSpace {
    static let x0: CGFloat = 0
    static let px: CGFloat = 1
    static let x0_5: CGFloat = 2
    static let x1: CGFloat = 4
    static let x1_5: CGFloat = 6
    static let x2: CGFloat = 8
    static let x2_5: CGFloat = 10
    static let x3: CGFloat = 12
    static let x3_5: CGFloat = 14
    static let x4: CGFloat = 16
    static let x5: CGFloat = 20
    static let x6: CGFloat = 24
    static let x8: CGFloat = 32
    static let x10: CGFloat = 40
    static let x12: CGFloat = 48
    static let x16: CGFloat = 64
}

/// Corner radius in points.
enum VVRadius {
    static let none: CGFloat = 0
    static let xs: CGFloat = 2
    static let sm: CGFloat = 4
    static let md: CGFloat = 6
    static let lg: CGFloat = 8
    static let xl: CGFloat = 12
    static let xl2: CGFloat = 16
    static let xl3: CGFloat = 24
    static let full: CGFloat = 9999
}

/// Font size in points, named by size.
enum VVFontSize {
    static let s10: CGFloat = 10
    static let s11: CGFloat = 11
    static let s12: CGFloat = 12
    static let s13: CGFloat = 13
    static let s14: CGFloat = 14
    static let s15: CGFloat = 15
    static let s16: CGFloat = 16
    static let s18: CGFloat = 18
    static let s20: CGFloat = 20
    static let s24: CGFloat = 24
    static let s30: CGFloat = 30
    static let s36: CGFloat = 36
    static let s48: CGFloat = 48
    static let s60: CGFloat = 60
}

enum VVFontWeight {
    static let light: Font.Weight = .light
    static let regular: Font.Weight = .regular
    static let medium: Font.Weight = .medium
    static let semibold: Font.Weight = .semibold
    static let bold: Font.Weight = .bold
}

/// Durations in seconds, and the curves they run on.
enum VVMotion {
    /// Hover and colour changes.
    static let fast: Double = 0.15
    /// Something closing.
    static let quick: Double = 0.2
    /// Tabs, the rail, a panel moving.
    static let base: Double = 0.3
    /// A view arriving.
    static let slow: Double = 0.38
    /// A whole tab set changing.
    static let slower: Double = 0.55

    /// Things moving between two places.
    static func standard(_ duration: Double = base) -> Animation {
        .timingCurve(0.4, 0, 0.2, 1, duration: duration)
    }
    /// Things arriving: fast out, long settle.
    static func enter(_ duration: Double = base) -> Animation {
        .timingCurve(0.22, 1, 0.36, 1, duration: duration)
    }
    /// The shell and rail resizing (CSS `ease`).
    static func gentle(_ duration: Double = base) -> Animation {
        .timingCurve(0.25, 0.1, 0.25, 1, duration: duration)
    }
    /// A dragged row landing.
    static func settle(_ duration: Double = base) -> Animation {
        .timingCurve(0.25, 1, 0.5, 1, duration: duration)
    }
    /// A small spring past the mark.
    static func overshoot(_ duration: Double = base) -> Animation {
        .timingCurve(0.34, 1.56, 0.64, 1, duration: duration)
    }
}
