// Desktop: the Electron shell bundles nothing from the workspace (tsc straight
// to dist/), so it gets a committed TS file; and its one page of its own,
// resources/offline.html, cannot import anything at all, so the build writes the
// custom properties into a marked block of that file.
import { HEADER_LINES, camel } from '../model.mjs';
import { cssVar } from './css.mjs';

const roleName = (r) => camel(r.name);

export function desktopTs(model) {
  const obj = (mode) =>
    `{\n${model.roles.map((r) => `  ${roleName(r)}: ${JSON.stringify(r[mode])},`).join('\n')}\n}`;
  return [
    HEADER_LINES.map((l) => `// ${l}`).join('\n'),
    '',
    '/** Semantic colours, light — the theme the app shows. */',
    `export const VV_COLOR = ${obj('light')} as const;`,
    '',
    '/** PROVISIONAL dark theme. Switched on nowhere yet. */',
    `export const VV_COLOR_DARK = ${obj('dark')} as const;`,
    '',
  ].join('\n');
}

export const OFFLINE_START = '/* vv-tokens:start — generated by packages/tokens, do not edit */';
export const OFFLINE_END = '/* vv-tokens:end */';

/** offline.html with its token block rewritten. The rest of the file is the shell's own. */
export function offlineHtml(model, current) {
  const start = current.indexOf(OFFLINE_START);
  const end = current.indexOf(OFFLINE_END);
  if (start < 0 || end < start) throw new Error('offline.html has no vv-tokens block');
  const lineStart = current.lastIndexOf('\n', start) + 1;
  const indent = current.slice(lineStart, start);
  const vars = model.roles.map((r) => `${indent}  ${cssVar(['color', ...r.name])}: ${r.light};`).join('\n');
  return `${current.slice(0, start)}${OFFLINE_START}\n${indent}:root {\n${vars}\n${indent}}\n${indent}${current.slice(end)}`;
}
