// The two colours the native platforms read before any code runs: iOS's
// AccentColor (the system tint) and Android's launcher background. Both are the
// logo green, which never follows the chosen accent.
import { parseColor } from '../model.mjs';

const brand = (model) => model.roles.find((r) => r.name.join('.') === 'brand').light;

export function accentColorset(model) {
  const { r, g, b, a } = parseColor(brand(model));
  const c = (n) => (n / 255).toFixed(3);
  return `${JSON.stringify(
    {
      colors: [
        {
          color: {
            'color-space': 'srgb',
            components: { alpha: a.toFixed(3), blue: c(b), green: c(g), red: c(r) },
          },
          idiom: 'universal',
        },
      ],
      info: { author: 'xcode', version: 1 },
    },
    null,
    2,
  ).replace(/": /g, '" : ')}\n`;
}

export function androidColors(model) {
  const { r, g, b } = parseColor(brand(model));
  const hex = [r, g, b].map((n) => n.toString(16).padStart(2, '0').toUpperCase()).join('');
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by packages/tokens. Do not edit; run `pnpm tokens:build`. -->',
    '<!-- Everything a screen paints comes from Tokens.kt; this is only what a resource must name. -->',
    '<resources>',
    `    <color name="vv_brand">#FF${hex}</color>`,
    '</resources>',
    '',
  ].join('\n');
}
