'use client';

// Console → Invite. The two ways someone gets in, on their own page rather than
// buried under the member list.
//
//   • The link — one reusable, revocable token per community. Anyone who follows
//     it lands in People → Waiting for approval; regenerating kills the old link.
//   • By email — only works for an address that already has an account, and adds
//     them straight away as an active member. Both facts are stated on the page,
//     because a form that silently 404s on unknown addresses is a trap.
//
// Aliases can be handed over in the same step, since an alias is the whole of
// what a person can do here.

import { useEffect, useState } from 'react';
import { UserPlus } from 'lucide-react';
import {
  Alert,
  Button,
  ConfirmDialog,
  Field,
  Input,
  SettingsSection,
} from '@/components/ui';
import { useConsoleAction } from '@/features/admin/components/console/ConsoleSaveContext';
import { fetchJson, fetchJsonBody } from '@/lib/fetchJson';
import { McpServerUrlRow, useMcpConnectInfo } from '@/features/settings/components/ConnectClaudePanel';
import { usePeopleSection } from './PeopleDataContext';
import { AliasToggle, type PeopleData } from './shared';

/**
 * Reusable invite link for the community. Admins copy it to share; regenerating
 * revokes the old link. Lazily generated by GET /invite the first time.
 */
function InviteLinkRow({ communityId }: { communityId: string }) {
  const [url, setUrl] = useState<string | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const runAction = useConsoleAction();

  useEffect(() => {
    let alive = true;
    fetchJson<{ url?: string }>(`/api/communities/${communityId}/invite`)
      .then((d) => { if (alive) setUrl(d.url ?? ''); })
      .catch((e: unknown) => {
        if (!alive) return;
        setUrl('');
        setLoadError(e instanceof Error ? e.message : 'Could not load the invite link');
      });
    return () => { alive = false; };
  }, [communityId]);

  const copy = async () => {
    if (!url) return;
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };

  const regenerate = async () => {
    setConfirmRegenerate(false);
    try {
      await runAction(async () => {
        const data = await fetchJson<{ url?: string }>(`/api/communities/${communityId}/invite`, { method: 'POST' });
        setUrl(data.url ?? '');
        setLoadError(null);
      });
    } catch { /* status pill shows the failure */ }
  };

  return (
    <div>
      {loadError && <Alert variant="error" inline>{loadError}</Alert>}
      <div className="flex items-center gap-2">
        <input
          readOnly
          value={url === null ? 'Loading…' : url}
          aria-label="Invite link"
          className="min-w-0 flex-1 truncate rounded-xl border border-transparent bg-surface-2 px-3.5 py-2.5 text-xs text-text-secondary"
        />
        <Button variant="pill-secondary" onClick={copy} disabled={!url}>
          {copied ? 'Copied' : 'Copy'}
        </Button>
      </div>
      <div className="mt-2 flex justify-end">
        <button
          type="button"
          onClick={() => setConfirmRegenerate(true)}
          disabled={url === null}
          className="text-xs font-medium text-text-muted transition-colors hover:text-text-primary disabled:opacity-50"
        >
          Regenerate
        </button>
      </div>

      <ConfirmDialog
        open={confirmRegenerate}
        title="Regenerate invite link"
        body="The current link will stop working immediately. Anyone holding the old link won't be able to join with it."
        confirmLabel="Regenerate"
        onConfirm={regenerate}
        onClose={() => setConfirmRegenerate(false)}
      />
    </div>
  );
}

/** Invite by email, optionally handing over aliases in the same step. */
function InviteByEmail({ communityId, aliases, onDone }: {
  communityId: string;
  aliases: PeopleData['aliases'];
  onDone: () => Promise<void>;
}) {
  const [email, setEmail] = useState('');
  const [chosen, setChosen] = useState<string[]>([]);
  const [error, setError] = useState('');
  const [added, setAdded] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const toggle = (name: string) =>
    setChosen((prev) => (prev.includes(name) ? prev.filter((x) => x !== name) : [...prev, name]));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setAdded(null);
    setLoading(true);
    const address = email.trim();
    try {
      await fetchJsonBody(`/api/communities/${communityId}/members`, 'POST', {
        email: address,
        aliases: chosen,
      });
      await onDone();
      setEmail('');
      setChosen([]);
      setAdded(address);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to add member');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <Field label="Email address">
        <Input
          type="email"
          required
          placeholder="user@example.com"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
      </Field>
      {aliases.length > 0 && (
        <Field label="Aliases">
          <div className="flex flex-wrap gap-1.5">
            {aliases.map((alias) => (
              <AliasToggle
                key={alias.name}
                name={alias.name}
                color={alias.color}
                owner={alias.owner}
                on={chosen.includes(alias.name)}
                onClick={() => toggle(alias.name)}
              />
            ))}
          </div>
        </Field>
      )}
      {error && <Alert variant="error" inline>{error}</Alert>}
      {added && (
        <Alert variant="success" inline>
          {added} is now a member. They show up under People.
        </Alert>
      )}
      <div>
        <Button type="submit" variant="pill-primary" loading={loading} loadingText="Adding…">
          <span className="inline-flex items-center gap-1.5">
            <UserPlus size={14} />
            Add to space
          </span>
        </Button>
      </div>
    </form>
  );
}

/**
 * A pointer, not a control. An MCP connection is per-person — the token belongs
 * to whoever authorises it, and access is re-derived from their membership on
 * every call — so there is nothing an admin can set up here on a member's
 * behalf. Surfacing the address next to the invite link just means admins have
 * it to hand when they onboard someone.
 */
function ConnectClaudeRow() {
  const { info } = useMcpConnectInfo();

  return (
    <div>
      <McpServerUrlRow url={info?.url ?? null} />
      <p className="mt-2 text-xs text-text-muted">
        Each member connects their own Claude from{' '}
        <a href="/settings?section=mcp" className="font-medium text-text-secondary underline underline-offset-2 hover:text-text-primary">
          Settings → MCP
        </a>
        , where the full instructions live.
      </p>
    </div>
  );
}

export default function InvitePanel() {
  const { communityId, data, error, setError, run } = usePeopleSection();

  return (
    <div className="space-y-8">
      {error && <Alert variant="error" onDismiss={() => setError(null)}>{error}</Alert>}

      <SettingsSection
        title="Invite link"
        description="Share this with anyone. Following it puts them in the waiting list on Members — nobody joins without an admin approving them."
      >
        <InviteLinkRow communityId={communityId} />
      </SettingsSection>

      <SettingsSection
        title="Invite by email"
        description="For someone who already has an account. They join immediately, with whatever aliases you tick — no approval step. If the address has never signed up, this will tell you so."
      >
        {data === null ? (
          <p className="text-sm text-text-muted">Loading…</p>
        ) : (
          <InviteByEmail
            communityId={communityId}
            aliases={data.aliases}
            onDone={() => run(async () => {})}
          />
        )}
      </SettingsSection>

      <SettingsSection
        title="Connect Claude"
        description="Members can point Claude at this space's context over MCP. Claude only ever sees what that person can already see here — their spaces, their notes, their permissions."
      >
        <ConnectClaudeRow />
      </SettingsSection>
    </div>
  );
}
