'use client';

// Console → Invite. The two ways someone gets in, on their own page rather than
// buried under the member list.
//
//   • The link — one reusable, revocable token per space. Anyone who follows
//     it lands in People → Waiting for approval; regenerating kills the old link.
//   • By email — only works for an address that already has an account, and adds
//     them straight away as an active member. Both facts are stated on the page,
//     because a form that silently 404s on unknown addresses is a trap.
//
// Aliases can be handed over in the same step, since an alias is the whole of
// what a person can do here.

import { useEffect, useState } from 'react';
import { useCopied } from '@/features/shared/hooks/useCopied';
import { UserPlusIcon } from '@/features/shared/icons';
import {
  Alert,
  Button,
  ConfirmDialog,
  Field,
  Input,
  SettingsSection,
} from '@/components/ui';
import { useConsoleAction } from '@/features/admin/components/console/ConsoleSaveContext';
import { fetchJson, fetchJsonBody } from '@/lib/fetchJson';
import { usePeopleSection } from './PeopleDataContext';
import { AliasToggle, type PeopleData } from './shared';

/**
 * Reusable invite link for the space. Admins copy it to share; regenerating
 * revokes the old link. Lazily generated by GET /invite the first time.
 */
function InviteLinkRow({ spaceId }: { spaceId: string }) {
  const [url, setUrl] = useState<string | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [copied, copy] = useCopied();
  const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const runAction = useConsoleAction();

  useEffect(() => {
    let alive = true;
    fetchJson<{ url?: string }>(`/api/communities/${spaceId}/invite`)
      .then((d) => { if (alive) setUrl(d.url ?? ''); })
      .catch((e: unknown) => {
        if (!alive) return;
        setUrl('');
        setLoadError(e instanceof Error ? e.message : 'Could not load the invite link');
      });
    return () => { alive = false; };
  }, [spaceId]);

  const copyUrl = () => { if (url) void copy(url); };

  const regenerate = async () => {
    setConfirmRegenerate(false);
    try {
      await runAction(async () => {
        const data = await fetchJson<{ url?: string }>(`/api/communities/${spaceId}/invite`, { method: 'POST' });
        setUrl(data.url ?? '');
        setLoadError(null);
      });
    } catch { /* status pill shows the failure */ }
  };

  return (
    <div>
      {loadError && <Alert variant="error" inline>{loadError}</Alert>}
      {/* Text, not an input. The link isn't editable — a box you can click into
          and type in says it is, and then hands you a Copy button for whatever
          you typed. `select-all` keeps the one thing an input was good for. */}
      <div className="flex items-center gap-2">
        <p
          aria-label="Invite link"
          className="min-w-0 flex-1 select-all truncate rounded-xl bg-surface-2 px-3.5 py-2.5 text-sm text-text-secondary"
        >
          {url === null ? 'Loading…' : url}
        </p>
        <Button variant="brand" onClick={copyUrl} disabled={!url}>
          {copied ? 'Copied' : 'Copy'}
        </Button>
      </div>
      <div className="mt-2 flex justify-end">
        <button
          type="button"
          onClick={() => setConfirmRegenerate(true)}
          disabled={url === null}
          className="text-xs font-medium text-text-muted transition-colors hover:text-text-primary disabled:opacity-50"
        >
          Regenerate
        </button>
      </div>

      <ConfirmDialog
        open={confirmRegenerate}
        title="Regenerate invite link"
        body="The current link will stop working immediately. Anyone holding the old link won't be able to join with it."
        confirmLabel="Regenerate"
        onConfirm={regenerate}
        onClose={() => setConfirmRegenerate(false)}
      />
    </div>
  );
}

/** Invite by email, naming the aliases they'd hold if they say yes. */
function InviteByEmail({ spaceId, aliases, onDone }: {
  spaceId: string;
  aliases: PeopleData['aliases'];
  onDone: () => Promise<void>;
}) {
  const [email, setEmail] = useState('');
  const [chosen, setChosen] = useState<string[]>([]);
  const [error, setError] = useState('');
  const [invited, setInvited] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const ready = email.trim().length > 0 && (aliases.length === 0 || chosen.length > 0);

  const toggle = (name: string) =>
    setChosen((prev) => (prev.includes(name) ? prev.filter((x) => x !== name) : [...prev, name]));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setInvited(null);
    setLoading(true);
    const address = email.trim();
    try {
      await fetchJsonBody(`/api/communities/${spaceId}/invitations`, 'POST', {
        email: address,
        aliases: chosen,
      });
      await onDone();
      setEmail('');
      setChosen([]);
      setInvited(address);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to send the invitation');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {/* No visible label — "Invite by email" is directly above it, and saying
          it twice is noise. The placeholder and the aria-label carry it. */}
      <Input
        type="email"
        required
        aria-label="Email address"
        placeholder="user@example.com"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
      />
      {aliases.length > 0 && (
        <Field label="Aliases">
          <div className="flex flex-wrap gap-1.5">
            {aliases.map((alias) => (
              <AliasToggle
                key={alias.name}
                name={alias.name}
                color={alias.color}
                admin={alias.admin}
                on={chosen.includes(alias.name)}
                onClick={() => toggle(alias.name)}
              />
            ))}
          </div>
        </Field>
      )}
      {error && <Alert variant="error" inline>{error}</Alert>}
      {invited && (
        <Alert variant="success" inline>
          Invitation sent to {invited}. They join when they accept it.
        </Alert>
      )}
      <div>
        {/* Grey until the form can actually do something: an address, and — when
            the space has any to hand out — at least one alias. A solid brand
            button that 400s on submit is a lie about what's ready. */}
        <Button
          type="submit"
          variant={ready ? 'brand' : 'neutral'}
          disabled={!ready}
          loading={loading}
          loadingText="Sending…"
        >
          <span className="inline-flex items-center gap-1.5">
            <UserPlusIcon size={14} />
            Send invitation
          </span>
        </Button>
      </div>
    </form>
  );
}

export default function InvitePanel() {
  const { spaceId, data, error, setError, run } = usePeopleSection();

  return (
    <div className="space-y-8">
      {error && <Alert variant="error" onDismiss={() => setError(null)}>{error}</Alert>}

      <SettingsSection title={<span className="text-base">Invite link</span>}>
        <InviteLinkRow spaceId={spaceId} />
      </SettingsSection>

      {/* Larger than the sibling headings on purpose: with the description gone
          this is the only thing naming the form under it. */}
      <SettingsSection title={<span className="text-base">Invite by email</span>}>
        {data === null ? (
          <p className="text-sm text-text-muted">Loading…</p>
        ) : (
          <InviteByEmail
            spaceId={spaceId}
            aliases={data.aliases}
            onDone={() => run(async () => {})}
          />
        )}
      </SettingsSection>

      {data !== null && data.invitations.length > 0 && (
        <SettingsSection
          title={`Waiting on a reply (${data.invitations.length})`}
          description="Sent, unanswered. Withdrawing one takes it out of their bell."
        >
          <PendingInvitations spaceId={spaceId} invitations={data.invitations} />
        </SettingsSection>
      )}
    </div>
  );
}

/** Invitations nobody has answered yet, each with the way to take it back. */
function PendingInvitations({ spaceId, invitations }: {
  spaceId: string;
  invitations: PeopleData['invitations'];
}) {
  const { busy, run } = usePeopleSection();

  const withdraw = (id: string) =>
    run(() => fetchJson(`/api/communities/${spaceId}/invitations/${id}`, { method: 'DELETE' }));

  return (
    <div className="divide-y divide-border-subtle">
      {invitations.map((invitation) => (
        <div key={invitation.id} className="flex flex-wrap items-center justify-between gap-3 py-3">
          <div className="min-w-0">
            <div className="truncate text-sm font-medium text-text-primary">{invitation.user.name}</div>
            <div className="truncate text-xs text-text-muted">
              {invitation.user.email}
              {invitation.aliases.length > 0 && ` · ${invitation.aliases.join(', ')}`}
            </div>
          </div>
          <Button
            variant="neutral"
            onClick={() => void withdraw(invitation.id)}
            disabled={busy}
            className="!px-3 !py-1.5 !text-xs"
          >
            Withdraw
          </Button>
        </div>
      ))}
    </div>
  );
}
