'use client';

// How someone gets in: one reusable, revocable token per space. Anyone who
// follows it lands in the waiting queue further down Members, and an admin
// approves them there; regenerating the link kills the old one.
//
// It is a row at the top of Members rather than a console section of its own —
// getting in and being in are the same screen — and it is deliberately the first
// thing there, because it is the only part of the page you go looking FOR.

import { useEffect, useState } from 'react';
import { useCopied } from '@/features/shared/hooks/useCopied';
import { Alert, Button, ConfirmDialog } from '@/components/ui';
import { useConsoleAction } from '@/features/admin/components/console/ConsoleSaveContext';
import { fetchJson } from '@/lib/fetchJson';
import { primeRequestCache, swrFetch } from '@/features/shared/lib/requestCache';

/**
 * Reusable invite link for the space. Admins copy it to share; regenerating
 * revokes the old link. Lazily generated by GET /invite the first time.
 */
export default function InviteLink({ spaceId }: { spaceId: string }) {
  const [url, setUrl] = useState<string | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [copied, copy] = useCopied();
  const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const runAction = useConsoleAction();

  useEffect(() => {
    let alive = true;
    // Cached: the link only changes when an admin regenerates it, and that
    // path writes the new one straight into state.
    swrFetch(`spaces:invite:${spaceId}`, () => fetchJson<{ url?: string }>(`/api/spaces/${spaceId}/invite`), (d) => {
      if (alive) setUrl(d.url ?? '');
    })
      .catch((e: unknown) => {
        if (!alive) return;
        setUrl('');
        setLoadError(e instanceof Error ? e.message : 'Could not load the invite link');
      });
    return () => { alive = false; };
  }, [spaceId]);

  const copyUrl = () => { if (url) void copy(url); };

  const regenerate = async () => {
    setConfirmRegenerate(false);
    try {
      await runAction(async () => {
        const data = await fetchJson<{ url?: string }>(`/api/spaces/${spaceId}/invite`, { method: 'POST' });
        primeRequestCache(`spaces:invite:${spaceId}`, data);
        setUrl(data.url ?? '');
        setLoadError(null);
      });
    } catch { /* status pill shows the failure */ }
  };

  return (
    <div>
      {loadError && <Alert variant="error" inline>{loadError}</Alert>}
      {/* Text, not an input. The link isn't editable — a box you can click into
          and type in says it is, and then hands you a Copy button for whatever
          you typed. `select-all` keeps the one thing an input was good for. */}
      <div className="flex items-center gap-2">
        <p
          aria-label="Invite link"
          className="min-w-0 flex-1 select-all truncate rounded-xl bg-surface-2 px-3.5 py-2.5 text-sm text-text-secondary"
        >
          {url === null ? 'Loading…' : url}
        </p>
        <Button variant="brand" onClick={copyUrl} disabled={!url}>
          {copied ? 'Copied' : 'Copy'}
        </Button>
      </div>
      <div className="mt-2 flex justify-end">
        <button
          type="button"
          onClick={() => setConfirmRegenerate(true)}
          disabled={url === null}
          className="text-xs font-medium text-text-muted transition-colors hover:text-text-primary disabled:opacity-50"
        >
          Regenerate
        </button>
      </div>

      <ConfirmDialog
        open={confirmRegenerate}
        title="Regenerate invite link"
        body="The current link will stop working immediately. Anyone holding the old link won't be able to join with it."
        confirmLabel="Regenerate"
        onConfirm={regenerate}
        onClose={() => setConfirmRegenerate(false)}
      />
    </div>
  );
}
